docs:translate docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #103
Opened 2020-07-23 06:16 UTC by f-teruhisa

`docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md`を翻訳いたしました。
レビューをお願いします。

2020-07-23 06:16 UTC, f-teruhisa commented on docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md
> +[CDN](https://ja.wikipedia.org/wiki/%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%83%87%E3%83%AA%E3%83%90%E3%83%AA%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF)を設定するには、CDN のオリジンサーバーが Next
jaのWikipediaにCDNのページがあったため、リンクをそちらに変更しております。

2020-07-23 07:23 UTC, yokinist requested changes
@f-teruhisa 
翻訳ありがとうございます！基本的には問題ないかと思います。

何点か細かい表現で Suggested change を送らせていただいたので、ご確認お願いします！
問題なさそうだったらそのまま取り込んでいただき、別途検討すべきことがあればコメントにて追記いただければと思います。宜しくおねがいします 🙏

2020-07-23 07:23 UTC, yokinist commented on docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md
> +description: カスタムアセットプレフィックスを使用すると、CDN から静的コンテンツを配信させられます。詳細はこちらをご覧ください。
```suggestion
description: カスタムアセットプレフィックスを使用すると、CDN から静的コンテンツを配信できます。詳細はこちらをご覧ください。
```
より自然な日本語にしてみましたが、いかがでしょうか？

2020-07-23 07:23 UTC, yokinist commented on docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md
> +[CDN](https://ja.wikipedia.org/wiki/%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%83%87%E3%83%AA%E3%83%90%E3%83%AA%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF)を設定するには、CDN のオリジンサーバーが Next
```suggestion
[CDN](https://ja.wikipedia.org/wiki/%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%83%87%E3%83%AA%E3%83%90%E3%83%AA%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF)を設定するには、CDN のオリジンサーバーが Next.js がホストされているドメインを解決するように、アセットプレフィックスを設定します。
```
`the domain that Next.js is hosted on` の訳としては、「ホストされているドメイン」の方が適切かなと思いましたがいかがでしょうか？

2020-07-23 07:23 UTC, yokinist commented on docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md
> +Next.js はスクリプトを読み込みプレフィックスを自動的に使用しますが、 [public](/docs/basic-features/static-file-serving.md) フォルダには何の影響もありません。 コンポーネント内で動作し、環境ごとに異なるプレフィックスを導入する方法の例として、 [こちら](https://github.com/zeit/next.js/tree/can
```suggestion
Next.js は読み込むスクリプトの中でプレフィックスを自動的に使用しますが、 [public](/docs/basic-features/static-file-serving.md) フォルダには何の影響もありません。 コンポーネント内で動作し、環境ごとに異なるプレフィックスを導入する方法の 1 つとして、 [こちら](https://github.com/zeit/next.js/tree/canary/examples/with-universal-configuration-build-time)をご参考ください。
```
「読み込みプレフィックス」とも読みかねないので、「読み込むスクリプトの中でプレフィックスを」としてみましたがいかがでしょうか？また、ここにおいては例というよりも方法の 1 つとしていう表現にとどめておく方が適切かなと思いました！

2020-07-23 07:23 UTC, yokinist commented on docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md
> +[CDN](https://ja.wikipedia.org/wiki/%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%83%87%E3%83%AA%E3%83%90%E3%83%AA%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF)を設定するには、CDN のオリジンサーバーが Next
リンクの確認 / 変更ありがとうございます！

2020-07-23 07:23 UTC, yokinist commented on docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md
> +    <small>Next.jsの設定ファイルの詳細を見る。</small>
```suggestion
    <small>Next.jsの設定ファイルについて詳細を見る。</small>
```
細かいですが `about` の訳はそのまま「〜について」の方が直接的で分かりやすい訳かと思いました

2020-07-24 05:45 UTC, f-teruhisa commented on docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md
> +description: カスタムアセットプレフィックスを使用すると、CDN から静的コンテンツを配信させられます。詳細はこちらをご覧ください。
ありがとうございます！こちらのほうが回りくどくなく、理解しやすいと思いますｍ

2020-07-24 05:46 UTC, f-teruhisa commented on docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md
> +[CDN](https://ja.wikipedia.org/wiki/%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%83%87%E3%83%AA%E3%83%90%E3%83%AA%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF)を設定するには、CDN のオリジンサーバーが Next
ホストは「されている」の方が自然な使い方だと思いますので、こちらのほうが良さそうですねｍ
ありがとうございますｍ

2020-07-24 05:47 UTC, f-teruhisa commented on docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md
> +Next.js はスクリプトを読み込みプレフィックスを自動的に使用しますが、 [public](/docs/basic-features/static-file-serving.md) フォルダには何の影響もありません。 コンポーネント内で動作し、環境ごとに異なるプレフィックスを導入する方法の例として、 [こちら](https://github.com/zeit/next.js/tree/can
確かに...気づかなかったので助かります:pray:

2020-07-24 05:47 UTC, f-teruhisa commented on docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md
> +    <small>Next.jsの設定ファイルの詳細を見る。</small>
ありがとうございますｍ 取り込まさせていただきましたｍmm

2020-07-24 05:48 UTC, chanrute reviewed
@yokinist 
コメントいただきありがとうございます！
指摘頂いた点、どれもそのとおりだと思いましたので、取り込まさせていただきました 🙏 
お手すきで再度レビューをお願いしますｍ

2020-07-24 08:10 UTC, yokinist requested changes
@f-teruhisa 
ご確認いただきありがとうございます！
表記揺れが起きていた箇所で訳が固まったので、恐縮ですが追加で2点修正お願いしたいです🙇‍♂️
https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/111#discussion_r459904359

2020-07-24 08:10 UTC, yokinist commented on docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md
> +    <b>next.config.jsの導入:</b>
```suggestion
    <b>next.config.jsの紹介:</b>
```

2020-07-24 08:10 UTC, yokinist commented on docs/api-reference/next.config.js/cdn-support-with-asset-prefix.md
> +    <small>Next.jsの設定ファイルについて詳細を見る。</small>
```suggestion
    <small>Next.jsの設定ファイルについて詳しく学びましょう。</small>
```

2020-07-25 06:48 UTC, f-teruhisa commented
@yokinist 
 チェックありがとうございます！Suggestion、取り込ませていただきましたm

2020-07-25 06:58 UTC, yokinist approved these changes
ありがとうございます！LGTMです👍

2020-07-25 08:53 UTC, hiro08gh approved these changes

2020-07-25 08:53 UTC, hiro08gh commented
翻訳ありがとうございました！LGTMです！

2020-07-25 08:53 UTC, merged

2020-07-25 08:56 UTC, hiro08gh commented
@all-contributors please add @f-teruhisa  for translation