docs: translate docs/advanced-features/customizing-babel-config.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #104
Opened 2020-07-23 06:45 UTC by hiro08gh

`docs/advanced-features/customizing-babel-config.md`を翻訳しました。確認よろしくお願いします

2020-07-23 07:01 UTC, hiro08gh commented
迷ったんですが、babelの固有名詞はBabelなので統一しました。

2020-07-23 08:55 UTC, yokinist requested changes
@hiro08gh 
翻訳ありがとうございます！
何点か細かい表現など Suggested change を送らせていただいたので、ご確認お願いします！  
また、全角/半角切り替えスペースの有無についても確認したいところが何点かあったのであわせてご確認お願いします。

問題なさそうだったらそのまま取り込んでいただき、別途検討すべきことがあればコメントにて追記いただければと思います。
宜しくおねがいします 🙇‍♂️

2020-07-23 08:55 UTC, yokinist commented on docs/advanced-features/customizing-babel-config.md
> +# Babel設定のカスタマイズ
```suggestion
# Babel 設定のカスタマイズ
```
見出しも同様に半角スペースがあったほうがいいと思いましたが、ルール/スタイルガイド的にどうでしょうか？

2020-07-23 08:55 UTC, yokinist commented on docs/advanced-features/customizing-babel-config.md
> +description: 独自の設定をNext.jsに追加して、Babelプリセットを拡張します。
```suggestion
description: 独自の設定をNext.jsに追加し、Babelプリセットを拡張します。
```
し、の方がシンプルでいいかなと思いました。またdescriptionに関しては半角スペースなくていいのかスタイルガイド/ルール的に気になりました。

2020-07-23 08:55 UTC, yokinist commented on docs/advanced-features/customizing-babel-config.md
> +Next.js のアプリに含まれる `next/babel` プリセットは、React アプリケーションや、サーバーサイドコードのコンパイルに必要なすべてのことが含まれます。ですが、デフォルトの Babel 設定を拡張したい場合は、それも可能です。
```suggestion
Next.js のアプリに含まれる `next/babel` プリセットは、React アプリケーションとサーバーサイドのコードをコンパイルするにあたって必要なことすべてが含まれます。ですが、デフォルトの Babel 設定を拡張したい場合は、それも可能です。
```
「サーバーサイドコードのコンパイルに」をより柔らかくしてみましたが、いかがでしょうか？

2020-07-23 08:55 UTC, yokinist commented on docs/advanced-features/customizing-babel-config.md
> +開始するには、アプリのトップに `.babelrc` を定義する必要があるだけです。もし、そのようなファイルを見つけた場合信頼できるソースだと考えます。それから、`next/babel`プリセットを Next.js で定義する必要があります。
```suggestion
開始するには、アプリのトップに `.babelrc` を置くだけです。もし、そのようなファイルを見つけた場合_信頼できるソース_だとみなされるため、Next.js も同様に必要とする `next/babel`プリセットを定義する必要があります。
```
- 日本語的には `.babelrc` というファイルは「定義」よりも「置く」という方が自然かなと思いました。
- `therefore` に関しては因果関係を示しているため、つなげてみました。
- 原文のイタリック表記を反映させました。
- また `Next.js needs as well` のニュアンスが失われていたので追加してみました。必要が続くのでもうちょっといい訳し方はないかなと思いますが参考までにお願いします
`therefore` については因果関係をしていると思われるので変えてみました。

2020-07-23 08:55 UTC, yokinist commented on docs/advanced-features/customizing-babel-config.md
> +これらの presets/plugins を設定する場合、カスタムした `.babelrc` の `presets` や `plugins` を追加しないでください。その代わり、`next/babel`プリセットでこのように設定します:
```suggestion
これらの presets/plugins を設定する場合、カスタムした `.babelrc` の `presets` や `plugins` を追加**しないでください**。その代わり、`next/babel`プリセットでこのように設定します:
```
- 位置迷いましたが、原文にある `**` は日本語訳にもあったほうがいいと思いました！

2020-07-23 08:55 UTC, yokinist commented on docs/advanced-features/customizing-babel-config.md
> +各設定で、利用可能なオプションについてはドキュメントサイトに訪れて学んでください。
```suggestion
各設定で、利用可能なオプションについてはドキュメントサイトをご覧ください。
```
- ここは恐らく詳しくはここから参照してくださいのようなニュアンスなので厳密には訳さず、「ご覧ください」としてみました。

2020-07-23 08:55 UTC, yokinist commented on docs/advanced-features/customizing-babel-config.md
> +> `"preset-env"`の `mobules` オプションは `false` にすべきで、そうでなければ、webpackのコード分割はオフになります。
```suggestion
> `"preset-env"`の `mobules` オプションは `false` にすべきで、そうでなければ、webpackのコード分割はされません。
```
`オフになる` -> `されない` なので自然な訳にしてみました。

2020-07-23 09:43 UTC, hiro08gh commented on docs/advanced-features/customizing-babel-config.md
> +# Babel設定のカスタマイズ
ここはスタイルガイドに合わせてスペースを入れるべきでした！

2020-07-23 09:45 UTC, hiro08gh commented on docs/advanced-features/customizing-babel-config.md
> +開始するには、アプリのトップに `.babelrc` を定義する必要があるだけです。もし、そのようなファイルを見つけた場合信頼できるソースだと考えます。それから、`next/babel`プリセットを Next.js で定義する必要があります。
ありがとうございます！！こちらの方が自然なので、採用させていただきます！

2020-07-23 09:51 UTC, hiro08gh commented on docs/advanced-features/customizing-babel-config.md
> +description: 独自の設定をNext.jsに追加して、Babelプリセットを拡張します。
descriptionにも半角スペースはあった方がいいですね！修正します。

2020-07-24 00:37 UTC, hiro08gh commented
修正しました。確認お願いします。

2020-07-24 00:53 UTC, yokinist requested changes
ありがとうございます、問題なさそうです！
他、見落としていた箇所が1点あったためコメントいたしました。
そちらだけご確認ください🙇‍♂️

2020-07-24 00:53 UTC, yokinist commented on docs/advanced-features/customizing-babel-config.md
> +> Next.jsは、サーバーサイドのコンパイルに現在のNode.jsのバージョンを使用します。
```suggestion
> Next.jsは、サーバーサイドのコンパイルに**現在の**Node.jsのバージョンを使用します。
```
見落としていましたが、こちらも原文同様 `**` で現在のバージョンを強調したほうがいいと思いました！

2020-07-24 01:03 UTC, hiro08gh commented on docs/advanced-features/customizing-babel-config.md
> +> Next.jsは、サーバーサイドのコンパイルに現在のNode.jsのバージョンを使用します。
すみません！自分も見落としてました！

2020-07-24 01:21 UTC, hiro08gh commented
修正しました！

2020-07-24 01:41 UTC, yokinist submitted a review, later dismissed
LGTMです🙌
ありがとうございます！

2020-07-24 02:52 UTC, hoosan submitted a review, later dismissed

2020-07-24 03:02 UTC, thesugar requested changes
インラインコードブロックの前後のスペースと、細かい typo です。2 人目レビューのあとに重ねてですみません。。（後から修正するのも面倒かと思うので 💦 ）

2020-07-24 03:02 UTC, thesugar commented on docs/advanced-features/customizing-babel-config.md
> +description: 独自の設定をNext.js に追加し、Babel プリセットを拡張します。
```suggestion
description: 独自の設定を Next.js に追加し、Babel プリセットを拡張します。
```

2020-07-24 03:02 UTC, thesugar commented on docs/advanced-features/customizing-babel-config.md
> +`next/babel`はプリセットを含みます:
```suggestion
`next/babel` はプリセットを含みます:
```

2020-07-24 03:02 UTC, thesugar commented on docs/advanced-features/customizing-babel-config.md
> +これらの presets/plugins を設定する場合、カスタムした `.babelrc` の `presets` や `plugins` を追加**しないでください**。その代わり、`next/babel`プリセットでこのように設定します:
```suggestion
これらの presets/plugins を設定する場合、カスタムした `.babelrc` の `presets` や `plugins` を追加**しないでください**。その代わり、`next/babel` プリセットでこのように設定します:
```

2020-07-24 03:02 UTC, thesugar commented on docs/advanced-features/customizing-babel-config.md
> +> `"preset-env"` の `mobules` オプションは `false` にすべきで、そうでなければ、webpack のコード分割されません。
```suggestion
> `"preset-env"` の `modules` オプションは `false` にすべきで、そうでなければ、webpack のコード分割はされません。
```
- modules の typo 修正
- 「コード分割されません」より「コード分割はされません」のほうが日本語として自然かと思いました！

2020-07-24 04:00 UTC, yokinist submitted a review, later dismissed

2020-07-24 04:21 UTC, thesugar approved these changes

2020-07-24 04:34 UTC, yokinist approved these changes

2020-07-24 04:36 UTC, merged

2020-07-24 04:36 UTC, yokinist commented
@all-contributors please add @hiro08gh for translation