docs: translate docs/routing/introduction.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #106
Opened 2020-07-23 09:21 UTC by karur4n

docs/routing/introduction.md を翻訳しました

確認よろしくお願いします

2020-07-23 09:22 UTC, karur4n commented on docs/routing/introduction.md
> +description: Next.js はファイルシステムに沿った、独自の思想に基づくルーターがビルトインで導入されています。このページで学んでいきましょう。
opinionated の翻訳に迷いました

2020-07-25 02:21 UTC, hoosan requested changes
翻訳いただきありがとうございます！いくつかコメントしましたのでご確認ください🙏

2020-07-25 02:21 UTC, hoosan commented on docs/routing/introduction.md
> +description: Next.js はファイルシステムに沿った、独自の思想に基づくルーターがビルトインで導入されています。このページで学んでいきましょう。
「独自の思想に基づく」に賛成です！

2020-07-25 02:21 UTC, hoosan commented on docs/routing/introduction.md
> +`pages` ディレクトリ内のファイルは次の代表的なパターンで定義されます。
```suggestion
`pages` ディレクトリ内のファイルは次の一般的なパターンで定義されます。
```
「代表的」でも問題ないようには思うのですが、ここで言っているルーティングパターンの話では「一般的な」が良いかと思うのですがいかがでしょう？

2020-07-25 02:21 UTC, hoosan commented on docs/routing/introduction.md
> +ルーターはネストされたファイルもサポートします。もしネストされたフォルダ構造にファイルを作れば、同じようにルーティングされます。
```suggestion
ルーターはネストされたファイルもサポートします。ネストされたフォルダ構造を作ると、内部に置かれたファイルも同じようにルーティングされます。
```
ここは"If you create a nested folder structure"が一つのif節で、"files will be automatically routed in the same way still."が一つの節ですので、createが係る目的語は"folder structure"、後半の節の主語がfilesになるようにしてみました

2020-07-25 02:21 UTC, hoosan commented on docs/routing/introduction.md
> +動的なセグメントにマッチさせたければ角括弧（ブラケット）を使うことができます。パラメーターに名前を付けてマッチされられます。
```suggestion
動的なセグメントにマッチさせたければブラケット構文を使うことができます。名前をつけたパラメーターとのマッチが可能です。
```
syntaxを含めた方が良いかと思いました！
「ブラケット記法」と「ブラケット構文」のどちらが良いか（または他に適切な表現はあるか）は議論の余地がありそうですので、
二人目のレビュアーの意見も聞きたいです。
また、後半の「マッチされられます」が少し気になったのでsuggestionしてみました。

2020-07-25 02:21 UTC, hoosan commented on docs/routing/introduction.md
> +Next.js のルーターは、シングルページアプリケーションのようにクライアントサイドでのページ間を遷移できます。
```suggestion
Next.js のルーターは、シングルページアプリケーションのようにクライアントサイドでのページ間遷移が可能です。
```
「クライアントサイドでのページ間を遷移できます。」が少し気になりました。
「クライアントサイドでのページ間遷移が可能です。」はどうでしょう？

2020-07-25 02:21 UTC, hoosan commented on docs/routing/introduction.md
> +`Link` という React コンポーネントはクライアントサイドでの遷移を提供します。
```suggestion
このクライアントサイドでのページ遷移のために、`Link` という React コンポーネントが提供されています。
```
上との文章の繋がりから、ページ遷移のために`Link` という React コンポーネントが提供されているという言い方が良いかと思いましたがいかがでしょう？

2020-07-25 02:21 UTC, hoosan commented on docs/routing/introduction.md
> +[動的なパスセグメント](/docs/routing/dynamic-routes.md)でリンクするとき、ルータがどの JavaScript ファイルを読む込むのかを知るために `href` と `as` を渡す必要があります。
```suggestion
[動的なパスセグメント](/docs/routing/dynamic-routes.md)でリンクするとき、ルータがどの JavaScript ファイルを読む込むのかが分かるように、 `href` と `as` を渡す必要があります。
```
「知るために」が少し直訳なので、少し言い換えてみましたがどうでしょうか？

2020-07-25 02:21 UTC, hoosan commented on docs/routing/introduction.md
> +- `href` - `pages` ディレクトリ中のページの名前。例：`/blog/[slug]`.
```suggestion
- `href` - `pages` ディレクトリ中のページの名前です。例えば `/blog/[slug]` のようにします。
```
日本語が句点で終わるように直しました。

2020-07-25 02:21 UTC, hoosan commented on docs/routing/introduction.md
> +- `as` - ブラウザに表示される URL. 例：`/blog/hello-world`.
```suggestion
- `as` - ブラウザに表示される URL です。以下の例では `/blog/hello-world` になります。
```
こちらも同様です！

2020-07-25 02:21 UTC, hoosan commented on docs/routing/introduction.md
> +`as` プロパティも動的に生成できます。as プロパティでページを渡されたポストのリストを表示するときは次のようになります。
```suggestion
`as` プロパティも動的に生成できます。as プロパティでページを渡されたポストのリストを表示するときは次のようになります:
```
コードブロック手前のコロンはそのままでお願いします🙏

2020-07-25 02:21 UTC, hoosan commented on docs/routing/introduction.md
> +## ルーターを注入する
```suggestion
## ルーターを React コンポーネント内で使う
```
ここまで"file-system based router"の話をしていて、
この章では備考的にnext/routerのuseRouterやwithRouterなどのReact コンポーネント内でのルーターの使用について言及しているので、injectingの意味しているところを平たく表現した方が良いと思いましたがどうでしょうか？
もう一人のレビュアーの意見を聞きたいです。

2020-07-25 02:49 UTC, hiro08gh commented on docs/routing/introduction.md
> +`as` プロパティも動的に生成できます。as プロパティでページを渡されたポストのリストを表示するときは次のようになります。
```suggestion
`as` プロパティも動的に生成できます。プロパティとしてページに渡されたポストのリストを表示する時は次のようになります:
```

2020-07-25 02:49 UTC, hiro08gh commented on docs/routing/introduction.md
> +`as` プロパティも動的に生成できます。as プロパティでページを渡されたポストのリストを表示するときは次のようになります。
`as プロパティでページを渡されたポストのリストを表示するときは次のようになります`ここは、
`プロパティとしてページに渡されたポストのリストを表示する時は次のようになります:`の方が自然かと思いました。

2020-07-25 02:49 UTC, hiro08gh commented on docs/routing/introduction.md
> +## ルーターを注入する
Inject自体に`導入する`という意味があるので、ここは`ルーターを導入する`が一番自然だと思いました。

2020-07-25 02:49 UTC, hiro08gh commented on docs/routing/introduction.md
> +## ルーターを注入する
inject自体に導入するという意味があるので、ここはルーターを導入するが一番自然だと思いました。

2020-07-25 02:50 UTC, hiro08gh commented on docs/routing/introduction.md
> +`as` プロパティも動的に生成できます。as プロパティでページを渡されたポストのリストを表示するときは次のようになります。
`as プロパティでページを渡されたポストのリストを表示するときは次のようになります:`ここは、
`プロパティとしてページに渡されたポストのリストを表示する時は次のようになります:`の方が自然かと思いました。

どうでしょうか？

2020-07-25 02:58 UTC, hiro08gh commented on docs/routing/introduction.md
> +動的なセグメントにマッチさせたければ角括弧（ブラケット）を使うことができます。パラメーターに名前を付けてマッチされられます。
自分は「ブラケット記法」が一般的だと思うので、ここは「ブラケット記法」がいいと思いました！

2020-07-25 13:21 UTC, karur4n commented on docs/routing/introduction.md
> +動的なセグメントにマッチさせたければ角括弧（ブラケット）を使うことができます。パラメーターに名前を付けてマッチされられます。
ありがとうございます！
https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/106/commits/b9efc20f8585a099d6994ee36a075547e1eccfe3

2020-07-25 13:23 UTC, karur4n commented on docs/routing/introduction.md
> +## ルーターを注入する
「ルーター」という言葉を Next.js にある機構としてのルーターなのか、コード中の router オブジェクトなのか、
はっきり分かるように示したほうがいいかと思い Suggested change を採用させていただきました 🙏

2020-07-25 13:27 UTC, karur4n commented on docs/routing/introduction.md
> +`as` プロパティも動的に生成できます。as プロパティでページを渡されたポストのリストを表示するときは次のようになります。
ありがとうございます！
こちら採用させていただきました
https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/106#discussion_r460355070


https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/106/commits/18f188e03e530858c531cd001369922c82aff1a3

2020-07-26 01:23 UTC, hoosan approved these changes
修正ありがとうございます！私からはLGTMです👍

2020-07-26 01:27 UTC, hiro08gh commented
翻訳していただきありがとうございました！LGTMです！

2020-07-26 01:27 UTC, hiro08gh approved these changes

2020-07-26 01:27 UTC, merged

2020-07-26 01:30 UTC, hiro08gh commented
@all-contributors please add @karur4n  for translation