Docs/api reference/next/router
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #113
Opened 2020-07-23 15:31 UTC by okakyo

`docs/api reference/next/router.md` を翻訳しました。

- 原文を直接訳す際、表現が難しい用語（props, state, Navigations etc,,,） については、英単語そのまま、あるいは直接カタカナに訳しました。
- 一部日本語で統一されていない箇所（能動的、受動的など）で不安があるため、こういったところを特に注意してレビューしてくれると嬉しいです。

和訳プロジェクトに初投稿で、つたない日本語で訳してしまったところがあるかもしれませんが、
レビューのほどよろしくお願いいたします！

2020-07-24 07:57 UTC, thesugar requested changes
翻訳ありがとうございます！！
また、和訳プロジェクトに初投稿とのことで、それについても大変嬉しく思います。

今回翻訳していただいた Router の部分は、分量も多く、また、英文の問題のみにとどまらず、Router そのものの技術的な仕様も必ずしもわかりやすくなかったりするので、大変な部分もあったかと思います。

私のほうでレビュー致しましたのでご確認ください。
元々の原文が長いぶん、コメントを入れた箇所も多くなってしまっていますがご容赦ください。

不明点などがあればなんなりとおっしゃってください。
よろしくお願いします。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +description: Next.js Router のAPIやuseRouter フックを利用したルーターインスタンスの使い方について学んでいきます。
```suggestion
description: Next.js の Router API について学び、useRouter フックを利用してページ内のルーターインスタンスにアクセスしてみましょう。
```
- Next.js Router の API は「Next.js の Router API」としたほうがわかりやすいかと思いました。
- Learn more about the API ... and access というふうに、Learn more about が the API と access にかかるように訳出いただいておりますが、ここでの access は動詞と解釈したほうが自然だと思います。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +> この記事を読む前に、[Routing Introduction](/docs/routing/introduction.md)をあらかじめ参照することをおすすめします。
```suggestion
> 先に進む前に、まずは[ルーティング入門](/docs/routing/introduction.md)をお読みになることをお勧めします。
```
こちらは https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/blob/master/docs/api-reference/next/link.md の同じ部分と統一させてください🙇‍♂️

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +もし、アプリ内の関数コンポーネントに含まれる [`router` object](#router-object) へアクセスしたいときは、 `useRouter` フックを利用できます。以下の例を見てください。
```suggestion
アプリ内の関数コンポーネントの中で [`router` オブジェクト](#router-オブジェクト) へアクセスしたいときは、 `useRouter` フックを利用できます。以下の例をご覧ください:
```
- ここでの inside は前置詞ではなく副詞と解釈して、「関数コンポーネントに含まれる `router` オブジェクトへアクセスしたいとき」より「関数コンポーネントの中で `router` オブジェクトへアクセスしたいとき」としたほうが自然だと思います。
- コードブロック直前のコロン（:）はコロンのままでお願いします 🙏

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +> `useRouter` は、[React Hook](https://reactjs.org/docs/hooks-intro.html)、クラスとして扱うことができません。[withRouter](#withRouter)を利用するか、関数コンポーネントでラップしたクラスを用いるかのいづれかで扱うことができます。
```suggestion
> `useRouter` は、[React Hook](https://ja.reactjs.org/docs/hooks-intro.html) であり、したがってクラスとともに使用することはできません。[withRouter](#withRouter) を利用するか、関数コンポーネントでクラスをラップしてください。
```
「クラスとして扱うことができません」->「クラスとともに使用することはできません」としました。useRouter は React フックなのでクラスコンポーネントでは利用できない（関数コンポーネントでのみ利用できる）という意味だと思われます。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +続いて、[`useRouter`](#useRouter)と[`withRouter`](#withRouter)を使って返す `router` object の定義について書いていきます。:
```suggestion
[`useRouter`](#useRouter) と [`withRouter`](#withRouter) の両方から返却される `router` オブジェクトの定義は以下のとおりです:
```
-「続いて〜書いていきます」はやや砕けた印象なので「〜は以下のとおりです」という訳にしました。
- 「useRouter と withRouter を使って返す」という文だとやや意味が通りづらいので、ここは原文に忠実に「useRouter と withRouter の両方から返却される（返される/リターンされる）」という訳でよいかと思います。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +- `asPath`: `String` - ブラウザーに反映されている実際のパス名（クエリーも含まれます）を返します。
```suggestion
- `pathname`: `String` - 現在のルートです。 これは `/pages` ディレクトリ内でのページのパスです。
- `query`: `Object` - オブジェクトに解釈されたクエリ文字列です。もし、ページに[データ取得要求](/docs/basic-features/data-fetching.md) が含まれなければ、プリレンダリング時には空オブジェクトになります。デフォルトでは `{}` になります。
- `asPath`: `String` - ブラウザに表示される実際のパス（クエリも含まれる）です。
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +もし、[`useRouter`](#useRouter) がうまく扱えない場合、`withRouter` も[`router` object](#router-object) と同様にコンポーネントに加えることができます。次のように使っていきます。:
```suggestion
[`useRouter`](#useRouter) が最適でない場合、`withRouter` を使うことで同様の [`router` オブジェクト](#router-オブジェクト)をコンポーネントに加えることができます。使い方は以下のとおりです:
```
「withRouter が router オブジェクトと同様にふるまう」のではなく「withRouter を使っても（useRouterと）同様の router オブジェクトを扱える」という訳が適切かと思います！

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +`next/router` でエクスポートされた `Router` API は次のように定義されます。
```suggestion
`Router` の API は `next/router` からエクスポートされます。Router API は以下のように定義されています。
```
原文の「The API of `Router`, exported by `next/router`, is defined below.」ですが、ここであえて "`Router` API" と表記せずに "The API of `Router`" と記述していることから、あらためて Router API 自体について説明しようとしているニュアンスがうかがえます。
また、原文はカンマで , exported 〜, is defined 〜と書き連ねているので、「## Router API」という節名を受けて「（その節名の Router API とは） `Router` の API のことで、（それは）`next/router` からエクスポートされるもので、（そしてそれは）以下のように定義されているよ」という流れの文章かと思います。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +クライアントサイドのトランジションを扱います。このメソッドは[`next/link`](/docs/api-reference/next/link.md) では不十分な場合に役立ちます。
```suggestion
クライアント側のページ遷移を処理します。このメソッドは [`next/link`](/docs/api-reference/next/link.md) では不十分な場合に役立ちます。
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
>  </details>
すみません、この部分だけ他の箇所と違ってうまく suggestion 表示できないのですが、この部分も以下のように日本語にしていただけると幸いです！
```
<details>
  <summary><b>例</b></summary>
  <ul>
    <li><a href="https://github.com/zeit/next.js/tree/canary/examples/using-router">ルーターを利用する</a></li>
  </ul>
</details>
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +  - [`shallow`](/docs/routing/shallow-routing.md): 再実行される前に現在のページのパスを更新します。 [`getStaticProps`](/docs/basic-features/data-fetching.md#getstaticprops-static-generation), [`getServerSideProps`](/docs/ba
```suggestion
- `url` - 遷移先の URL です。通常、`page` の名前です。
- `as` - URL のオプションのデコレータで、ブラウザに表示されます。デフォルトは `url` です。
- `options` - 以下の設定オプションを持つ、オプションのオブジェクトです:
  - [`shallow`](/docs/routing/shallow-routing.md): [`getStaticProps`](/docs/basic-features/data-fetching.md#getstaticprops静的生成)、[`getServerSideProps`](/docs/basic-features/data-fetching.md#getserversidepropsサーバーサイドレンダリング) あるいは [`getInitialProps`](/docs/api-reference/data-fetching/getInitialProps.md) を再実行することなく現在のページのパスを更新します。デフォルトでは `false` です。
```

- Optional は「オプションの」と訳しました。「任意の」という訳も決して誤りではありませんが、any の「任意」と区別がつかないためです。
- `as` にかんする部分の訳は、わかりやすさを意識して「URL のオプションのデコレータで、ブラウザに表示されます」としました。これは、たとえば `Router.push("/hoge", "fuga")` とすると `〜/hoge` ページに遷移するもののブラウザのアドレスバーには `〜/fuga` と表示されます（`as` を設定しなければ、ブラウザのアドレスバーには普通に `〜/hoge` と表示されます）、、ということを言っている文だと思います。
- また、他のドキュメントへのリンクは、翻訳済みのものは翻訳後のものへ修正しました（#getstaticprops静的生成 と #getserversidepropsサーバーサイドレンダリング）

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +> 外部URL をRouter`で使う必要がない場合、[window.location](https://developer.mozilla.org/en-US/docs/Web/API/Window/location) が先ほどの場合には向いています。
```suggestion
> 外部 URL に対しては `Router` を使う必要がありません。この場合は [window.location](https://developer.mozilla.org/ja/docs/Web/API/Window/location) がより適しています。
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +あらかじめ定義されたルートの `pages/about.js` にナビゲーションする場合:
```suggestion
事前に定義されたルートである `pages/about.js` に遷移する場合:
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +動的ルートの `pages/post/[pid].js`へナビゲーションする場合:
```suggestion
動的ルートの `pages/post/[pid].js` へ遷移する場合:
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +URL オブジェクトも、さきほどの[`next/link`](/docs/api-reference/next/link.md#with-url-object) と同じように扱うことができます。`url` と `as` パラメータとを扱う場合は次のようになります。:
```suggestion
URL オブジェクトは、[`next/link`](/docs/api-reference/next/link.md#urlオブジェクト) で URL オブジェクトを用いる場合と同じように扱うことができます。`url` と `as` パラメータの両方で有効です:
```
Router.push(url, as, options) の url パラメータならびに as パラメータのどちらにおいても URL オブジェクトを利用できるという意味です。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +[`next/link`](/docs/api-reference/next/link.md) の `replace` prop に似た `Router.replace` は、`history` スタックに新しい URL エントリを追加されるのを防ぎます。次の例を見てください。:
```suggestion
[`next/link`](/docs/api-reference/next/link.md) の `replace` prop に似ています。`Router.replace` を使うと、`history` スタックに新しい URL エントリは追加されません。次の例をご覧ください:
```

「## Router.replace」という節のタイトルがあって、→「（そのタイトルのRouter.replaceは）〜〜に似ていて、（そして）それを使うとこれこれこういう挙動になります」という流れがわかるような訳にしました。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +`Router.replace` の API は [`Router.push`](#router.push)で使われる API　と全く同じ値を返します。
```suggestion
`Router.replace` の API は [`Router.push`](#router.push) で使われる API と全く同じです。
```
Router.push("/home") と Router.replace("/home") のように、API の使い方が同じという意味合いかと思われます。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +クライアントサイドのトランジションを高速化するためのページを呼び出します。`next/link` をページを自動的に先読みに行われるとき、このメソッドは [`next/link`](/docs/api-reference/next/link.md) を用いないナヴィゲーションでしか役立ちません。
```suggestion
クライアント側のページ遷移を高速化するためにページをプリフェッチします。このメソッドは [`next/link`](/docs/api-reference/next/link.md) を用いないページ遷移においてのみ有用です。というのも、`next/link` は自動的にページのプリフェッチ周りの面倒を見てくれるからです。
```

ここでの as は同時性ではなく理由を表すものとして訳出するのが適切なケースかと思われます。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +> このAPI は、本番環境用の機能です。開発環境でページを先読みすることはできません。
```suggestion
> この API は、本番環境限定の機能です。Next.js は開発環境ではページをプリフェッチしません。
```
- 本番環境「限定」として、only を明示的に訳出しました
- Next.js doesn't prefetch〜なので、「できません」でなく「しません」として原文に忠実に訳しました。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +- `as` - `url` に付属する [dynamic routes](/docs/routing/dynamic-routes) を前もって呼ばれるデコレータです.　デフォルトで `url`を返します。
```suggestion
- `url` - `pages` ディレクトリに含まれる `page` へのパスです。
- `as` - `url` のオプションのデコレータであり、[動的ルート](/docs/routing/dynamic-routes) をプリフェッチするために用いられます。デフォルトでは `url` です。
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +例えば。ログインページを持ち、ログイン後にユーザーをダッシュボードにリダイレクトさせる場合を考えます。この時は次のようにダッシュボードを前もって呼びだし、画面をより高速にトランジションできます。:
```suggestion
例えば、ログインページがあり、ログイン後にユーザーをダッシュボードにリダイレクトさせるとしましょう。こうしたケースでは、次の例のように、より高速なページ遷移を行うためにダッシュボードをプリフェッチすることができます:
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
>          /* Form data */
```suggestion
        /* フォームのデータ */
```
ここでは、ログイン時のフォーム（例えばユーザーID やパスワードなど）を指しているものと思われます。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +      //　すでに先読みされたダッシュボードページに、クライアントサイドの高速なトランジションを行います。
```suggestion
      // プリフェッチ済みのダッシュボードページに、クライアント側で高速に遷移します 
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +    // ユーザーがログイン後に訪れた際に、ダッシュボードページの先読みを行います。
```suggestion
    // ダッシュボードページをプリフェッチします。ユーザーがログイン後にそのページを訪れることになるからです。
```
ここも、as は理由と解釈するのが適切かと思われます

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
すみません、他の箇所と違って suggestion 表示できないのですが、
以下 195 行目の部分も
```
 {/* フォームのフィールド */}
```
というように日本語にしていただけますと幸いです。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +一部の場合 ( 例えば、[Custom Server](/docs/advanced-features/custom-server.md)を使用する場合 ) において、ルーターが実行される前に[popstate](https://developer.mozilla.org/en-US/docs/Web/Events/popstate) を呼び出して、何かさせたい場合があります。
```suggestion
場合によっては（例えば、[カスタムサーバー](/docs/advanced-features/custom-server.md)を使用する場合）、[popstate](https://developer.mozilla.org/en-US/docs/Web/Events/popstate) をリッスンして、ルーターが動作する前に何かしたいということがあるかもしれません。
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +以下の例のように、リクエストを扱う際(例えば、SSR リフレッシュさせたいとき)に利用できます。
```suggestion
これを用いてリクエストを操作したり、SSR によるリフレッシュを強制したりすることができます。以下に示す例のようになります:
```
「以下の例のように、」は文頭でもいいのですが、「これを用いて〜」という文章が続くため、その文中の「これ」が何を指しているか若干わかりづらくなってしまう懸念などから「これを用いて〜できます。以下に示す例のようになります」という訳にしました。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
うまく差分表示できないのですが、
こちらのコードブロック内の英文も以下のように日本語に修正していただけると幸いです！

```jsx
import Router from 'next/router';
Router.beforePopState(({ url, as, options }) => {
  // この 2 つのルートだけを許可したい！
  if (as !== '/' && as !== '/other') {
    // 不正なルートは 404 として SSR でレンダリングする
    window.location.href = as;
    return false;
  }
  return true;
});
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +  - `options`: `Object` - [Router.push](#router.push) で送信される追加オプションを返します。
```suggestion
- `cb` - 入力された `popstate` イベントに対して実行される関数です。この関数は、以下の props を持つオブジェクトとしてイベントの状態を受け取ります: 
  - `url`: `String` - 新しい state のためのルートです。これは通常 `page` の名前です。
  - `as`: `String` - ブラウザに表示される URL です。
  - `options`: `Object` - [Router.push](#router.push) によって送信される追加のオプションです。
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +もし、`beforePopState` 関数が `false` を返したとき、`Router`は `popstate` を扱えません。この場合、操作することになります。[Disabling file-system routing](/docs/advanced-features/custom-server.md#disabling-file-system-routing)を参照してください。
```suggestion
`beforePopState` に渡した関数が `false` を返却する場合、`Router` は `popstate` を処理しないため、その場合は自分の責任で `popstate` を処理することになります。 [ファイルシステムのルーティングを無効化する](/docs/advanced-features/custom-server.md#disabling-file-system-routing) をご覧ください。
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +ブラウザのバックボタンと同様に、ページを戻します。クリックすると `window.history.back()` が実行されます。
```suggestion
履歴を遡ります。ブラウザの戻るボタンをクリックするのと同じです。`window.history.back()` が実行されます。
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +ブラウザのリフレッシュボタンと同様に、現在の URL でリロードされます。クリックすると、`window.location.reload()` が実行されます。
```suggestion
現在の URL をリロードします。ブラウザの更新ボタンをクリックするのと同じです。`window.location.reload()` が実行されます。
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
>  </details>
```
<details>
  <summary><b>例</b></summary>
  <ul>
    <li><a href="https://github.com/zeit/next.js/tree/canary/examples/with-loading">ページ読み込みインディケータと一緒に利用する</a></li>
  </ul>
</details>
```

こちらも（例によって suggestion 表示になっておらず恐縮ですが）日本語にしていただけると幸いです！

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +Router 内で発生した様々なイベントを受け取ることができます。こちらがサポートされているイベントの一覧です。:
```suggestion
Router 内で発生する様々なイベントをリッスンできます。こちらがサポートされているイベントの一覧です:
```
listen はそのまま「リッスンする」か、日本語にするとしたら「受け取る」よりも「待ち受ける」のほうが適切かと思います（ただ、ほぼ日本語化しているので「リッスンする」でよいかと思われます）。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +- `hashChangeComplete(url)` - ハッシュが変更されたのにページが変更されないときに実行されます。
```suggestion
- `routeChangeStart(url)` - ルートの変更が開始した時に発火します。
- `routeChangeComplete(url)` - ルートが完全に変更され終わったときに発火します。
- `routeChangeError(err, url)` - ルート変更時にエラーが発生した際、あるいはルートの読み込みが中止された際に発火します。
  - `err.cancelled` - ページ遷移が中止されたかどうかを示します。
- `beforeHistoryChange(url)` -ブラウザの履歴を変更する直前に発火します。 
- `hashChangeStart(url)` - ハッシュが変更されるが、ページが変更されないときに発火します。
- `hashChangeComplete(url)` - ハッシュの変更が完了したが、ページが変更されないときに実行されます。
```
- fires は（イベントの）発火として訳しました。
- Fires just before changing the browser's history は「ブラウザの履歴が変更される直前」よりも、「ブラウザの履歴を変更する直前」というふうに、原文に忠実に change を他動詞として訳出したほうが適切と思われます。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +> この時の  `url`　は、ブラウザーで表示されているものです。もし、`Router.push(url, as)`(あるいはそれに似たもの)　を呼び出すと、`url` の値は `as`になります。
```suggestion
> ここでの `url` はブラウザに表示されている URL です。`Router.push(url, as)`（あるいは類似のメソッド）を呼び出すと、`url` の値は `as` になります。
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +例えば、ルーターイベント `routeChangeStart` を呼ぶには、次のようにしてください。:
```suggestion
例えば、ルーターのイベント `routeChangeStart` をリッスンするには次のようにしてください:
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +もし、そのイベントを呼び出したくないのであれば、`off`メソッドをつかってイベントを解除してください。
```suggestion
イベントをリッスンしたくなくなったら、`off` メソッドをつかって購読を解除してください。
```
- no longer は「もはや〜ない」という意味なので、「（イベントをリッスンしていたけれど、状況が変わって）もうリッスンしたくなくなった」という変化のニュアンスが出るように訳してみました。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +もし、ルートのローディングが中止になった際（２つのリンクが連続で高速にクリックされたとき）、`routeChangeError`が実行されます。そして、渡された `err` には以下の例のように、`cancelled`プロパティに `true` を格納します。
```suggestion
ルートの読み込みがキャンセルされたら（例えば、2 つのリンクを続けて素早くクリックした場合）、`routeChangeError` が発火します。そして、渡される `err` には、以下の例のように、`true` がセットされた `cancelled` プロパティが含まれます:
```

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
> +コンポーネントがマウントされたとき([useEffect](https://reactjs.org/docs/hooks-effect.html) 、または [componentDidMount](https://reactjs.org/docs/react-component.html#componentdidmount) / [componentWillUnmount](https://re
```suggestion
ルーターのイベントは、コンポーネントがマウントされたとき（[useEffect](https://ja.reactjs.org/docs/hooks-effect.html) 、または [componentDidMount](https://ja.reactjs.org/docs/react-component.html#componentdidmount) / [componentWillUnmount](https://ja.reactjs.org/docs/react-component.html#componentwillunmount）、あるいはイベントが発生したときに、以下の例のように、imperatively に登録する必要があります:
```

[スタイルガイド](https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/blob/master/styleguide.md) にしたがって imperatively はそのまま英語のままにしています（やや唐突感もありますが…）。
意味するところは、（Router 関連の API はほとんどそうですが）Router.events.on() のように（declarative（宣言的）でなく）命令的な書き方で記述しますよ、という意味かと思います。

2020-07-24 07:57 UTC, thesugar commented on docs/api-reference/next/router.md
>  ### router object
```suggestion
### router オブジェクト
```

2020-07-24 12:16 UTC, okakyo commented on docs/api-reference/next/router.md
> +もし、そのイベントを呼び出したくないのであれば、`off`メソッドをつかってイベントを解除してください。
unsubscribe の箇所を「購読を解除する」ではニュアンスがおかしくなると思うので、イベントを解除するととらえてイベントを解除したほうがいいと思います。

2020-07-24 12:27 UTC, thesugar commented on docs/api-reference/next/router.md
> +もし、そのイベントを呼び出したくないのであれば、`off`メソッドをつかってイベントを解除してください。
さっそくのご確認ありがとうございます！ 🙇 
ご指摘のとおり、購読という言葉はややぎこちない唐突な印象があるかと思います。一方で [React のドキュメント](https://ja.reactjs.org/docs/hooks-effect.html) などでも subscription は購読という語で訳されており、許容範囲かなと思う部分もあります。

購読という単語にこだわる必要はないと思いますが、意味的には「イベントのリッスンを行わないようにする」というニュアンスと思われるので、「イベントを解除する」よりは、「イベントの購読 / サブスクリプション / リッスン を解除する」などとするか、「購読 (subscription)」と原文の英単語も併記するなどとしたほうがいいかなと思います（「イベントを解除する」のみだと、"イベントの発生を待ち受ける（リッスンする）のをやめる"というニュアンスが若干薄れてしまうかなと思います）。

2020-07-24 12:29 UTC, okakyo commented on docs/api-reference/next/router.md
> +もし、そのイベントを呼び出したくないのであれば、`off`メソッドをつかってイベントを解除してください。
分かりました。ありがとうございます！

2020-07-24 12:31 UTC, okakyo commented on docs/api-reference/next/router.md
> +一部の場合 ( 例えば、[Custom Server](/docs/advanced-features/custom-server.md)を使用する場合 ) において、ルーターが実行される前に[popstate](https://developer.mozilla.org/en-US/docs/Web/Events/popstate) を呼び出して、何かさせたい場合があります。
「かも」を表記するとtextlint でエラー扱いになるので、この部分の変更を行ったほうがよろしいでしょうか

2020-07-24 12:37 UTC, okakyo commented on docs/api-reference/next/router.md
> +一部の場合 ( 例えば、[Custom Server](/docs/advanced-features/custom-server.md)を使用する場合 ) において、ルーターが実行される前に[popstate](https://developer.mozilla.org/en-US/docs/Web/Events/popstate) を呼び出して、何かさせたい場合があります。
この「あるかもしれません」の部分を「があります」として修正してもいいのでしょうか

2020-07-24 12:43 UTC, thesugar commented on docs/api-reference/next/router.md
> +一部の場合 ( 例えば、[Custom Server](/docs/advanced-features/custom-server.md)を使用する場合 ) において、ルーターが実行される前に[popstate](https://developer.mozilla.org/en-US/docs/Web/Events/popstate) を呼び出して、何かさせたい場合があります。
こちらの確認不足で大変失礼しました。ご提案いただいた「があります」の訳でも文意は損なわれないので、大変お手数おかけしますが、そのようにご修正いただけますと幸いです 🙏

2020-07-24 13:03 UTC, okakyo commented
ご指摘を受けた部分を中心に修正しました。一部 lint に引っかかった等の理由で指摘通りの修正を行えておりませんが、レビューのほどよろしくお願いします。

2020-07-24 13:31 UTC, thesugar commented
ご対応ありがとうございます！確認します！

2020-07-24 15:59 UTC, thesugar commented
ご対応ありがとうございました！内容確認しました。
手元で改めて textlint を走らせてみたのですが、私の suggestion の文章だとやはり複数 textlint のエラーが出てしまうようで、大変ご迷惑おかけしました 🙇‍♂️ 

修正のご対応いただきありがとうございました！
一部、未修正の typo や細かい脱字等がいくつかありましたので、もし失礼でなければ**私のほうで直接ファイルを修正してしまってもよろしいでしょうか？**

意図/背景としては、
- 修正をお願いしたい箇所は、すでに指摘させていただいた typo などのうち、修正が未反映である部分（→これは、私の suggestion が textlint に沿っていなかったため、修正のときにさらに文章を直す必要があったためと思われ、私の責任です。すみません…）であること
- 上記の理由から、再度先ほどと同様の形でコメントしてしまうと、先ほどと同じ内容の指摘を、数としては先ほどと同等の数コメントしてしまうことになるため、ご確認いただくのに不要な負担をおかけすることになる

というもので、それ以外の意図はありません。
繰り返しになりますが、直接修正しようと思っている内容は、先ほど↑でコメントさせていただいたものとほぼ同内容で、新規の指摘事項等はありません。

以上、ご確認のほどよろしくお願いします！

2020-07-24 16:12 UTC, okakyo commented
問題ないです。よろしくお願いします！

2020-07-25 16:02 UTC, thesugar commented
ありがとうございます！

遅くなってしましたが、私のほうでファイルの修正終了しました。
textlint にひっかかる部分は、上記のレビューコメントと少し異なる形で修正している（主に、てにをは等）部分もありますが基本的には上記の私からの suggestion とおりの修正としております。

念のため一度さらっとご確認いただいて、問題なさそうでしたら私からのレビューは完了とさせていただきたいと思います！

2020-07-26 04:47 UTC, okakyo commented
ご対応ありがとうございました！

修正部分を一通り確認してみましたが、特に問題ないと思います！

2020-07-26 05:14 UTC, thesugar commented
ご確認ありがとうございます！ 😄 
では私からは LGTM とさせていただきます！
（続いては 2 人目のレビュアーの方からのレビュー、という流れになります）

2020-07-26 10:36 UTC, hiro08gh commented
翻訳していただきありがとうございます！僕からもLGTMです！

2020-07-26 10:36 UTC, hiro08gh approved these changes

2020-07-26 16:33 UTC, thesugar approved these changes

2020-07-26 16:34 UTC, thesugar commented
@all-contributors please add @okakyo for translation

2020-07-26 16:34 UTC, merged