Docs/upgrading
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #117
Opened 2020-07-24 10:55 UTC by tomotaco

`docs/upgrading.md` を翻訳しましたので、レビューよろしくお願いします。

2020-07-26 03:58 UTC, hiro08gh reviewed
長文を翻訳していただきありがとうございました！いくつかレビューをコメントをさせていただきました。ご確認よろしくお願いします。

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +// あるいは
```suggestion
// または
```

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +カスタム `.babelrc` から `@zeit/next-typescript/babel` への参照があれば削除して下さい。
```suggestion
カスタム `.babelrc` から `@zeit/next-typescript/babel` への参照があれば削除して下さい。（存在する場合）
```

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +カスタム `.babelrc` から `@zeit/next-typescript/babel` への参照があれば削除して下さい。
(if present)の翻訳も追加していただければ嬉しいです。

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +// あるいは
コードブロックの`or`は、`または`で統一していただきたいです。

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +この挙動に依存するコードの更新は、比較的素直です。
```suggestion
この挙動に依存するコードの更新は、比較的簡単です！
```

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +この挙動に依存するコードの更新は、比較的素直です。
`relatively straightforward!`の翻訳は、`比較的簡単です！`の方が自然だと思いました。

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +  // あるいは
```suggestion
  // または
```

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +この移行を手動で行う、あるいは codemod が生成する内容を見るためには、以下を見て下さい:
```suggestion
この移行を手動で行う、あるいは codemod が生成する内容を見るためには、以下をご覧下さい:
```

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +Next.js はページレベルの設定という概念を持つようになり、整合性を保つため `withAmp` 高位コンポーネントは削除されました。
```suggestion
Next.js はページレベルの設定という概念を持つようになり、整合性を保つため `withAmp` 高階コンポーネントは削除されました。
```

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +Next.js はページレベルの設定という概念を持つようになり、整合性を保つため `withAmp` 高位コンポーネントは削除されました。
`higher-order component`は、React日本語リファレンスでは、`高階コンポーネント `と翻訳されているため、用語に一貫性を持たせるために合わせていただけたら嬉しいです。
https://ja.reactjs.org/docs/higher-order-components.html

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +この移行を手動で行う、あるいは codemod が生成する内容を見るためには、以下を見て下さい:
ここは、読者に語りかけるように`ご覧下さい`にしていただけたら嬉しいです。

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +動的ルーティングのために、 `now.json` ファイル内に `routes` を設定していた場合、Next.js 9 の新しい[動的なルーティング機能](https://nextjs.org/docs/routing/dynamic-routes) を利用することで、これらのルールを削除できます。
```suggestion
動的なルーティングのために、 `now.json` ファイル内に `routes` を設定していた場合、Next.js 9 の新しい[動的なルーティング機能](https://nextjs.org/docs/routing/dynamic-routes) を利用することで、これらのルールを削除できます。
```

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +動的ルーティングのために、 `now.json` ファイル内に `routes` を設定していた場合、Next.js 9 の新しい[動的なルーティング機能](https://nextjs.org/docs/routing/dynamic-routes) を利用することで、これらのルールを削除できます。
用語に一貫性をもたらすために、`dynamic routes`は`動的なルーティング`にしていただきたいです。

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +`pages/_app.js` から `getInitialProps` の削除(できれば)は、新しい Next.js の機能を利用するために重要です！
```suggestion
`pages/_app.js` から `getInitialProps` の削除(可能であれば)は、新しい Next.js の機能を利用するために重要です！
```

2020-07-26 03:58 UTC, hiro08gh commented on docs/upgrading.md
> +`pages/_app.js` から `getInitialProps` の削除(できれば)は、新しい Next.js の機能を利用するために重要です！
`When possible`は、`可能であれば`の方が伝わりやすいと感じました。

2020-07-26 05:06 UTC, tomotaco commented on docs/upgrading.md
> +カスタム `.babelrc` から `@zeit/next-typescript/babel` への参照があれば削除して下さい。
「(if present)」は「～への参照があれば」の所に含めて訳したつもりでしたが、わかりにくくてすみません。
「（存在する場合）」と明示的に訳す方針に賛成します。その上で、それなら「～への参照を削除して下さい」にした方がいいのかなと思いましたが、いかがでしょうか。
ご意見頂けると嬉しいです。

2020-07-26 05:11 UTC, tomotaco commented
チェックありがとうございました。ご指摘はいずれもごもっともでしたので、ご提案を取り込みさせていただきました。
1か所(if present の所)はご相談したい内容をコメントさせて頂きましたので、よろしくお願いします。

2020-07-26 06:51 UTC, hiro08gh commented on docs/upgrading.md
> +カスタム `.babelrc` から `@zeit/next-typescript/babel` への参照があれば削除して下さい。
確認していただきありがとうございます！できるだけ()内の翻訳は、原文重視にしていただきたいので、`～への参照を削除して下さい`に変更していただければ嬉しいです！

2020-07-26 07:56 UTC, tomotaco commented on docs/upgrading.md
> +カスタム `.babelrc` から `@zeit/next-typescript/babel` への参照があれば削除して下さい。
承知いたしました。修正させていただきます。

2020-07-26 08:03 UTC, tomotaco commented on docs/upgrading.md
> +カスタム `.babelrc` から `@zeit/next-typescript/babel` への参照があれば削除して下さい。
https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/117/commits/ed369eea3737726daf20ea9e0950e414b8635a9c にて修正いたしましたので、ご確認よろしくお願いします。

2020-07-26 09:53 UTC, hiro08gh commented
修正していただきありがとうございます！僕からはLGTMです！

2020-07-26 10:37 UTC, hiro08gh submitted a review, later dismissed

2020-07-27 01:53 UTC, yokinist requested changes
@tomotaco 
ありがとうございます！
細かい箇所ですが、数点追加でコメントさせていただきました！
ご確認お願いします 🙇

2020-07-27 01:53 UTC, yokinist commented on docs/upgrading.md
> +カスタム `.babelrc` から `@zeit/next-typescript/babel` への参照を削除して下さい。（存在する場合）
```suggestion
カスタム `.babelrc` から `@zeit/next-typescript/babel` への参照を削除して下さい（存在する場合）。
```
とても細かい点で恐縮ですが、`()` は句読点前にあわせていただきたいです＞＜

2020-07-27 01:53 UTC, yokinist commented on docs/upgrading.md
> +#### `next/dynamic` はデフォルトではもはやロード時に　"loading..." を表示しません
```suggestion
#### もはや `next/dynamic` はデフォルトでロード時に "loading..." を表示しません
```
`ではもはや` あたりが読みづらい印象があったため、「もはや〜」という訳の方がいいかなと思いましたがいかがでしょうか？

2020-07-27 01:53 UTC, yokinist commented on docs/upgrading.md
> +アプリケーション移行の助けになるよう、移行前/移行後の例を提供しました:
```suggestion
この挙動に依存するコードの更新は、比較的簡単です！アプリケーション移行の助けになるよう、移行前/移行後の例を提供しました:
```
原文に合わせ改行せず同じ段落にまとめたほうが良さそうです！

2020-07-27 19:18 UTC, tomotaco commented
コメントありがとうございました。ご提案を取り込みさせて頂きました。

2020-07-27 19:24 UTC, yokinist approved these changes
ありがとうございます！LGTM です 🙌

2020-07-28 02:51 UTC, hiro08gh commented
修正していただきありがとうございました！LGTMです！

2020-07-28 02:51 UTC, hiro08gh approved these changes

2020-07-28 02:55 UTC, merged

2020-07-28 03:06 UTC, hiro08gh commented
@all-contributors please add @tomotaco  for translation