docs/api-reference/next.config.js/custom-page-extensions
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #118
Opened 2020-07-24 12:07 UTC by rikusen0335

このページ、Custom Page Extenstionというタイトルですが、カスタムページ拡張機能で問題ないでしょうか？

2020-07-26 01:48 UTC, hoosan requested changes
翻訳ありがとうございます！コメントしましたのでご確認ください🙏
~タイトルも、カスタムページ拡張子（もう少し柔らかくいうと「ページ拡張子のカスタマイズ」）が適切かと思います！
「カスタムページ拡張子」と「ページ拡張子のカスタマイズ」のどちらかk、あるいは他の適切な表現があるかについては
もう一人のレビュアーにも意見聞きたいです。~
→こちら、「独自のページ拡張子」にさせていただきたく、よろしくお願いします🙏

2020-07-26 01:48 UTC, hoosan commented on docs/api-reference/next.config.js/custom-page-extensions.md
> +description: ページディレクトリ内のページを解決する際にNext.jsが使用するデフォルトのページ拡張機能を拡張します。
```suggestion
description: ページディレクトリ内のページを読み込む際にNext.jsが使用する、ページ標準の拡張子をカスタマイズします。
```
ここで言っているのは、pagesディレクトリ内でルート名解決する際に通常使用する拡張子（.jsや.jsx）に加え、例えば(.mdx)[https://github.com/mdx-js/mdx]のような独自の拡張子も使用できるように設定できる・・ということですので、拡張機能というよりは、「使える拡張子を増やす（カスタマイズする）」という意味になります！文章を少し変えましたのでご確認ください🙏

2020-07-26 01:48 UTC, hoosan commented on docs/api-reference/next.config.js/custom-page-extensions.md
> +# カスタムページ拡張機能
```suggestion
# カスタムページ拡張子
```
こちらも拡張機能→拡張子としました！

2020-07-26 01:53 UTC, hoosan requested changes

2020-07-26 01:53 UTC, hoosan commented on docs/api-reference/next.config.js/custom-page-extensions.md
> +    <small>Next.jsが使用する設定ファイルについて学ぶ。</small>
```suggestion
    <small>Next.jsが使用する設定ファイルについてさらに学びましょう。</small>
```
ここは統一のため〜についてさらに学びましょう。という表現にさせて下さい🙏

2020-08-02 07:35 UTC, rikusen0335 commented
おまたせしました！修正コミットプッシュしましたので、レビューお願いいたします。

2020-08-04 00:07 UTC, hoosan approved these changes
反応遅れまして申し訳ありません🙇‍♂️
私からはLGTMです！👍

2020-08-04 00:09 UTC, hiro08gh commented
翻訳していただきありがとうございます！僕からもLGTMです！

2020-08-04 00:09 UTC, hiro08gh approved these changes

2020-08-04 00:11 UTC, merged

2020-08-04 00:13 UTC, hiro08gh commented
@all-contributors please add @rikusen0335  for translation