docs: translate docs/api-reference/next.config.js/disabling-x-powered-by.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #119
Opened 2020-07-24 12:12 UTC by ogugu9

`docs/api-reference/next.config.js/disabling-x-powered-by.md` を翻訳しました。

2020-07-26 01:55 UTC, hoosan approved these changes
翻訳いただきありがとうございます！私からはLGTMです👍

2020-07-26 02:50 UTC, hoosan requested changes
すみません、一点だけ表現の統一のため修正いただけますでしょうか🙏

2020-07-26 02:50 UTC, hoosan commented on docs/api-reference/next.config.js/disabling-x-powered-by.md
> +    <small>Next.js が使用する設定ファイルについてさらに学びましょう。</small>
```suggestion
    <small>Next.js が使用する設定ファイルについて詳しく学びましょう。</small>
```
すみません、こちら統一のため〜について詳しく学びましょうという表現にさせて下さい🙏

2020-07-26 19:56 UTC, ogugu9 commented on docs/api-reference/next.config.js/disabling-x-powered-by.md
> +    <small>Next.js が使用する設定ファイルについてさらに学びましょう。</small>
かしこまりました、ありがとうございます！

2020-07-27 01:58 UTC, yokinist approved these changes
ありがとうございます！LGTMです！！

2020-07-27 12:59 UTC, hiro08gh approved these changes

2020-07-27 13:29 UTC, hoosan approved these changes

2020-07-27 13:34 UTC, merged