Translated "docs/advanced-features/amp-support/api-reference/data-fetching/geiInitialProps"
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #121
Opened 2020-07-24 16:15 UTC by tomohiroyoshida

`docs/advanced-features/amp-support/api-reference/data-fetching/geiInitialProps`<br>
を翻訳いたしました。翻訳どころかOSS自体も初めてで不十分なところもあると思いますが、ご確認よろしくお願いいたします！

2020-07-24 16:21 UTC, tomohiroyoshida commented on docs/api-reference/data-fetching/getInitialProps.md
> +もし TypeScript を使っているならば、関数コンポーネントに `NextPage` 型を使用できます:
you can use the NextPage type for function componentsのtypeを「型」と訳したのですが、これであってるか心配です…:persevere:

2020-07-24 16:22 UTC, tomohiroyoshida commented on docs/api-reference/data-fetching/getInitialProps.md
> +もし TypeScript を使っているならば、関数コンポーネントに `NextPage` 型を使用できます:
`you can use the NextPage type for function componentsのtype`の`type`を「型」と訳したのですが、これであってるか心配です…:persevere:

2020-07-26 02:54 UTC, hoosan requested changes
翻訳いただきありがとうございます！いくつかコメントしましたのでご確認ください🙏

2020-07-26 02:54 UTC, hoosan commented on docs/api-reference/data-fetching/getInitialProps.md
> +`getInitialProps` は、任意のページに静的メソッドとして追加できる[`非同期`](https://vercel.com/blog/async-and-await) 関数です。次の例を見てみましょう:
```suggestion
`getInitialProps` は、任意のページに[`静的メソッド`](https://ja.javascript.info/static-properties-methods)として追加できる[`非同期`](https://vercel.com/blog/async-and-await) 関数です。次の例を見てみましょう:
```
静的メソッドへのリンクを追加しました！（日本語ドキュメントがあるのでそちらにリンクしてます）

2020-07-26 02:54 UTC, hoosan commented on docs/api-reference/data-fetching/getInitialProps.md
> +`getInitialProps` は非同期にデータを取得して `props` を生成するために使われます。
```suggestion
`getInitialProps` は非同期にデータを取得して `props` にデータを与えるために使われます。
```
populatesは「データを入れる」というような意味の他動詞ですので、生成するというよりはpropsにデータを与えるという表現が良いかと思いましたがいかがでしょうか？

2020-07-26 02:54 UTC, hoosan commented on docs/api-reference/data-fetching/getInitialProps.md
> -Data returned from `getInitialProps` is serialized when server rendering, similar to what [`JSON.stringify`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stri
すみません、この部分の訳が抜けているようですので、追加いただけますでしょうか🙏

2020-07-26 02:54 UTC, hoosan commented on docs/api-reference/data-fetching/getInitialProps.md
>  ## Context Object
```suggestion
## Context オブジェクト
```
オブジェクトは日本語でも良いかと思いました！

2020-07-26 02:54 UTC, hoosan commented on docs/api-reference/data-fetching/getInitialProps.md
> +`getInitialProps` は `context` という単一の引数を受け取る、以下のプロパティを持つオブジェクトです。
```suggestion
`getInitialProps` は `context` という単一の引数を受け取る、以下のプロパティを持つオブジェクトです:
```
ここの文末コロンはそのままでお願いします🙏

2020-07-26 02:54 UTC, hoosan commented on docs/api-reference/data-fetching/getInitialProps.md
> +もし TypeScript を使っているならば、関数コンポーネントに `NextPage` 型を使用できます:
TypeScriptの話なので合ってると思います！

2020-07-26 02:54 UTC, hoosan commented on docs/api-reference/data-fetching/getInitialProps.md
> +    <small>Next.js の data fetching について詳しく学ぶ</small>
```suggestion
    <small>Next.js のデータ取得について詳しく学びましょう。</small>
```
ここは表現の統一のために修正させて下さい🙏

2020-07-26 02:54 UTC, hoosan commented on docs/api-reference/data-fetching/getInitialProps.md
>      <b>Data Fetching:</b>
```suggestion
    <b>データ取得:</b>
```

2020-07-26 02:54 UTC, hoosan commented on docs/api-reference/data-fetching/getInitialProps.md
> +    <small>Next.js の pages について詳しく学ぶ</small>
```suggestion
    <small>Next.js の pages について詳しく学びましょう。</small>
```

2020-07-26 02:54 UTC, hoosan commented on docs/api-reference/data-fetching/getInitialProps.md
> +    <small>Next.js の Automatic Static Optimization について詳しく学ぶ</small>
```suggestion
    <small>Next.js の Automatic Static Optimization について詳しく学びましょう。</small>
```

2020-07-26 04:08 UTC, tomohiroyoshida commented on docs/api-reference/data-fetching/getInitialProps.md
> +`getInitialProps` は非同期にデータを取得して `props` を生成するために使われます。
そうですね！「データを入れる」に訂正しておきます！

2020-07-26 04:50 UTC, hoosan commented on docs/api-reference/data-fetching/getInitialProps.md
> +`getInitialProps` は非同期にデータを取得して `props` を生成するために使われます。
私は「追加する」でも良いかと思います！
もう一人のレビュアーの方、ご意見ありましたらお願いします🙏

2020-07-26 05:34 UTC, tomohiroyoshida commented on docs/api-reference/data-fetching/getInitialProps.md
> +description: `getInitialProps` を使い、ページでサーバーサイドレンダリングを有効にして初期データを追加します。
レビューを受けて、`initial data population`の訳を`初期データの追加`に変更しました

2020-07-26 05:36 UTC, tomohiroyoshida commented on docs/api-reference/data-fetching/getInitialProps.md
> +)を可能にし、初期データを追加します。これは特に [SEO](https://ja.wikipedia.org/wiki/%E6%A4%9C%E7%B4%A2%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%B3%E6%9C%80%E9%81%A9%E5%8C%96) 対策に有効です。
同様に`initial data population`の訳を初期データの追加に変更しました

2020-07-26 05:37 UTC, tomohiroyoshida commented on docs/api-reference/data-fetching/getInitialProps.md
> +`getInitialProps` は、任意のページに[`静的メソッド`](https://ja.javascript.info/static-properties-methods)として追加できる[`非同期`](https://vercel.com/blog/async-and-await) 関数です。次の例を見てみましょう:
`静的メソッド`のレファレンスを追加

2020-07-26 05:38 UTC, tomohiroyoshida commented on docs/api-reference/data-fetching/getInitialProps.md
> +`getInitialProps` から返されるデータは、 [`JSON.stringify`](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) が行うのと同じように、サーバーレンダリング時にシリアライズされます。 `getInitialProps` から返
翻訳し忘れた部分の追加

2020-07-26 05:40 UTC, tomohiroyoshida commented on docs/api-reference/data-fetching/getInitialProps.md
> +最初のページのロードでは、 `getInitialProps` はサーバー上でのみ実行されます。
公式ドキュメントに参考に、不要な改行を消しました

2020-07-26 10:41 UTC, hoosan requested changes
修正ありがとうございます！
すみません、descriptionで一点確認したく。こちらローカル環境でエラー出ていませんでしょうか？（あるいは、非表示であるべきdescriptionが表示されていませんでしょうか）
エラー出るようなら`を外すことで回避できるので、文意に問題ないですしそうしていただければと思います。

2020-07-26 10:41 UTC, hoosan commented on docs/api-reference/data-fetching/getInitialProps.md
> +description: `getInitialProps` を使い、ページでサーバーサイドレンダリングを有効にして初期データを追加します。
```suggestion
description: getInitialProps を使い、ページでサーバーサイドレンダリングを有効にして初期データを追加します。
```
この部分、私のローカル環境だと``があるとYAMLExceptionになるのですが、そちらでは出ていませんでしょうか？

2020-07-26 12:04 UTC, tomohiroyoshida commented on docs/api-reference/data-fetching/getInitialProps.md
> +description: `getInitialProps` を使い、ページでサーバーサイドレンダリングを有効にして初期データを追加します。
すみません！エラーは出ていなかったので見過ごしていました<br>
修正しましたので、ご確認よろしくお願いいたします:pray:

2020-07-27 13:59 UTC, hoosan submitted a review, later dismissed
修正いただきありがとうございました！私からはLGTMです👍

2020-07-28 04:33 UTC, Shinyaigeek commented on docs/api-reference/data-fetching/getInitialProps.md
> +`getInitialProps` は非同期にデータを取得して `props` を生成するために使われます。
https://eow.alc.co.jp/search?q=populate

英二郎によると, `populate` には `(データを)投入する` という意味もあるそうなので, @hoosan がおっしゃる通りこの場合生成するというよりはpropsにデータを与えるというニュアンスで「投入する」と訳してもいいかもと思いました.

**個人的には**, 「追加する」より「投入する」の方が, propsというデータ構造に対して実データ(ここの文脈だと初期データ)を流し込む感じがあるかなと思いますが, 個人の感想の範疇だと思うので, 「追加する」でも問題ないとも思います！

2020-07-28 05:03 UTC, Shinyaigeek requested changes
翻訳ありがとうございます！
いくつか指摘, コメントしましたので確認お願いします 🙇

2020-07-28 05:03 UTC, Shinyaigeek commented on docs/api-reference/data-fetching/getInitialProps.md
> +> これらの新しいデータ取得メソッドを使用することで、静的生成とサーバーサイドのレンダリングを細かく選択できるようになります。
```suggestion
> これらの新しいデータ取得メソッドを使用することで、静的生成とサーバーサイドレンダリングを細かく選択できるようになります。
```

かなり細かい指摘で恐縮ですが, ここを `サーバーサイドのレンダリング` と訳しているのには何か意図があってのことでしょうか？
もし特にないのであれば, このページの他の箇所と同様に普通に `サーバーサイドレンダリング` と訳してあげた方が(聴き慣れているため) しっくりくるかなと思いました！

2020-07-28 05:03 UTC, Shinyaigeek commented on docs/api-reference/data-fetching/getInitialProps.md
> +)を可能にし、初期データを追加します。これは特に [SEO](https://ja.wikipedia.org/wiki/%E6%A4%9C%E7%B4%A2%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%B3%E6%9C%80%E9%81%A9%E5%8C%96) 対策に有効です。
```suggestion
  `getInitialProps` は、ページ内の[サーバーサイドレンダリング](/docs/basic-features/pages.md#server-side-rendering
)を可能にし、初期データを追加出来るようになります。つまり、既にデータが追加されているページをサーバーから送信するということです。これは特に [SEO](https://ja.wikipedia.org/wiki/%E6%A4%9C%E7%B4%A2%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%B3%E6%9C%80%E9%81%A9%E5%8C%96) 対策に有効です。
```

* `allows you to do ~ ` の文意が抜けているような気がしたので,  `初期データを追加できるようになる` としました
* `it means ~` も抜けているような気がしたので, suggest出しますがこうした方がいいというのがあれば修正コミットください :pray:

2020-07-28 05:03 UTC, Shinyaigeek commented on docs/api-reference/data-fetching/getInitialProps.md
> -> `getInitialProps` will disable [Automatic Static Optimization](/docs/advanced-features/automatic-static-optimization.md).
すみません. ここの訳が抜けているような気がするので確認お願いします 🙏 

FYI: https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/47#issuecomment-660565750

2020-07-28 05:03 UTC, Shinyaigeek commented on docs/api-reference/data-fetching/getInitialProps.md
> +`getInitialProps` は `context` という単一の引数を受け取る、以下のプロパティを持つオブジェクトです:
```suggestion
`getInitialProps` は `context` という単一の引数を受け取り、この `context` は以下のプロパティを持つオブジェクトです:
```

`it's an object with the following propertiews:` の `it` は 文脈的に `context` を指していますが, `getInitialProps` を指しているような雰囲気を訳から感じたのでいっそのこと `it` を `context` と訳した方がいいと感じましたが如何でしょうか？

代名詞を置き換えるのは無粋な印象も受けるので悩みどころですが...

2020-07-28 05:03 UTC, Shinyaigeek commented on docs/api-reference/data-fetching/getInitialProps.md
> +- `getInitialProps` の中でサーバーサイドのみのモジュールを使用している場合は、[こちらを適切にインポート](https://arunoda.me/blog/ssr-and-server-only-modules)するようにしてください。そうしなければアプリが遅くなってしまうでしょう。
```suggestion
- `getInitialProps` の中でサーバーサイドのみのモジュールを使用している場合は、[それらを適切にインポート](https://arunoda.me/blog/ssr-and-server-only-modules)するようにしてください。そうしなければアプリが遅くなってしまうでしょう。
```

`こちら` だと, その後に続くものを指しているような印象を受けますが, その後に続いているのは「参考記事」という感じの, サーバーサイドでしか使われないモジュールがクライアント向けビルドのコードにもバンドルされて I/O コストが膨れて辛いという感じの記事でモジュールを指しているわけではないので, この場合 `サーバーサイドのみのモジュール` を指しているので, `それら` の方がいいかと思いましたが如何でしょうか？

2020-07-28 06:57 UTC, tomohiroyoshida commented on docs/api-reference/data-fetching/getInitialProps.md
> +`getInitialProps` は `context` という単一の引数を受け取る、以下のプロパティを持つオブジェクトです:
`context`に訂正します:pray:

2020-07-28 06:58 UTC, tomohiroyoshida commented on docs/api-reference/data-fetching/getInitialProps.md
> +> これらの新しいデータ取得メソッドを使用することで、静的生成とサーバーサイドのレンダリングを細かく選択できるようになります。
すみません！`サーバーサイドレンダリング `に訂正します:pray:

2020-07-28 07:01 UTC, tomohiroyoshida commented on docs/api-reference/data-fetching/getInitialProps.md
> +- `getInitialProps` の中でサーバーサイドのみのモジュールを使用している場合は、[こちらを適切にインポート](https://arunoda.me/blog/ssr-and-server-only-modules)するようにしてください。そうしなければアプリが遅くなってしまうでしょう。
確かにそうですね…`それら`に訂正します:bow:

2020-07-28 07:13 UTC, tomohiroyoshida commented on docs/api-reference/data-fetching/getInitialProps.md
> +> [Pages](/docs/basic-features/pages.md) と[データ取得](/docs/basic-features/data-fetching.md)のドキュメントの詳細については、こちらをご覧ください:
ページ内の`Data fetching`の訳を`データ取得`に統一しました

2020-07-30 13:53 UTC, hoosan approved these changes

2020-07-31 13:03 UTC, Shinyaigeek approved these changes
対応ありがとうございます！LGTMです :+1:

2020-07-31 13:04 UTC, Shinyaigeek commented
@all-contributors add @tomohiroyoshida for translation

2020-07-31 13:09 UTC, merged