docs: translate docs/advanced-features/custom-server.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #123
Opened 2020-07-25 02:37 UTC by takefumi-yoshii

https://nextjs.org/docs/advanced-features/custom-server
翻訳しました。よろしくお願いいたします。

2020-07-26 07:17 UTC, yokinist requested changes
翻訳ありがとうございます！
何点か気になった箇所に Suggested change を送らせていただきました！  
ご確認いただき問題なければ取り込んでいただき、別途検討すべきことがあればコメントいただければと思います。よろしくおねがいします🙏

2020-07-26 07:17 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +description: カスタムサーバーを使用してプログラマティックに Next.js アプリを起動します。
```suggestion
description: カスタムサーバーを使用してプログラム上で Next.js アプリを起動します。
```
`プログラマティック` でも意味は通ると思うんですが、あまり聞き慣れないので `プログラム上で` の方がより自然な日本語かなと思いました！

2020-07-26 07:17 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +通常、next サーバーは `next start` で起動します。しかしながら、カスタムルートパターンを使用するために、100％ プログラマティックな起動が可能です。
```suggestion
通常、next サーバーは `next start` で起動します。しかしながら、カスタムしたルーティングパターンを使用するために、100％ プログラム上での起動が可能です。
```
`カスタムルートパターン` が分かりづらい印象があったので、`カスタムしたルーティングパターン` がいいかなと思いました！

2020-07-26 07:17 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +> カスタムサーバーの使用を決定する前に、Next.js の統合ルーターがアプリの要件を満たせない場合にのみ使用することを覚えておいてください。カスタムサーバーは、**サーバーレス関数**や **[Automatic Static Optimization](/docs/advanced-features/automatic-static-optimization.md).** などの重要なパフ
```suggestion
> カスタムサーバーの使用を決定する前に、Next.js の統合ルーターがアプリの要件を満たせない場合にのみ使用すべきことを気に留めてください。カスタムサーバーでは、**サーバーレス関数**や **[Automatic Static Optimization](/docs/advanced-features/automatic-static-optimization.md).** などの重要なパフォーマンス最適化が削除されます。
```
- ニュアンス的には同じものの `覚えてください` よりも `気に留めてください` の方が文脈にしっくり来る気がしました。
- `should` のニュアンスを追加
- カスタムサーバーの説明について受動的な表現が自然なように感じました

2020-07-26 07:17 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +カスタムサーバーは、次のインポートを使用して、サーバーを　Next.js　アプリケーションに接続します:
```suggestion
カスタムサーバーは、次のようにインポートして、サーバーを Next.js アプリケーションに接続します:
```
- 動詞が続き少し冗長な表現に感じたのでこちらはいかがでしょうか？
- スペースを半角にしました

2020-07-26 07:17 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +- `dev`: `Boolean` - Next.js を開発モードで起動するか。デフォルトは `false` です
```suggestion
- `dev`: `Boolean` - Next.js を開発モードで起動するかどうか。デフォルトは `false` です
```
`whether or not to` については「するか」で終わるかは「するかどうか」または「するか否か」のような訳の方が自然で伝わりやすいかなと思いました。

2020-07-26 07:17 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +> `useFileSystemPublicRoutes`は SSR のファイル名ルートのみを無効にすることに注意してください。クライアント側のルーティングは、これらのパスに引き続きアクセスできます。このオプションを使用する場合は、プログラマティックに不要なルートへのナビゲーションを防ぐ必要があります。
```suggestion
> `useFileSystemPublicRoutes`は SSR のファイル名ルートのみを無効にすることに注意してください。クライアント側のルーティングは、これらのパスに引き続きアクセスできます。このオプションを使用する場合は、プログラム上で不要なルートへのナビゲーションを防ぐ必要があります。
```

2020-07-26 07:17 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +デフォルトでは、`Next` はファイル名と一致するパス名の下の `pages` フォルダー内の各ファイルを提供します。プロジェクトでカスタムサーバーを使用する場合、この挙動で同じコンテンツが複数のパスから提供される可能性があり、SEO と UX で問題を起こす可能性があります。
```suggestion
デフォルトでは、`Next` はファイル名と一致するパス名の下の `pages` フォルダー内の各ファイルを提供します。プロジェクトでカスタムサーバーを使用する場合、この挙動で同じコンテンツが複数のパスから提供されることになり、SEO と UX に問題を起こす可能性があります。
```
- `may` 推量的なニュアンスがどちらにもかかっていたので修正してみましたが、いかがでしょうか

2020-07-27 00:19 UTC, takefumi-yoshii commented on docs/advanced-features/custom-server.md
> +description: カスタムサーバーを使用してプログラマティックに Next.js アプリを起動します。
ありがとうございます！ここの表現悩んでいたので、取り込みさせていただきます

2020-07-27 00:22 UTC, takefumi-yoshii commented on docs/advanced-features/custom-server.md
> +- `dev`: `Boolean` - Next.js を開発モードで起動するか。デフォルトは `false` です
ここを「するかどうか」にすると、text-lint で落ちてしまう箇所で、ちょっと悩んでます。。　@yokinist

2020-07-27 00:28 UTC, takefumi-yoshii commented on docs/advanced-features/custom-server.md
> +デフォルトでは、`Next` はファイル名と一致するパス名の下の `pages` フォルダー内の各ファイルを提供します。プロジェクトでカスタムサーバーを使用する場合、この挙動で同じコンテンツが複数のパスから提供される可能性があり、SEO と UX で問題を起こす可能性があります。
カスタムサーバー側で提供するコードがない限り「複数のパスから提供」していることにはならないため、
「複数のパスから提供されることになり」という表現ではないと思いました。

2020-07-27 00:58 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +- `dev`: `Boolean` - Next.js を開発モードで起動するか。デフォルトは `false` です
なるほど、そうだったんですね...。ここは「するかどうか」という訳の方が分かりやすくいいなと思っているので、lintをパスする方法を検討したいです。

1. 部分的にtextlintをdisableする
2. textlintの設定を変更する

が考えられると思いますが「するかどうか」という表現は他箇所でも出てきそうなので、設定を変えてしまってもいい気がしていますがどうでしょう。参考までに僕以外のレビュアーの方にも意見を伺いたいです

---
FYI:

`.textlintrc` の `preset-ja-technical-writing` 内で以下を追加することでパスはできそうです
```yml
"no-doubled-joshi": {
  "strict": false,
  "allow": ["か"], // 助詞のうち「か」は複数回の出現を許す(e.g. するかどうか)
}
```

2020-07-27 01:05 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +デフォルトでは、`Next` はファイル名と一致するパス名の下の `pages` フォルダー内の各ファイルを提供します。プロジェクトでカスタムサーバーを使用する場合、この挙動で同じコンテンツが複数のパスから提供される可能性があり、SEO と UX で問題を起こす可能性があります。
> カスタムサーバー側で提供するコードがない限り「複数のパスから提供」していることにはならない

自分もその理解だったのですが、 `If your project uses a custom server` はそのケースに当たるかなと思っていましたがいかがでしょうか？(※ 設定しない限り、Next.jsデフォルトのルーティング + カスタムサーバーのルーティングの複数パスが存在してしまうという理解をしていました)

2020-07-27 02:15 UTC, takefumi-yoshii commented on docs/advanced-features/custom-server.md
> +デフォルトでは、`Next` はファイル名と一致するパス名の下の `pages` フォルダー内の各ファイルを提供します。プロジェクトでカスタムサーバーを使用する場合、この挙動で同じコンテンツが複数のパスから提供される可能性があり、SEO と UX で問題を起こす可能性があります。
Express.js を利用したカスタムサーバーの本家サンプルコードを引用します。
https://github.com/vercel/next.js/blob/canary/examples/custom-server-express/server.js

```server.js
const express = require('express')
const next = require('next')

const port = parseInt(process.env.PORT, 10) || 3000
const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

app.prepare().then(() => {
  const server = express()

  server.get('/a', (req, res) => {
    return app.render(req, res, '/a', req.query)
  })

  server.get('/b', (req, res) => {
    return app.render(req, res, '/b', req.query)
//  return app.render(req, res, '/a', req.query) とした場合、`pages/a` 相当がレンダリングされる
  })

  server.all('*', (req, res) => {
    return handle(req, res)
  })

  server.listen(port, (err) => {
    if (err) throw err
    console.log(`> Ready on http://localhost:${port}`)
  })
})
```

この様に、カスタムサーバー側でルーティングが増えるほど、
「複数のパスから提供」することが可能になってしまう、という注意書きかと。

逆に、pages による自動ルーティングと重複しないルーティングが
きちんと施されていれば、その懸案事項は払拭されるものだと思います。

以上のことから「提供されることになる」という表現は「may」としてふさわしくなく、
「提供される可能性がある」としています。

2020-07-27 03:08 UTC, hiro08gh commented on docs/advanced-features/custom-server.md
> +- `dev`: `Boolean` - Next.js を開発モードで起動するか。デフォルトは `false` です
助詞の「か」が複数回出るケースは少ないと思うので、例外としてtextlintの設定を変えてしまっていいと思います。

2020-07-27 04:12 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +- `dev`: `Boolean` - Next.js を開発モードで起動するか。デフォルトは `false` です
確認ありがとうございます！
では、翻訳用のブランチ & PRなので別途 textlint の変更PRつくっちゃいますね！

2020-07-27 04:28 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +デフォルトでは、`Next` はファイル名と一致するパス名の下の `pages` フォルダー内の各ファイルを提供します。プロジェクトでカスタムサーバーを使用する場合、この挙動で同じコンテンツが複数のパスから提供される可能性があり、SEO と UX で問題を起こす可能性があります。
例も添えていただきありがとうございます！
改めて自分のなかで整理してみたんですが結果としてはおっしゃる通り推量的なニュアンスを含めた方がいいと思いました(理由は後述)。ただ、以下2点はあらかじめ確認/検討しておきたいです。

1. 「可能性がある」が続いてしまっていること
可能性があるが続いてしまっているのが日本語として気になりました。ここはネガティブな推量の表現として「恐れがある」にしてみるのはいかがでしょうか？

2. ここでの懸念(複数パスから同じコンテンツが描画される)の原因として想定していること

ちょっと認識があってるか分からないので皆さんにもコメントいただきたい箇所なんですが、自分なりの理解を以下記させていただきます。

ここで懸念しているのは、「カスタムサーバーでルーティングが複数記述されうる」ことではなく「何もしてなければ Next.js デフォルトのルーティング(`pages` 内のファイルに基づくルーティング)とカスタムサーバーのルーティングが併用されてしまう」ことを想定していると捉えていました。

いただいた例でいうと以下のケースです
```js
// 省略
app.prepare().then(() => {
  const server = express()

  // この場合 /b でも /c でも pages/b のコンテンツが描画されてしまうこと
  server.get('/c', (req, res) => {
    return app.render(req, res, '/b', req.query)
  })

  server.all('*', (req, res) => {
    return handle(req, res)
  })

  server.listen(port, (err) => {
    if (err) throw err
    console.log(`> Ready on http://localhost:${port}`)
  })
})
```

その理由としては、次の段落との文脈との整合性(`pages` 内のファイルに基づくルーティングとの関連の有無)がとれるからです。

後述すると書いていた推量的なニュアンスを含む理由ですが、ファイルに基づくルーティングと同様のルーティング(サンプルの記述例など)をカスタムサーバーで設定して場合のおいては複数パスから同一ページを返すことはなくなり結果として懸念しているSEO/UX面での問題なくなるからです。その意味で推量的なニュアンスを含むのが適切かなと思いました。

2020-07-27 04:33 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +この動作を無効にし、　`pages`　内のファイルに基づくルーティングを防ぐには、 `next.config.js` を開いて `useFileSystemPublicRoutes` 設定を無効にします:
```suggestion
この動作を無効にし、 `pages` 内のファイルに基づくルーティングを防ぐには、 `next.config.js` を開いて `useFileSystemPublicRoutes` 設定を無効にします:
```
引用して気付いた点ですがこちらも半角スペースでお願いします 🙇

2020-07-27 04:47 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +- `dev`: `Boolean` - Next.js を開発モードで起動するか。デフォルトは `false` です
#140 で送りました！

2020-07-27 06:37 UTC, takefumi-yoshii commented on docs/advanced-features/custom-server.md
> +デフォルトでは、`Next` はファイル名と一致するパス名の下の `pages` フォルダー内の各ファイルを提供します。プロジェクトでカスタムサーバーを使用する場合、この挙動で同じコンテンツが複数のパスから提供される可能性があり、SEO と UX で問題を起こす可能性があります。
異論ないです！suggestion も変更されていましたので、取り込ませていただきます 🙏

2020-07-27 06:38 UTC, takefumi-yoshii commented on docs/advanced-features/custom-server.md
> +この動作を無効にし、　`pages`　内のファイルに基づくルーティングを防ぐには、 `next.config.js` を開いて `useFileSystemPublicRoutes` 設定を無効にします:
ありがとうございます！

2020-07-27 07:02 UTC, yokinist commented on docs/advanced-features/custom-server.md
> +- `dev`: `Boolean` - Next.js を開発モードで起動するか。デフォルトは `false` です
https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/140#pullrequestreview-455506647
こちらについては同意いただけている & 該当のPRがマージされたので取り込んじゃいます！

2020-07-27 07:05 UTC, yokinist approved these changes
翻訳とコメントの確認ありがとうございました！！
僕からはLGTMです👍

2020-07-27 13:01 UTC, hiro08gh commented
翻訳していただきありがとうございました！LGTMです！

2020-07-27 13:01 UTC, hiro08gh approved these changes

2020-07-27 13:03 UTC, merged