Translated the docs/api-reference/next.config.js/exportPathMap.md.
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #124
Opened 2020-07-25 03:35 UTC by kuroppe1819

`docs/api-reference/next.config.js/exportPathMap.md`を翻訳しました。

2020-07-26 13:08 UTC, kuroppe1819 commented on docs/api-reference/next.config.js/exportPathMap.md
> +    <small>Next.js で使う設定ファイルについてより詳しく学ぶ。</small>
共通で使われている文言に修正します。
```suggestion
    <small>Next.js で使用する設定ファイルについて詳しく学びましょう。</small>
```

2020-07-28 13:09 UTC, hiro08gh reviewed
翻訳していただきありがとうございました！いくつかレビューコメントを残したので、確認していただければ嬉しいです！

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +description: next export を使うとき、HTMLファイルとしてエクスポートされるページのカスタマイズをする。
```suggestion
description: next export を使うとき、HTMLファイルとしてエクスポートされるページのカスタマイズをします。
```

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +> この機能は `next export` を含みません。もし `next export` についてより詳細に学びたい場合は[静的HTMLのエクスポート](/docs/advanced-features/static-html-export.md)を参照してください。
```suggestion
> この機能は `next export` を含みません。もし `next export` について詳しく学びたい場合は[静的HTMLのエクスポート](/docs/advanced-features/static-html-export.md)を参照してください。
```

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +> この機能は `next export` を含みません。もし `next export` についてより詳細に学びたい場合は[静的HTMLのエクスポート](/docs/advanced-features/static-html-export.md)を参照してください。
`Learn more about`は、`について詳しく学び~`で統一してもらえたら嬉しいです。

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +`exportPathMap` は 2 つの引数を受け取ります: `async` 関数(非同期関数)です。第 1 引数は `defaultPathMap` で、これは Next.js で使うデフォルトマップです。第 2 引数はオブジェクトです:
```suggestion
`exportPathMap` は 2 つの引数を受け取る `async` 関数です:
```

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +- `dev` - 開発中に `exportPathMap` が呼ばれているとき `true` になります。`next export` 実行中のとき `false` になります。開発時 `exportPathMap` は経路の定義に利用されます。
```suggestion
- `dev` - 開発中に `exportPathMap` が呼ばれているとき `true` になります。`next export` 実行中のとき `false` になります。開発時 `exportPathMap` はルートの定義に利用されます。
```

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +`exportPathMap` は 2 つの引数を受け取ります: `async` 関数(非同期関数)です。第 1 引数は `defaultPathMap` で、これは Next.js で使うデフォルトマップです。第 2 引数はオブジェクトです:
ここは原文に忠実で、`exportPathMap` は 2 つの引数を受け取る `async` 関数です:の方が自然だと思いました！

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +description: next export を使うとき、HTMLファイルとしてエクスポートされるページのカスタマイズをする。
こちらは敬体で合わせていただけたら嬉しいです。

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +- `dir` - プロジェクトディレクトリへの絶対パス。
```suggestion
- `dir` - プロジェクトディレクトリへの絶対パス
```

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +- `buildId` - ビルド ID を生成します。
```suggestion
- `buildId` - ビルド ID を生成します
```

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +- `distDir` - `.next/` ディレクトリへの絶対パス ([`distDir`](/docs/api-reference/next.config.js/setting-a-custom-build-directory.md)設定で設定可能)。
```suggestion
- `distDir` - `.next/` ディレクトリへの絶対パス ([`distDir`](/docs/api-reference/next.config.js/setting-a-custom-build-directory.md)設定で設定可能)
```

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +- `dir` - プロジェクトディレクトリへの絶対パス。
句読点を原文に合わせていただけたら嬉しいです！

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +- `page`: `String` - `pages` ディレクトリ内のページを描画します。
```suggestion
- `page`: `String` - `pages` ディレクトリ内のページを描画します
```

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +- `page`: `String` - `pages` ディレクトリ内のページを描画します。
こちらも上記と同様です！句読点を合わせていただきたいです。

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +- `page`: `String` - `pages` ディレクトリ内のページを描画します。
```suggestion
- `page`: `String` - `pages` ディレクトリ内のページを描画します
```

2020-07-28 13:09 UTC, hiro08gh commented on docs/api-reference/next.config.js/exportPathMap.md
> +- `dev` - 開発中に `exportPathMap` が呼ばれているとき `true` になります。`next export` 実行中のとき `false` になります。開発時 `exportPathMap` は経路の定義に利用されます。
`routes`の翻訳が、`ルート`になっているので合わせていただけたら嬉しいです！

2020-08-01 15:11 UTC, kuroppe1819 commented
添削ありがとうございます。指摘された箇所を修正しました。

2020-08-02 10:43 UTC, hiro08gh commented
素晴らしい翻訳ありがとうございました！僕からはLGTMです！

2020-08-02 11:44 UTC, Shinyaigeek requested changes
翻訳ありがとうございます :pray:

いくつか指摘, コメント残しておいたので確認お願いします 🙇

2020-08-02 11:44 UTC, Shinyaigeek commented on docs/api-reference/next.config.js/exportPathMap.md
> +> この機能は `next export` を含みません。もし `next export` について詳しく学びたい場合は[静的HTMLのエクスポート](/docs/advanced-features/static-html-export.md)を参照してください。
```suggestion
> この機能は `next export` に固有のものです。もし `next export` について詳しく学びたい場合は[静的HTMLのエクスポート](/docs/advanced-features/static-html-export.md)を参照してください。
```

この機能は `exportPathMap` を指しており,  `exportPathMap` は `next export` の時のみ使われるくらいのもの(=通常の `build` 時は `getStaticPath` 等が走る, `getStaticPath` が無い時はbuild時はSSRになる) であるとして寧ろ `固有のもの` くらいのものではと思いましたが, どうでしょうか？

2020-08-02 11:44 UTC, Shinyaigeek commented on docs/api-reference/next.config.js/exportPathMap.md
> +以下のページで、アプリのカスタム `exportPathMap` を作る例から始めましょう:
```suggestion
以下のページを伴うアプリのために、 カスタム`exportPathMap` を作る例から始めましょう:
```

原文中の `with the following pages` は下にまとめられているページ群のリストを指していて `an app` にかかって `以下のページ構造(=ディレクトリ構造)を伴うアプリケーション` となるかなと思いましたが, `以下のページで、` だと `an app` にかかってる感が少なく, 寧ろこのドキュメントの以下のデモを指しているかのような印象を受けたので `以下のページを伴う` と訳しましたがいかがでしょうか？

2020-08-02 11:44 UTC, Shinyaigeek commented on docs/api-reference/next.config.js/exportPathMap.md
> +ページが HTML ファイルとしてエクスポートされたとき、例えば、 `/about` は `/about.html` になります。
```suggestion
ページは HTML ファイルとしてエクスポートされ、例えば、 `/about` は `/about.html` になります。
```

めちゃくちゃ細かい指摘で恐縮ですが, 条件 `時` のニュアンスはないような気がします

2020-08-02 11:44 UTC, Shinyaigeek commented on docs/api-reference/next.config.js/exportPathMap.md
> +`exportPathMap` は 2 つの引数を受け取る `async` 関数(非同期関数)です: 第 1 引数は `defaultPathMap` で、これは Next.js で使うデフォルトマップです。第 2 引数はオブジェクトです:
```suggestion
`exportPathMap` は 2 つの引数を受け取る `async` 関数(非同期関数)です: 第 1 引数は `defaultPathMap` で、これは Next.js で使うデフォルトマップです。第 2 引数は以下のプロパティを持つオブジェクトです:
```

* with が消えてしまっている
* 急にリストが出てきてびっくりする

という理由で, `object` に対して `以下のプロパティを持つ` (=with) を補った方がわかりやすいと感じました

2020-08-02 11:44 UTC, Shinyaigeek commented on docs/api-reference/next.config.js/exportPathMap.md
> +返されたオブジェクトは、 `key` が `pathname` で `value` が以下のフィールドを受け入れるオブジェクトのページのマップです:
```suggestion
返り値となるオブジェクトは、 `key` が `pathname` で `value` が以下のフィールドを受け入れるオブジェクトのページのマップです:
```

`return` の主語は文脈的に 非同期関数と言及されている `exportPathMap` なのですが, `returned` をそのまま受動態的に `返された` としてあげてもいいですが, それだと主語が不明瞭になり何によって返されたかがわからないなと感じたので `返り値となる` として今説明している `exportPathMap` の返り値となるオブジェクトの説明であると示すのが親切かと思いました.

**個人的** には 「`exportPathMap` の返り値となる」 くらいまで補ってあげてもいいかもしれないというお気持ちでいます.

2020-08-02 11:44 UTC, Shinyaigeek commented on docs/api-reference/next.config.js/exportPathMap.md
> +- `page`: `String` - `pages` ディレクトリ内のページを描画します
```suggestion
- `page`: `String` - 描画する `pages` ディレクトリ内のページ
```

ここはpages dir内のどのページをレンダリングするかという話なので, `描画する` を `the page` を修飾する感じかと思います

2020-08-04 15:51 UTC, kuroppe1819 commented on docs/api-reference/next.config.js/exportPathMap.md
> +以下のページで、アプリのカスタム `exportPathMap` を作る例から始めましょう:
```suggestion
以下のページを含むアプリのために、カスタム `exportPathMap` を作る例から始めましょう:
```
はどうですか？

2020-08-04 15:54 UTC, kuroppe1819 commented on docs/api-reference/next.config.js/exportPathMap.md
> +以下のページで、アプリのカスタム `exportPathMap` を作る例から始めましょう:
```suggestion
以下のページを含むアプリのカスタム `exportPathMap` を作る例から始めましょう:
```
はどうですか？

2020-08-04 15:57 UTC, Shinyaigeek commented on docs/api-reference/next.config.js/exportPathMap.md
> +以下のページで、アプリのカスタム `exportPathMap` を作る例から始めましょう:
@kuroppe1819 ミスで吹っ飛ばしてしまってどうしようか調べてました。。 :pray:

それでいいと思います！ありがとうございます！！

2020-08-04 16:10 UTC, kuroppe1819 commented on docs/api-reference/next.config.js/exportPathMap.md
> +> この機能は `next export` を含みません。もし `next export` について詳しく学びたい場合は[静的HTMLのエクスポート](/docs/advanced-features/static-html-export.md)を参照してください。
Static HTML Export を読むと

> you can define a parameter called exportPathMap in your next.config.js file to configure exactly which pages will be generated.

と書いてあったので除外するというより固有のものという訳が正しそうです。ご指摘ありがとうございます！

2020-08-05 00:13 UTC, hiro08gh approved these changes

2020-08-05 07:49 UTC, Shinyaigeek approved these changes
対応ありがとうございます！LGTMです 👍

2020-08-05 07:51 UTC, merged