translate docs/faq.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #131
Opened 2020-07-25 09:53 UTC by adoringonion

docs/faq.mdを翻訳しました。確認お願いします。

2020-07-27 00:34 UTC, yokinist requested changes
@adoringonion 
翻訳ありがとうございます！ 

- example 等のリンクを `zeit` -> `vercel` に変更
- 他、気になった点をコメント & Suggested change

させていただきました。
ご確認いただき、問題なければ取り込んでいただき、別途検討すべきことがあればコメントにて教えていただければと思います。よろしくおねがいします！

2020-07-27 00:34 UTC, yokinist commented on docs/faq.md
> +  <p>Next.js は <a href="https://new.babeljs.io/docs/en/next/babel-preset-env.html">@babel/preset-env</a> を利用することで IE11 を含む現行の全てのブラウザに対応しています。また IE11 に対応するため、 Next.js は Promise polyfill をグローバルインストールして
```suggestion
  <p>Next.js は <a href="https://new.babeljs.io/docs/en/next/babel-preset-env.html">@babel/preset-env</a> を利用することで IE11 とすべてのモダンブラウザに対応しています。また IE11 に対応するため、 Next.js は Promise polyfill をグローバルインストールしています。</p>
```
`IE11 and all modern browsers` とあるのですべてのブラウザではなく、 IE11(レガシーブラウザ) + モダンブラウザに対応している訳が適切かなと思いました

2020-07-27 00:34 UTC, yokinist commented on docs/faq.md
> +  <p>目的のブラウザが対応していない機能を必要とするコードや外部 npm パッケージを使用する場合は、 polyfills を実装する必要があります。 polyfills を実装する必要がある場合、 <a href="https://github.com/zeit/next.js/tree/canary/examples/with-polyfills">polyfills</a> のサンプル
```suggestion
  <p>目的のブラウザが対応していない機能を必要とするコードや外部 npm パッケージを使用する場合は、 Polyfill を実装する必要があります。 Polyfill を実装する必要がある場合、 <a href="https://github.com/vercel/next.js/tree/canary/examples/with-polyfills">Polyfill</a> のサンプルで推奨されている方法を見ることができます。</p>
```
日本語で用いられる場合は、用語としては「Polyfill」が一般的かなと思いました
https://developer.mozilla.org/ja/docs/Glossary/Polyfill

2020-07-27 00:34 UTC, yokinist commented on docs/faq.md
> +  <p>Next.js は webpack 設定のオーバーヘッドを無くすように最善を尽くしてきました。 もし独自で設定する必要がある場合は、こちらの <a href="/docs/api-reference/next.config.js/custom-webpack-config.md">webpack 設定のカスタマイズのドキュメント</a>を見てください。</p>
```suggestion
  <p>Next.js は webpack 設定のオーバーヘッドを無くすように最善を尽くしています。 しかし、独自で設定する必要がある場合は、こちらの <a href="/docs/api-reference/next.config.js/custom-webpack-config.md">webpack 設定のカスタマイズのドキュメント</a>を見てください。</p>
```
過去形の表現となっていたので今も最善を尽くしてるというニュアンスが伝わるようにしてみました

2020-07-27 00:34 UTC, yokinist commented on docs/faq.md
> +    <li>ルートは事前に知られておく必要はなく、ルートマニフェストを送りません</li>
```suggestion
    <li>ルーティングは事前に知られておく必要はなく、ルートマニフェストを送りません</li>
```
`Routes` は違和感なければ「ルーティング」と訳してしまったほうが自然かなと思いました

2020-07-27 00:34 UTC, yokinist commented on docs/faq.md
> +    <li>ルートは常に遅延読み込みが可能です</li>
```suggestion
    <li>ルーティングは常に遅延読み込みが可能です</li>
```

2020-07-27 00:34 UTC, yokinist commented on docs/faq.md
> +  <p>使えます！ <a href="https://github.com/zeit/next.js/tree/canary/examples/with-apollo">example with Apollo</a> を見てください。</p>
```suggestion
  <p>使えます！ <a href="https://github.com/vercel/next.js/tree/canary/examples/with-apollo">example with Apollo</a> を見てください。</p>
```

2020-07-27 00:34 UTC, yokinist commented on docs/faq.md
> +  <p>使えます！ <a href="https://github.com/zeit/next.js/tree/canary/examples/with-redux">example</a> を見てください。 <a href="https://github.com/zeit/next.js/tree/canary/examples/with-redux-thunk">example with
```suggestion
  <p>使えます！ <a href="https://github.com/zeit/next.js/tree/canary/examples/with-redux">example</a> を見てください。 <a href="https://github.com/vercel/next.js/tree/canary/examples/with-redux-thunk">example with thunk</a> もあります。</p>
```

2020-07-27 00:34 UTC, yokinist commented on docs/faq.md
> +  <p>最初のリリース以来、多くの他ライブラリやツールとの併用例がコントリビュートされてきました。 <a href="https://github.com/zeit/next.js/tree/canary/examples">examples</a> ディレクトリで見ることができます。</p>
```suggestion
  <p>最初のリリース以来、多くの他ライブラリやツールとの併用例がコントリビュートされてきました。 <a href="https://github.com/vercel/next.js/tree/canary/examples">examples</a> ディレクトリで見ることができます。</p>
```

2020-07-27 00:34 UTC, yokinist commented on docs/faq.md
> +  <p>手間がかからない React のサーバーサイドレンダリングの選択肢を調査していた時、 Next.js と同じ手法を取っている <a href="https://github.com/facebookarchive/react-page">react-page</a> （現在は非推奨）に出会いました。これは React の製作者である Jordan Walke によるものです。</p>
```suggestion
  <p>手間がかからない React のサーバーサイドレンダリングの選択肢を調査していた時、 Next.js と似た手法を取っている <a href="https://github.com/facebookarchive/react-page">react-page</a> （現在は非推奨）に出会いました。これは React の製作者である Jordan Walke によるものです。</p>
```
`similar` なので「同じ」よりも「似た」という表現にとどめておく方が適切かなと思いました

2020-08-11 07:39 UTC, yokinist commented
@adoringonion 
翻訳者の意図を汲み取った訳を心掛けていきたいので、上記の変更提案についてお時間あるときにご確認お願いします🙇‍♂️
（もし数日経ってもご返信いただけなかった場合はこのまま取り込んでしまうので、予めご了承ください）

2020-08-11 17:05 UTC, adoringonion commented
返信が大変遅くなって申し訳ございません。明日、指摘していただいた箇所を修正して再度PRを出させていただきます

2020-08-12 16:38 UTC, adoringonion commented
遅くなって申し訳ございません。指摘していただいた点を修正しました。確認お願いします

2020-08-12 17:18 UTC, yokinist submitted a review, later dismissed
ご確認ありがとうございました！LGTMです👍

2020-08-15 10:44 UTC, yokinist commented
@all-contributors please add @adoringonion  for translation

2020-08-22 09:24 UTC, yokinist commented
for reviewers:
こちら2人目レビューされないとマージできないので、どなたかお時間あるときに最終確認お願いします！

2020-08-30 08:31 UTC, thesugar requested changes
翻訳ありがとうございました！
2 人目のレビューがかなり遅くなってしまって本当に申し訳ありません。
細かい部分にはなりますが、何点かコメントさせていただきましたのでご確認ください。

2020-08-30 08:31 UTC, thesugar commented on docs/faq.md
>  description: Get to know more about Next.js with the frequently asked questions.
```suggestion
description: よくある質問を通して Next.js について理解を深めましょう。
```

description 部分の訳を追加しました。

2020-08-30 08:31 UTC, thesugar commented on docs/faq.md
> +  <p>クライアントサイドのバンドルサイズはアプリごとに計測されるべきですが、 Next のメインバンドルは gzip 形式で約 65kb に圧縮されています。</p>
```suggestion
  <p>クライアントサイドのバンドルサイズはアプリごとに計測されるべきですが、軽量の Next.js アプリであればメインバンドルは gzip 形式で約 65kb に圧縮されています。</p>
```

small という部分の訳が抜けていたので追加しました！

2020-08-30 08:31 UTC, thesugar commented on docs/faq.md
> +  <p>Next.js は webpack 設定のオーバーヘッドを無くすように最善を尽くしています。 しかし、独自で設定する必要がある場合は、こちらの <a href="/docs/api-reference/next.config.js/custom-webpack-config.md">webpack 設定のカスタマイズのドキュメント</a>を見てください。</p>
```suggestion
  <p>Next.js は webpack 設定のオーバーヘッドを無くすように最善を尽くしています。 しかし、より多くの制御を必要とするような高度なケースでは、こちらの <a href="/docs/api-reference/next.config.js/custom-webpack-config.md">webpack 設定のカスタマイズのドキュメント</a>を見てください。</p>
```

正しい訳だとは思うのですが、より原文に忠実になるように修正してみました。

2020-08-30 08:31 UTC, thesugar commented on docs/faq.md
> +  <p>好きな方法を選ぶことができます。 React コンポーネント内でリモートデータを取得するには、 <a href="https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch">fetch API</a> か <a href="https://swr.now.sh/">SWR</a> のどちらかを使うことが
```suggestion
  <p>好きな方法を選ぶことができます。 React コンポーネント内でリモートデータを取得するには、 <a href="https://developer.mozilla.org/ja/docs/Web/API/Fetch_API/Using_Fetch">fetch API</a> か <a href="https://swr.now.sh/">SWR</a> のどちらかを使うことができます。 もしくは Next.js 独自の<a href="/docs/basic-features/data-fetching.md">データ取得メソッド</a>を使って初期データを追加できます。</p>
```

- mozilla のドキュメントは日本語verがあったのでそちらに URL を修正しました。
- initial data population の訳は [こちら](https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/121/#discussion_r460481230) と平仄を取り、「初期データの追加」としました。

2020-08-30 08:31 UTC, thesugar commented on docs/faq.md
> +  <p>使えます！ <a href="https://github.com/vercel/next.js/tree/canary/examples/with-apollo">example with Apollo</a> を見てください。</p>
```suggestion
  <p>使えます！ <a href="https://github.com/vercel/next.js/tree/canary/examples/with-apollo">Apollo を使ったサンプル</a> を見てください。</p>
```

example with Apollo の部分を日本語にしました。

2020-08-30 08:31 UTC, thesugar commented on docs/faq.md
> +  <p>使えます！ <a href="https://github.com/vercel/next.js/tree/canary/examples/with-redux">example</a> を見てください。 <a href="https://github.com/vercel/next.js/tree/canary/examples/with-redux-thunk">example w
```suggestion
  <p>使えます！ こちらの<a href="https://github.com/vercel/next.js/tree/canary/examples/with-redux">サンプル</a> を見てください。 <a href="https://github.com/vercel/next.js/tree/canary/examples/with-redux-thunk">thunk を用いたサンプル</a> もあります。</p>
```

example と example with thunk の部分を日本語にしました。

2020-08-30 08:31 UTC, thesugar commented on docs/faq.md
> +  <p>PHP とは違って ES6 モジュールシステムの恩恵を受けることができ、ページ毎にコンポーネントや関数がエクスポートされることで遅延評価やテストを簡単に導入することができます。</p>
```suggestion
  <p>PHP とは違って ES6 モジュールシステムの恩恵を受けることができ、ページ毎にコンポーネントや関数がエクスポートされており、遅延評価やテストのためにそれらを簡単にインポートできます。</p>
```

原文そのものの意味は「各ページからコンポーネントや関数がエクスポートされているから、遅延評価やテストにおいてそれら（コンポーネントや関数）を簡単にインポートできる」で、「遅延評価やテストを簡単に導入できる」という意味とは少し異なるかなと思いましたので、その部分を修正しました。

2020-09-02 03:55 UTC, adoringonion commented
返信遅くなってすみません。レビューありがとうございます。確認させていただきます

2020-09-02 04:16 UTC, adoringonion commented
返信遅くなってすみません。修正ありがとうございます！

2020-09-13 13:57 UTC, hiro08gh submitted a review, later dismissed

2020-09-13 14:37 UTC, thesugar commented
@adoringonion さん
すみません、こちらどうでしょう？
私のコメントした部分の変更まだ取り込まれていないように見受けられたので、、。
ご確認いただけると幸いです！ 🙇

2020-09-13 14:50 UTC, adoringonion commented
本当にすみません、僕自身が操作しなければいけないことに気づいていませんでした。大変遅くなりましたが取り込ませていただきました

2020-09-14 11:21 UTC, yokinist approved these changes
ご確認ご対応いただきありがとうございました！再度ですがLGTMです！！

2020-09-14 15:37 UTC, thesugar commented
@adoringonion 
とんでもないです！私のほうこそ諸々遅れてしまってすみませんでした。
翻訳ありがとうございました！LGTM です！

2020-09-14 15:37 UTC, thesugar approved these changes

2020-09-14 15:38 UTC, merged