docs: translate docs/advanced-features/measuring-performance.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #133
Opened 2020-07-26 03:18 UTC by kakukakug

`docs/advanced-features/measuring-performance.md` について翻訳を行いました。
ご確認をお願いします。

2020-07-27 14:25 UTC, hoosan requested changes
翻訳いただきありがとうございます！細かい点ですがコメントしましたのでご確認下さい🙏

2020-07-27 14:25 UTC, hoosan commented on docs/advanced-features/measuring-performance.md
>  export function reportWebVitals(metric) {
お手数ですが、こちらのコードブロック内のコメントも翻訳をお願いできますでしょうか🙏

2020-07-27 14:25 UTC, hoosan commented on docs/advanced-features/measuring-performance.md
>  export function reportWebVitals(metric) {
こちらのコードブロック内のコメントも翻訳いただけますと嬉しいです🙏

2020-07-27 14:25 UTC, hoosan commented on docs/advanced-features/measuring-performance.md
>  ## Custom metrics
```suggestion
## カスタム指標
```
本文でカスタム指標と訳していただいているので、ここも統一するのはいかがでしょうか？

2020-07-27 14:27 UTC, hoosan commented on docs/advanced-features/measuring-performance.md
>  export function reportWebVitals(metric) {
わかりにくくてすみません🙏
66行目から86行目と、111行目から124行目までのコードブロック内のコメントに関する件です！

2020-07-27 14:46 UTC, kakukakug commented on docs/advanced-features/measuring-performance.md
>  ## Custom metrics
対応しました！

2020-07-27 14:46 UTC, kakukakug commented on docs/advanced-features/measuring-performance.md
>  export function reportWebVitals(metric) {
コードブロック内のコメントで漏れていた部分も対応しました！

2020-07-28 08:54 UTC, hoosan requested changes

2020-07-28 08:54 UTC, hoosan commented on docs/advanced-features/measuring-performance.md
>  - Custom metrics
```suggestion
- カスタム指標
```
すみません、見落としていましたがこちらも統一した方が良いかと思いました🙏

2020-07-28 11:44 UTC, kakukakug commented on docs/advanced-features/measuring-performance.md
>  - Custom metrics
ありがとうございます！対応しました。

2020-07-28 12:52 UTC, hoosan submitted a review, later dismissed
修正ありがとうございます！私からはLGTMです👍

2020-07-28 13:21 UTC, yokinist requested changes
翻訳ありがとうございます！

- リンクを日本語版へ
- 文末の表記を原文に揃える
- 1点、訳し方で気になったところ

をコメント&提案させていただきました。
再度、ご確認いただけると嬉しいです。
よろしくおねがいします！

2020-07-28 13:21 UTC, yokinist commented on docs/advanced-features/measuring-performance.md
>  - [First Contentful Paint](https://developer.mozilla.org/en-US/docs/Glossary/First_contentful_paint) (FCP)
```suggestion
- [First Contentful Paint](https://developer.mozilla.org/ja/docs/Glossary/First_contentful_paint) (FCP)
```
日本語版のページがあるのでリンクはこちらでお願いします 🙏

2020-07-28 13:21 UTC, yokinist commented on docs/advanced-features/measuring-performance.md
>  - [Time to First Byte](https://developer.mozilla.org/en-US/docs/Glossary/Time_to_first_byte) (TTFB)
```suggestion
- [Time to First Byte](https://developer.mozilla.org/ja/docs/Glossary/Time_to_first_byte) (TTFB)
```
日本語版のページがあったのでリンクはこちらでお願いします 🙏 
※ まだ訳されてはいませんが、訳される可能性があるため

2020-07-28 13:21 UTC, yokinist commented on docs/advanced-features/measuring-performance.md
> +これらの指標はすべて `web-vital` ラベルを使用して処理できます。
```suggestion
これらの指標はすべて `web-vital` ラベルを使用して処理できます:
```
文末の表記ですが、原文と揃えていただきたいです＞＜

2020-07-28 13:21 UTC, yokinist commented on docs/advanced-features/measuring-performance.md
> +    console.log(metric); // metricオブジェクト({ id, name, startTime, value, label }) がコンソールに出力されます。
```suggestion
    console.log(metric); // metricオブジェクト({ id, name, startTime, value, label }) がコンソールに出力されます
```
こちらも、文末の表記を原文と揃えていただきたいです

2020-07-28 13:21 UTC, yokinist commented on docs/advanced-features/measuring-performance.md
> +    console.log(metric); // metricオブジェクト({ id, name, startTime, value, label }) がコンソールに出力されます。
```suggestion
    console.log(metric); // metricオブジェクト({ id, name, startTime, value, label }) がコンソールに出力されます
```
こちらも、文末の表記を原文と揃えていただきたいです

2020-07-28 13:21 UTC, yokinist commented on docs/advanced-features/measuring-performance.md
> +これらの指標は、[User Timing API](https://caniuse.com/#feat=user-timing) をサポートするすべてのブラウザで機能します。
```suggestion
これらの指標は、[User Timing API](https://caniuse.com/#feat=user-timing) をサポートしているすべてのブラウザで機能します。
```
細かい表現ですが、「サポートしている」の方が自然かなと思いました

2020-07-28 13:21 UTC, yokinist commented on docs/advanced-features/measuring-performance.md
> +リレー機能を使用して、サイトのユーザーパフォーマンスを測定および追跡するためのエンドポイントに、任意の結果を送信できます:
```suggestion
リレー機能を用いて任意の結果をアナリティクスのエンドポイントに送信すると、測定および追跡することができます:
```
measure and track は endpoint の修飾ではなく send any of results to an analytics endpoint の結果として捉えたほうが自然な気がしましたがいかがでしょうか？

2020-07-28 13:21 UTC, yokinist commented on docs/advanced-features/measuring-performance.md
> +> `id` を使用して、手動でメトリックス分布を構築できます(割合の計算など)
```suggestion
> `id` を使用して、手動でメトリックス分布を構築できます(割合の計算など)。
```
こちらも、文末の表記を原文に揃えていただきたいです

2020-07-28 13:21 UTC, yokinist commented on docs/advanced-features/measuring-performance.md
> +>     nonInteraction: true // 直帰率のデータへの影響を回避する
```suggestion
>     nonInteraction: true // 直帰率のデータへの影響を回避する。
```
こちらも、文末の表記を原文と揃えていただきたいです

2020-07-29 14:08 UTC, kakukakug commented
> 翻訳ありがとうございます！
> 
> * リンクを日本語版へ
> * 文末の表記を原文に揃える
> * 1点、訳し方で気になったところ
> 
> をコメント&提案させていただきました。
> 再度、ご確認いただけると嬉しいです。
> よろしくおねがいします！

@yokinist 
上記内容について対応を行いました。再レビューをお願いします！

2020-07-29 15:04 UTC, yokinist approved these changes
ご確認いただきありがとうございました 🙏 
LGTMです！！

2020-07-30 14:10 UTC, hoosan approved these changes

2020-07-30 14:16 UTC, merged