docs: translate docs/advanced-features/preview-mode.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #134
Opened 2020-07-26 05:03 UTC by YouheiNozaki

docs/advanced-features/preview-mode.mdの翻訳をしました。
遅くなってしまい、申し訳ありません。レビューよろしくお願いします。

本家のdocsが更新されていたので、最新版のdocsを翻訳しました。

2020-07-28 11:10 UTC, hoosan requested changes
翻訳していただきありがとうございます！かなり大変だったかと思います！
長文ですので、他よりもたくさんコメントしております🙇‍♂️
また、全体として以下の点をご確認いただけますと幸いです：

- commit suggestionは使用せず、ローカルでまとめて修正していただけますでしょうか🙏
- forkしてからかなり経っているようですので、一度最新の状態に更新してください🙏（textlintの設定等がかなり変わっています🙇‍♂️）
- textlint:fixで[スタイルガイド](https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/blob/master/styleguide.md)に記載の半角スペースを入れる修正をしていただけますでしょうか🙏

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +解説: Next.jsは静的に生成されたページのためのプレビューモードがあります。ここではその使い方について学びます。
```suggestion
description: Next.jsは静的に生成されたページのためのプレビューモードがあります。ここではその使い方について学びます。
```
ここはdescriptionのままでお願いします🙏

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +    <li><a href="https://github.com/vercel/next.js/tree/canary/examples/cms-graphcms">GraphCMS Example</a> (<a href="https://next-blog-graphcms.now.sh/">デモ</a>)</li>
```suggestion
    <li><a href="https://github.com/vercel/next.js/tree/canary/examples/cms-graphcms">GraphCMS の例</a> (<a href="https://next-blog-graphcms.now.sh/">デモ</a>)</li>
```
例に統一していただけますでしょうか🙏

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +[ページドキュメント](/docs/basic-features/pages.md)と[データ取得ドキュメント](/docs/basic-features/data-fetching.md)で、 `getStaticProps` と `getStaticPaths`を使って、ビルド時にページを事前レンダリングをする(**静的生成**)について説明しました。
```suggestion
[ページのドキュメント](/docs/basic-features/pages.md)と[データ取得のドキュメント](/docs/basic-features/data-fetching.md)で、 `getStaticProps` と `getStaticPaths`を使って、ビルド時にページを事前レンダリングをする(**静的生成**)について説明しました。
```
ドキュメントの前に「の」が合った方が読みやすいかと思いますがどうでしょう？

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +静的生成はヘッドレスCMSからページにデータを取得するときに役立ちます。しかし、ヘッドレスCMSで下書きをしていて、すぐにページで**プレビュー**をしたいとき理想的ではありません。Next.jsではビルド時ではなく**リクエスト時**にこれらのページをレンダリングし、公開されたコンテンツではなく下書きのコンテンツを取得します。この特定の場合のみ、Next.jsでは静的生成をバイパスする必要があ
```suggestion
静的生成はヘッドレスCMSからページにデータを取得するときに役立ちます。しかし、ヘッドレスCMSで下書きをしていて、すぐにページで**プレビュー**をしたいときには理想的ではありません。Next.js ではビルド時ではなく**リクエスト時**にこれらのページをレンダリングし、公開されたコンテンツではなく下書きのコンテンツを取得します。このような特定のケースにおいて、Next.js に静的生成を行って欲しくない場合があります。
```
"want Next.js to bypass"なので、Next.jsに静的生成をパイパスして欲しい、つまり静的生成を行って欲しくないという表現の方が良いかと思いましたがどうでしょうか？

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +Next.jsはこの問題を解決するための**プレビューモード**と呼ばれる機能があります。ここではその使い方について説明します。
```suggestion
Next.js にはこの問題を解決するための**プレビューモード**と呼ばれる機能があります。ここではその使い方について説明します。
```
細かい表現問題ですが個人的にこちらの方が読みやすいと思うのですがいかがでしょう？

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +> Next.jsのAPIルートに慣れていない場合は、まず最初に [APIルートドキュメント](/docs/api-routes/introduction.md) を参照してください。
```suggestion
> Next.jsのAPIルートに慣れていない場合は、まず最初に [APIルートのドキュメント](/docs/api-routes/introduction.md) をご覧ください。
```
こちらも上と同様です

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +まず**プレビューAPIルート**を作成します。`pages/api/preview.js` (TypeScriptを使用している場合は `.ts` )　などの任意の名前をつけることが出来ます。
```suggestion
まず、**プレビューAPIルート**を作成します。`pages/api/preview.js` (TypeScriptを使用している場合は `.ts` )　などの任意の名前をつけることが出来ます。
```
細かいですが読点を入れた方が読みやすいかと思います

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +このAPIルートでは、レスポンスオブジェクトである `setPreviewData` を呼び出す必要があります。 `setPreviewData` の引数はオブジェクトである必要があり、 `getStatciProps` (これについては後ほど詳しく説明します)によって使用することが出来ます。ここでは　`{}` を使用します。
```suggestion
このAPIルートでは、レスポンスオブジェクトから `setPreviewData` を呼び出す必要があります。 `setPreviewData` の引数はオブジェクトである必要があり、 `getStatciProps` (これについては後ほど詳しく説明します)によって使用することが出来ます。ここでは　`{}` を使用します。
```
`setPreviewData`はレスポンスオブジェクトの中に含まれているメソッドで、
「である」とすると同一であるかのような誤解を生むかと思いましたので表現を変えさせていただきました🙏

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +.　`res.setPreviewData` はプレビューモードを実行するブラウザにいくつかの**Cookie**を設定します。これらのCookieを含むNext.jsへのリクエストは**preview mode**と判断され、静的に生成されたページの動作へと変更されます(これについては後ほど詳しく説明します)。
```suggestion
`res.setPreviewData` はプレビューモードを実行するブラウザにいくつかの **Cookie** を設定します。これらの Cookie を含む Next.js へのリクエストは **プレビューモード** と判断され、静的に生成されたページの動作が変更されます(これについては後ほど詳しく説明します)。
```
"the behavior for statically generated pages will change"は、the behaviorが主語、changeが動詞になります。
「動作へと変更」ではなく「動作が変更」とするのが正しいと思いましたがいかがでしょう？

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +以下のようなAPIルートを作成しブラウザから手動でアクセスすることによって、これを手動でテストすることが出来ます。
```suggestion
以下のような API ルートを作成し、ブラウザから手動でアクセスすることによって、これを手動でテストすることが出来ます:
```
コードブロック前のコロンはそのままでお願いします🙏

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +// ブラウザから手動でテストするための簡単なサンプル
```suggestion
// ブラウザから手動でテストするための簡単なサンプルです。
```
原文に合わせて文章にしていただくのが良いかと思います！

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +// pages/api/preview.jsにこれを配置し、
```suggestion
// もしこのファイルがpages/api/preview.jsに置かれているならば、
```

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +// ブラウザで、 /api/preview を開いてください.
```suggestion
// ブラウザで /api/preview を開いてください。
```

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +実際には、このAPIルートをヘッドレスCMSから _安全に_ 呼び出す必要があります。具体的な手順は使用しているヘッドレスCMSによって異なりますが、ここでは実行できるいくつかの共通の手順を紹介します。
```suggestion
実際には、このAPIルートをヘッドレスCMSから _安全に_ 呼び出す必要があります。具体的な手順は使用しているヘッドレスCMSによって異なりますが、ここではいくつかの共通する手順を紹介します。
```
「実行できる」はなくても良いかと思いましたがいかがでしょうか？

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +**最初に**、選択したトークンジェネレーターを使用して**シークレットトークン文字列**を作成する必要があります。このシークレットトークンはNext.jsアプリとヘッドレスCMSだけが知っています、このシークレットトークンにより、CMSにアクセスできないユーザーはプレビューURLにアクセスすることが出来なくなります。
```suggestion
**最初に**、選択したトークンジェネレーターを使用して**シークレットトークン文字列**を作成する必要があります。このシークレットトークンはNext.jsアプリとヘッドレスCMSだけが知っています。このシークレットトークンにより、CMSにアクセスできないユーザーはプレビューURLにアクセスすることが出来なくなります。
```
細かいですが句点が正しいかと思います

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +**次に**、ヘッドレスCMSがカスタムプレビューURLの設定をサポートしている場合は、プレビューURLとして次のように指定します。(これはプレビューAPIルートが `pages/api/preview.js` にあることを前提としています。)
```suggestion
**次に**、ヘッドレスCMSがカスタムプレビューURLの設定をサポートしている場合は、プレビューURLとして次のように指定します。(これはプレビューAPIルートが `pages/api/preview.js` にあることを想定した場合です。)
```
ここは想定とした方が良いかと思いましたがいかがでしょう？

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +- `<your-site>` デプロイしたドメインである必要があります。
```suggestion
- `<your-site>` はデプロイしたドメインである必要があります。
```
原文が文章ですのでそのように修正しました！

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +- `<token>` 生成したシークレットトークンに置き換える必要があります。
```suggestion
- `<token>` は生成したシークレットトークンに置き換える必要があります。
```

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +- `<path>` プレビューするページのパスである必要があります。 `/posts/foo` でプレビューする場合には `&slug=/posts/foo` を使用してください。
```suggestion
- `<path>` はプレビューするページのパスである必要があります。 `/posts/foo` でプレビューする場合には `&slug=/posts/foo` を使用してください。
```

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +ヘッドレスCMSは　`<path>` に `&slug=/posts/{entry.fields.slug}` のようにCMSのデータに基づいて動的に設定することによって、プレビューURLに変数を含めることが出来ます。
```suggestion
ヘッドレス CMS がプレビュー URL に変数を含めることが出来る場合がありますが、これにより `&slug=/posts/{entry.fields.slug}` のように、CMS のデータに基づいて動的に `<path>` を設定することができるようになります。
```
"so that A can〜" は、「〜することによって」ではなく、「Aが〜できるように」と訳すのが一般的かと思いました！

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +  // 提供された `slug` が存在しているかどうか確認し、ヘッドレスCMSをフェッチします。
```suggestion
  // 提供された `slug` が存在しているかどうか確認するため、ヘッドレスCMSをフェッチします。
```
ここのto checkは確認するため、とするのが良いかと思います！

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +  // slugが存在しない場合、プレビューモードを有効にすることは出来ません。
```suggestion
  // slugが存在しない場合、プレビューモードを有効にしないようにしましょう。
```
できませんというより、res.status(401)を返すように実装しましょうという意味ですので、このように変えてみましたがいかがでしょう？

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +## ステップ2 `getStaticProps` に更新
```suggestion
## ステップ2 `getStaticProps` を更新
```
updateの目的語がgetStaticPropsなので「を」とするのが正しいかと思います！

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +次のステップはプレビューモードを `getStaticProps` をサポートするように更新することです。
```suggestion
次のステップはプレビューモードをサポートするように `getStaticProps` を更新することです。
```

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> + ( `res.setPreviewData` を経由して)プレビューモードのCookieが設定されている `getStaticProps` で生成したページをリクエストすると、 `getStaticProps` が(ビルド時ではなく)**リクエスト時**に呼び出されます。
```suggestion
 ( `res.setPreviewData` を経由して)プレビューモードのCookieが設定されている `getStaticProps` を含むページをリクエストすると、 `getStaticProps` が(ビルド時ではなく)**リクエスト時**に呼び出されます。
```
getStaticPropsで生成した、ではなく getStaticPropsを含むとするのが良いかと思います。
（bypassされてリクエストごとのレンダリングになりますので、生成したページにリクエストすると書くと読み手が混乱するかと思いました。）

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +さらに、次のように `context` オブジェクトが呼び出されます。
```suggestion
さらに、次のような `context` オブジェクトを引数に getStaticProps が呼ばれます:
```
ここのitはgetStaticPropsでありcontextオブジェクトが呼ばれるというのは少し違うのかなと思いましたので、表現を変えてみましたがいかがでしょう？（訳していただいた文章ですと`context`が主語になっていますので、itが主語の方が良いかと思いました）

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +プレビューAPIルートで `res.setPreviewData({})` を使用したため、 `context.previewData` は `{}` になります。 プレビューAPIルートから `getStaticProps` にセッション情報を渡し、必要に応じてこれを使用することが出来ます。
```suggestion
プレビューAPIルートで `res.setPreviewData({})` を使用したため、 `context.previewData` は `{}` になります。 これを用いて、プレビューAPIルートから `getStaticProps` に、必要であればセッション情報を渡すことが出来ます。
```
ここのthisはres.setPreviewData({})を指していますので、このように修正いたしました！

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +`context.preview` 及び/または `context.previewData` に基づいて異なるデータを取得するように `getStaticProps` を更新することが出来ます。
```suggestion
`context.preview` や `context.previewData` に基づいて異なるデータを取得するように `getStaticProps` を更新することが出来ます。
```
and/orは「や」とすると柔らかく表現できるかと思いますがいかがでしょう？

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +それでおしまいです。ヘッドレスCMSからまたは手動で、( `secret` と `slug` を使用して)プレビューAPIルートにアクセスすると、プレビューコンテンツを表示することが出来ます。また公開せずに下書きを更新すると、下書きをプレビューすることが出来るようになります。
```suggestion
以上です！ヘッドレスCMSから、または手動で、( `secret` と `slug` を使用して)プレビューAPIルートにアクセスすると、プレビューコンテンツを表示することが出来ます。また、公開せずに下書きを更新すると、下書きをプレビューすることが出来るはずです。
```
少し表現を柔らかくしましたがどうでしょうか？

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +# そしてプレビューを見ることが出来るようになります。
```suggestion
# プレビューを見ることが出来るようになります。
```

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +# これをヘッドレスCMSのプレビューURLとして設定するか、手動でアクセスします。
```suggestion
# これをヘッドレスCMSのプレビューURLとして設定するか、手動でアクセスすることで、
```

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +# そしてプレビューを見ることが出来るようになります。
文章をまとめてみましたがいかがでしょうか？

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +  // プレビューモードのCookieを削除する
```suggestion
  // プレビューモードのCookieを削除します。
```

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +`setPreviewData` はオプションオブジェクトであるオプションの2番目のパラメーターを受け取ります。次のキーを受け取ります。
```suggestion
`setPreviewData` はオプションで2番目のパラメーターを指定することができ、これが設定に関するオブジェクトになります。次のキーを受け取ります:
```
オブションが続きますので、少し言い換えましたがいかがでしょう？

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +  // プレビューモードのCookieを削除する
ここは原文に合わせて文章にしていただいた方が良いかと思いました！

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +`setPreviewData` をオブジェクトに渡して、 `getStaticProps` で利用可能にすることが出来ます。しかし、データはCookieに保存されるため、サイズに制限があります。現在、プレビューデータは2KBに制限されています。
```suggestion
オブジェクトを  `setPreviewData` に渡して、 `getStaticProps` で利用可能にすることが出来ます。しかし、データはCookieに保存されるため、サイズに制限があります。現在、プレビューデータは2KBに制限されています。
```
"You can pass an object to `setPreviewData` " ですので、
`setPreviewData` をオブジェクトに渡すのではなくオブジェクトを`setPreviewData` に渡すのが正しいかと思います！

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +### `getServerSideProps` の動作。
```suggestion
### `getServerSideProps` の動作
```
句点を除きました！

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +### `next build` ごとにユニーク
```suggestion
### `next build` ごとに単一
```
ユニークを単一とした方が読みやすいかと思いましたがいかがでしょう？

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +This ensures that the bypass cookie can’t be guessed. `next build` を実行するたびに、バイパスCookieの値と暗号化された `previewData` の秘密鍵が変更されます。これにより、バイパスCookieを推測出来ないようにします。
```suggestion
`next build` を実行するたびに、バイパスCookieの値と暗号化された `previewData` の秘密鍵が変更されます。これにより、バイパスCookieを推測出来ないようにします。
```

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +This ensures that the bypass cookie can’t be guessed. `next build` を実行するたびに、バイパスCookieの値と暗号化された `previewData` の秘密鍵が変更されます。これにより、バイパスCookieを推測出来ないようにします。
英文が入り込んでましたので削除しました！

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +    <small>Next.jsのデータ取得について学ぶ。</small>
```suggestion
    <small>Next.jsのデータ取得について詳しく学びましょう。</small>
```
統一のためこのような表現にさせてください🙏

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +    <small>Next.jsのAPIルートについて学ぶ。</small>
```suggestion
    <small>Next.jsのAPIルートについて詳しく学びましょう。</small>
```

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +    <small>Next.jsの環境変数について学ぶ。</small>
```suggestion
    <small>Next.jsの環境変数について詳しく学びましょう。</small>
```

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +// pages/api/preview.jsにこれを配置し、
ここは一例ですので、もし〜の表現とするのが良いかと思いました！

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +**最後に**、プレビューAPIルートで:
```suggestion
**最後に**、プレビューAPIルートで以下の処理を行います:
```
日本語にすると尻切れとんぼな印象なので、少し文章を足しましたがいかがでしょうか？

2020-07-28 11:10 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +  // getPostBySlugは必要なフェッチロジックをヘッドレスCMSに実装します。
```suggestion
  // getPostBySlugはヘッドレスCMSへの必要なフェッチロジックを実装します。
```
to the headless CMSは「への」とするのが正しいかと思います！

2020-07-28 14:23 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +[ページドキュメント](/docs/basic-features/pages.md)と[データ取得ドキュメント](/docs/basic-features/data-fetching.md)で、 `getStaticProps` と `getStaticPaths`を使って、ビルド時にページを事前レンダリングをする(**静的生成**)について説明しました。
To reviewers: "xx documentation" は頻出ですが、「〇〇に関するドキュメント」への統一の方が良いでしょうか？

2020-07-28 14:54 UTC, yokinist commented on docs/advanced-features/preview-mode.md
> +[ページドキュメント](/docs/basic-features/pages.md)と[データ取得ドキュメント](/docs/basic-features/data-fetching.md)で、 `getStaticProps` と `getStaticPaths`を使って、ビルド時にページを事前レンダリングをする(**静的生成**)について説明しました。
関係/関連といったニュアンスは含まれていないので、シンプルに「◯◯のドキュメント」でいいと思います！

2020-07-28 16:16 UTC, yokinist commented on docs/advanced-features/preview-mode.md
> +[ページドキュメント](/docs/basic-features/pages.md)と[データ取得ドキュメント](/docs/basic-features/data-fetching.md)で、 `getStaticProps` と `getStaticPaths`を使って、ビルド時にページを事前レンダリングをする(**静的生成**)について説明しました。
#144 で documentation の訳についてスタイルガイドに反映させる PR 送ったので、改めてそちらで確認していただければと思います 🙏

2020-07-29 01:19 UTC, YouheiNozaki commented on docs/advanced-features/preview-mode.md
> +ヘッドレスCMSは　`<path>` に `&slug=/posts/{entry.fields.slug}` のようにCMSのデータに基づいて動的に設定することによって、プレビューURLに変数を含めることが出来ます。
こちら指摘の通りに訂正すると、このようなエラーが出てしまいました。
`84:37  error  一文に二回以上利用されている助詞 "が" がみつかりました。  ja-technical-writing/no-doubled-joshi`

そこで、このように訳してみたのですが、いかがでしょうか？

ヘッドレス CMS はプレビュー URL に変数を含めることも出来るので、これにより `&slug=/posts/{entry.fields.slug}` のように、CMS のデータに基づいて動的に `<path>` を設定できるようになります。

2020-07-29 01:23 UTC, YouheiNozaki commented on docs/advanced-features/preview-mode.md
> +静的生成はヘッドレスCMSからページにデータを取得するときに役立ちます。しかし、ヘッドレスCMSで下書きをしていて、すぐにページで**プレビュー**をしたいとき理想的ではありません。Next.jsではビルド時ではなく**リクエスト時**にこれらのページをレンダリングし、公開されたコンテンツではなく下書きのコンテンツを取得します。この特定の場合のみ、Next.jsでは静的生成をバイパスする必要があ
こちらの指摘もtextlintで弾かれたしまったので、最後の文を以下のようにしました。


このような特定のケースにおいて、Next.js に**静的生成をして欲しくない場合があります**。

2020-07-29 02:30 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +[ページドキュメント](/docs/basic-features/pages.md)と[データ取得ドキュメント](/docs/basic-features/data-fetching.md)で、 `getStaticProps` と `getStaticPaths`を使って、ビルド時にページを事前レンダリングをする(**静的生成**)について説明しました。
ありがとうございます！了解です🙆‍♂️

2020-07-29 02:30 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +静的生成はヘッドレスCMSからページにデータを取得するときに役立ちます。しかし、ヘッドレスCMSで下書きをしていて、すぐにページで**プレビュー**をしたいとき理想的ではありません。Next.jsではビルド時ではなく**リクエスト時**にこれらのページをレンダリングし、公開されたコンテンツではなく下書きのコンテンツを取得します。この特定の場合のみ、Next.jsでは静的生成をバイパスする必要があ
すみません！直していただいた文でOKです🙆‍♂️

2020-07-29 02:34 UTC, hoosan commented on docs/advanced-features/preview-mode.md
> +ヘッドレスCMSは　`<path>` に `&slug=/posts/{entry.fields.slug}` のようにCMSのデータに基づいて動的に設定することによって、プレビューURLに変数を含めることが出来ます。
お手数おかけします！日本語的に文意を損なっていなければ私のsuggestionをそのまま適用しなくて大丈夫です👌

2020-07-29 05:25 UTC, YouheiNozaki commented
丁寧なレビューありがとうございます！
修正多くて申し訳ありません。ご指摘の箇所を訂正しましたので、レビューよろしくお願いします。

2020-07-30 13:58 UTC, hoosan submitted a review, later dismissed
修正いただきありがとうございます！私からはLGTMです👍

2020-07-30 17:32 UTC, thesugar requested changes
本当に長い文章を翻訳ありがとうございました！  
私からも 3 点ばかりコメントしましたのでご確認ください！

2020-07-30 17:32 UTC, thesugar commented on docs/advanced-features/preview-mode.md
> +[ページのドキュメント](/docs/basic-features/pages.md)と[データ取得のドキュメント](/docs/basic-features/data-fetching.md)で、 `getStaticProps` と `getStaticPaths`を使って、ビルド時にページを事前レンダリングをする**静的生成**について説明しました。
```suggestion
[ページのドキュメント](/docs/basic-features/pages.md)と[データ取得のドキュメント](/docs/basic-features/data-fetching.md)で、`getStaticProps` と `getStaticPaths` を使って、ビルド時にページをプリレンダリングする**静的生成**について説明しました。
```

- 事前レンダリングをする -> プリレンダリングする
    - 事前レンダリングという訳でも完全に正しいのですが、ただ、まさにここで参照している[ページのドキュメント](https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/blob/master/docs/basic-features/pages.md)、[データ取得のドキュメント](https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/blob/master/docs/basic-features/data-fetching.md)のどちらでも「プリレンダリング」と訳されているので、そちらに統一したほうがよいかと思いました！

2020-07-30 17:32 UTC, thesugar commented on docs/advanced-features/preview-mode.md
> +静的生成はヘッドレス CMS からページにデータを取得するときに役立ちます。しかし、ヘッドレス CMS で下書きをしていて、すぐにページで**プレビュー**をしたいときには理想的ではありません。Next.js ではビルド時ではなく**リクエスト時**にこれらのページをレンダリングし、公開されたコンテンツではなく下書きのコンテンツを取得します。このような特定のケースにおいて、Next.js に静的
```suggestion
静的生成はヘッドレス CMS からページにデータを取得するときに役立ちます。しかし、ヘッドレス CMS で下書きをしていて、すぐにページで**プレビュー**をしたいときには理想的ではありません。Next.js がビルド時ではなく**リクエスト時**にこれらのページをレンダリングし、公開されたコンテンツではなく下書きのコンテンツを取得するようにしたいでしょう。このような特定のケースにおいて、Next.js に静的生成をして欲しくない場合があります。
```

"You'd want Next.js to render these pages at request time..." という文章は、前の文の「すぐにページでプレビューをしたいときには（静的生成は）理想的ではありません」という文章を受けて、「（もし、ページでプレビューしたいのなら）You would want Next.js to render...」と言っている文だと思います。ので、そのニュアンスが出るように少し訳を変更してみました。
（変更前の「Next.js ではビルド時ではなく…下書きのコンテンツを取得します」という訳だと You'd want の意味合いが消えて、Next.js のデフォルトの動作がそうであると言っているような印象になってしまうかなと思いました。）

2020-07-30 17:32 UTC, thesugar commented on docs/advanced-features/preview-mode.md
> +- それから、ブラウザを `slug` で指定したパスにリダイレクトします。(次の例では[307リダイレクト](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307)を使用しています)
```suggestion
- それから、ブラウザを `slug` で指定したパスにリダイレクトします。(次の例では[307リダイレクト](https://developer.mozilla.org/ja/docs/Web/HTTP/Status/307)を使用しています)
```

日本語のページがありましたので URL を変更しました！

2020-07-31 06:44 UTC, YouheiNozaki commented
レビューありがとうございます！！
レビューしてくださった通りに取り込みました！！

2020-07-31 14:08 UTC, thesugar approved these changes

2020-07-31 14:08 UTC, thesugar commented
さっそくのご対応ありがとうございました！ 🙇 
LGTM です！

2020-08-01 07:11 UTC, hoosan approved these changes

2020-08-01 07:14 UTC, merged

2020-08-01 07:27 UTC, thesugar commented
@all-contributors add @YouheiNozaki for translation

2020-08-01 07:28 UTC, hiro08gh commented
@all-contributors please add @YouheiNozaki  for translation