docs: translate docs/api-routes/api-middlewares.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #141
Opened 2020-07-27 18:41 UTC by yokinist

`docs/api-routes/api-middlewares.md` 翻訳しました！レビューお願いします🙏

2020-07-28 17:26 UTC, thesugar requested changes
内容的にはもはや非の打ちようがないといった感じでした、、！

いくつか、形式的な部分でコメントを入れてあります。
特に、スペーシングなどはまだプロジェクトを通しても明確にルールが定まっていない部分もあったかと思うのですが、yokinistさんもレビュアーであることに甘えて、この機会に方針を統一させるという意味でも細かい部分をコメントさせていただきました。ご確認ください 🙇

2020-07-28 17:26 UTC, thesugar commented on docs/api-routes/api-middlewares.md
> +API ルートには、送信されてきた (`req`) をパースするための組み込みミドルウェアが提供されています。以下、それらのミドルウェアです:
```suggestion
API ルートは、受け取ったリクエスト (`req`) をパースするための組み込みミドルウェアを提供しています。以下、それらのミドルウェアです:
```
- fix typo: the incoming request (`req`) が「送信されてきた (`req`)」と、「リクエスト」が欠落していたので修正しました。
- 同じ文章が登場する description 部分では「API ルートは〜を提供しています」と訳していただいていますが、この部分もその description 部分の訳と同じ訳にしてしまってもよいかなと思いました！

2020-07-28 17:26 UTC, thesugar commented on docs/api-routes/api-middlewares.md
> +// そして、ミドルウェアでエラーが発生したときエラーを投げる
```suggestion
// 後続の処理を行う前にミドルウェアの実行を待ち、
// また、ミドルウェアでエラーが発生したときエラーを投げるためのヘルパーメソッド
```
↑の suggestion の文章自体は参考程度にしてほしいのですが、以下が気になりました。
- 「ミドルウェアの実行を待ってから続ける」が、何を続けるのかパッと見で若干意味を取りづらい（と言っても、原文も continuing としか書かれていないので原文の問題でもありますが。。）ような気がしたので、「後続の処理を行う」というふうに訳してみるのはどうかなと思いました
- and を「そして」と訳すと「ミドルウェアの実行を待つ」→そして→「エラーが発生したときにエラーを投げる」という順序（あるいは前後関係）的なニュアンスが出るような気がしたため、「また」という同時性が出る訳のほうが自然かなと思いました
- "Helper method to wait 〜 and to throw an error〜." という一文が途中で改行されているものと解釈して、「後続の処理を行う前に〜また、〜エラーを投げるためのヘルパーメソッド」という訳（to throw もヘルパーメソッドにかかる）を提案してみました。

2020-07-28 17:26 UTC, thesugar commented on docs/api-routes/api-middlewares.md
> +> 完成したアプリを見るには、 [API Routes with CORS](https://github.com/zeit/next.js/tree/canary/examples/api-routes-cors) のサンプルを参照してください。
```suggestion
> 完成したアプリを見るには、[CORS を用いた API ルート](https://github.com/vercel/next.js/tree/canary/examples/api-routes-cors)の例を参照してください。
```

- GitHub の URL を zeit -> vercel にしました
- examples の部分（本ファイルの 8 行目〜 11 行目の部分）では example(s) を例と訳しておられ、また、API Routes with CORS は「CORS を用いた API ルート」と訳されているので、ここもそれに合わせました。
- 加えて、不要と思われる部分の半角スペースを削除しました。

2020-07-28 17:26 UTC, thesugar commented on docs/api-routes/api-middlewares.md
> +- `req.query` - [クエリ文字列](https://en.wikipedia.org/wiki/Query_string) が格納されているオブジェクトです。デフォルト値は `{}` です
```suggestion
- `req.query` - [クエリ文字列](https://en.wikipedia.org/wiki/Query_string)が格納されているオブジェクトです。デフォルト値は `{}` です
```
Nits: ここは半角スペース不要かと思いました（認識間違っていましたらすみません！）

2020-07-28 17:26 UTC, thesugar commented on docs/api-routes/api-middlewares.md
> +また、 [Connect](https://github.com/senchalabs/connect) と互換性のあるミドルウェアも利用できます。
```suggestion
また、[Connect](https://github.com/senchalabs/connect) と互換性のあるミドルウェアも利用できます。
```
Nits: 約物（ここでは `、`）と接している場合は半角スペース不要かと思いました（というルールが定まってはいなかったかもしれませんが、例えば 37 行目の「もし、`Stream` として利用したい場合〜」の部分や 75 行目の「まず、`cors` を〜」の部分では `、` と英語の間にスペースが入っていないので、それらとの統一という意も込めて）

参考：例えば  [React のプロジェクト](https://github.com/reactjs/ja.reactjs.org/blob/master/TRANSLATION.md#%E5%85%A8%E8%88%AC%E7%9A%84%E3%81%AA%E3%81%93%E3%81%A8) では約物（特に句読点 。, 、）と直接隣接している場合は英単語と和文の間のスペースは不要、というルールになっているようです。

2020-07-28 17:26 UTC, thesugar commented on docs/api-routes/api-middlewares.md
> +例えば、 [cors](https://www.npmjs.com/package/cors) パッケージを活用することで API エンドポイントに [CORS 設定](https://developer.mozilla.org/ja/docs/Web/HTTP/CORS) をできます。
```suggestion
例えば、[cors](https://www.npmjs.com/package/cors) パッケージを活用することで API エンドポイントに [CORS 設定](https://developer.mozilla.org/ja/docs/Web/HTTP/CORS)をできます。
```
Nits: こちらの二箇所も、半角スペース不要かと思いました。

2020-07-28 17:26 UTC, thesugar commented on docs/api-routes/api-middlewares.md
> +  // ミドルウェアを走らせる
```suggestion
  // ミドルウェアを実行する
```
ここはミドルウェアを実行するのほうが自然かなとも思いました（あまり強いこだわりはありません）。

2020-07-28 17:32 UTC, yokinist commented on docs/api-routes/api-middlewares.md
> +API ルートには、送信されてきた (`req`) をパースするための組み込みミドルウェアが提供されています。以下、それらのミドルウェアです:
ですね、こちらは揃えちゃいましょう！ありがとうございます！

2020-07-28 17:34 UTC, yokinist commented on docs/api-routes/api-middlewares.md
> +// そして、ミドルウェアでエラーが発生したときエラーを投げる
ここはどう訳したらうまく伝わるのか悩んでいた箇所だったので、提案いただいた表現が直感的に理解できるので取り込ませていただきます。ありがとうございます！

2020-07-28 18:13 UTC, yokinist commented on docs/api-routes/api-middlewares.md
> +また、 [Connect](https://github.com/senchalabs/connect) と互換性のあるミドルウェアも利用できます。
正直自分も少し戸惑いがありつつも明確なルールがなかったため(徹底はできていませんでしたが)

> 半角と全角が切り替わる箇所にスペースをいれてください - [styleguide.md](https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/blob/master/styleguide.md#%E5%8D%8A%E8%A7%92%E3%81%A8%E5%85%A8%E8%A7%92%E3%81%AE%E3%82%B9%E3%83%9A%E3%83%BC%E3%82%B9
)

というルールに則って書いてみました！

まだ、全角/半角切り替えスペースの適応の例外については暗黙的なものでスタイルガイドに記載できていなかったので、このPRで認識を揃えて更新できればいいなと思っています。

「約物（特に句読点 。, 、）と直接隣接している場合は英単語と和文の間のスペースは不要」というルールには自分も賛成です！問題なさそうならスタイルガイドも更新いたします！

2020-07-28 18:20 UTC, yokinist commented on docs/api-routes/api-middlewares.md
> +例えば、 [cors](https://www.npmjs.com/package/cors) パッケージを活用することで API エンドポイントに [CORS 設定](https://developer.mozilla.org/ja/docs/Web/HTTP/CORS) をできます。
https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/87#pullrequestreview-452762262 ここで確認しておきたかったことでもあるんですが

今のルールだと、ともに 1 になりますが、以下のケースはどちらが適切か予め確認しておきたいです。こちらも必要に応じて全角/半角切り替えスペースの適応の例外についてスタイルガイドに追記したいと思います。

1.1. `に␣[CORS 設定](https://developer.mozilla.org/ja/docs/Web/HTTP/CORS)␣を`
1.2. `に[CORS 設定](https://developer.mozilla.org/ja/docs/Web/HTTP/CORS)を`

または

2.1. `に␣**CORS**␣を`
2.2. `に**CORS**を`

2020-07-28 18:21 UTC, yokinist commented on docs/api-routes/api-middlewares.md
> +- `req.query` - [クエリ文字列](https://en.wikipedia.org/wiki/Query_string) が格納されているオブジェクトです。デフォルト値は `{}` です
https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/141#discussion_r461781277
こちらと同じ修正なので方針決まり次第、対応します！

2020-07-29 17:05 UTC, thesugar commented on docs/api-routes/api-middlewares.md
> +例えば、 [cors](https://www.npmjs.com/package/cors) パッケージを活用することで API エンドポイントに [CORS 設定](https://developer.mozilla.org/ja/docs/Web/HTTP/CORS) をできます。
ご確認ありがとうございます！

個人的には、
- 2.1. or 2.2. => 英単語（CORS）の前後に半角スペースが空くよう、2.1. のようにするのが適切かなと思います。
- 1.1. or 1.2. => このパターンは若干ややこしいかもしれませんね。。個人的には 1.1. / 1.2. のどちらとも少しだけ違ってしまうのですが、 `に␣[CORS 設定](https://developer.mozilla.org/ja/docs/Web/HTTP/CORS)を` とする（=1.1. にある 2 つの `␣` のうち、後者は取り除いたもの）のが適切ではないかと思いました。  
発想としては、「マークダウンとして見たとき（=編集時点）の半角/全角の切り替わりを基準とするのではなく、HTML になったとき（=ドキュメントとして完成した時点）の半角/全角の切り替わり部分にスペースが空いている状態が適切」ではないかと思っているためです。

一方、ルールの明快さや運用のしやすさなどといった観点も踏まえると、1.1. や 1.2. のほうが better という判断も当然あると思いますので、ご意見ありましたらよろしくお願いします 🙇 

// すみません、わかりづらい文章になってしまったので、意図不明の部分があればお尋ねください。。

2020-07-29 17:09 UTC, thesugar commented on docs/api-routes/api-middlewares.md
> +また、 [Connect](https://github.com/senchalabs/connect) と互換性のあるミドルウェアも利用できます。
ご確認ありがとうございます！
 [#141 (comment)](https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/141#discussion_r462452408) こちらでお返事させていただきました！

2020-07-29 17:23 UTC, yokinist commented on docs/api-routes/api-middlewares.md
> +例えば、 [cors](https://www.npmjs.com/package/cors) パッケージを活用することで API エンドポイントに [CORS 設定](https://developer.mozilla.org/ja/docs/Web/HTTP/CORS) をできます。
> HTML になったとき（=ドキュメントとして完成した時点）の半角/全角の切り替わり部分にスペースが空いている状態

なるほどです、その観点抜けていたので腑に落ちました。変更取り込みます！

2020-07-29 17:28 UTC, yokinist commented
レビューいただいた点について修正いたしました！再度、ご確認お願いします 🙏

2020-07-29 17:46 UTC, thesugar approved these changes

2020-07-29 17:47 UTC, thesugar commented
ご対応ありがとうございました！
私からは LGTM です！

2020-07-30 14:00 UTC, hoosan approved these changes
LGTMです！👍

2020-07-30 15:24 UTC, merged