docs: translate docs/static-optimization-indicator.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #142
Opened 2020-07-28 01:09 UTC by Hiro0206

docs/static-optimization-indicator.mdの翻訳をしました。
遅くなってしまい、申し訳ありません。レビューよろしくお願いします。

2020-07-28 12:50 UTC, yokinist requested changes
翻訳いただきありがとうございます！
原文に即した訳をしていただいており意味合いもおおよそ間違いではないんですが、開発ドキュメントとしてより読みやすい日本語表現といった観点で恐縮ながらコメントさせていただきました！
ご確認よろしくおねがいします 🙇

2020-07-28 12:50 UTC, yokinist commented on docs/api-reference/next.config.js/static-optimization-indicator.md
> +description: 最適化されたページは静的に最適化されているかどうかをあなたに知らせるためのインジケーターを含んでいます。あなたはこのページを見ることで、インジケーターを対象から外すことができるようになります。
```suggestion
description: 最適化されたページには、静的に最適化されているかどうかを知らせるインジケーターが含まれています。オプトアウトの方法を見ていきましょう。
```
- `you` の「あなたは」は日本語訳では読書を想定しており、あえて書かなくてもいいのかなと思いました
- オプトアウトは訳さずそのまま「オプトアウト」の方が自然で伝わると思いました(& 他の箇所もそのままだったので表記統一の観点からも)。

2020-07-28 12:50 UTC, yokinist commented on docs/api-reference/next.config.js/static-optimization-indicator.md
>  # Static Optimization Indicator
`Automatic Static Optimization` を訳さないのであれば、こっちも揃えたほうが自然そうですか上ではインジケータと訳している箇所があり判断に迷うところですね・・もう1人のレビュアーの方にも訳したほうがいいか意見いただきたいです！もし訳すとしたら `docs/manifest.json` も訳す必要があります。

FYI: 訳すとしたら以下になるかなと
- 静的最適化のインジケータ
- 静的最適化インジケータ

2020-07-28 12:50 UTC, yokinist commented on docs/api-reference/next.config.js/static-optimization-indicator.md
> +[Automatic Static Optimization](/docs/advanced-features/automatic-static-optimization.md)をページができるようになった場合、私達はあなたに知らせるインジケーターを表示します。
```suggestion
ページが [Automatic Static Optimization](/docs/advanced-features/automatic-static-optimization.md) の対象となる場合は、インジケーターを表示してお知らせします。
```
意味合いとしては間違っていないんですが、主語をページとすると分かりづらくなってしまうので開発者目線の文体でより読みやすくしてみましたがいかがでしょうか？

2020-07-28 12:50 UTC, yokinist commented on docs/api-reference/next.config.js/static-optimization-indicator.md
> +これは役に立ちます。なぜなら、automatic static optimization はとても有益なものですし、ページがその権利を与えられた場合、開発中でもすぐに知らせてくれるのは便利だからです。
```suggestion
Automatic Static Optimization 自体とても有益なものですし、開発中にページが適格であるかどうかをすぐに知ることができるので、これは役に立ちます。
```
`This is helpful` はあえて最後に結論として、もってきちゃったほうが読みやすいかなと思いました！

2020-07-28 12:50 UTC, yokinist commented on docs/api-reference/next.config.js/static-optimization-indicator.md
> +Electron アプリケーションで動かすといったような場面では、このインジケーターは役に立たない可能性があります。インジケーターを削除するためには、`next.config.js`ファイルを開き、`devIndicators`プロパティの `autoPrerender` 設定を無効にします:
```suggestion
ですが、 Electron アプリケーションで動かすときなど、インジケーターが役立たない場合があります。インジケーターを削除するためには、`next.config.js` ファイルを開き、`devIndicators` プロパティの `autoPrerender` 設定を無効にします:
```
「といったような場面では」と「可能性があります」が続いており少し冗長に感じたので日本語表現を修正してみましたが、いかがでしょうか？また後ろに半角スペースがなかったものがあったので追加しました。

「ですが」といった逆説は原文にはないんですが、ないと唐突な文脈になってしまうのであったほうがより円滑になると思ったのですがどうでしょうか？あくまで提案として残させてください 🙏

2020-08-10 04:47 UTC, Hiro0206 commented on docs/api-reference/next.config.js/static-optimization-indicator.md
> +Electron アプリケーションで動かすといったような場面では、このインジケーターは役に立たない可能性があります。インジケーターを削除するためには、`next.config.js`ファイルを開き、`devIndicators`プロパティの `autoPrerender` 設定を無効にします:
わかりやすく修正していただき、ありがとうございます！
今後の参考にさせていただきます！

2020-08-10 04:49 UTC, Hiro0206 commented on docs/api-reference/next.config.js/static-optimization-indicator.md
>  # Static Optimization Indicator
他のレビュアーの方から特に指摘がなさそうですが、こちらはこのままでもよろしいでしょうか？

2020-08-11 07:27 UTC, yokinist commented on docs/api-reference/next.config.js/static-optimization-indicator.md
>  # Static Optimization Indicator
@Hiro0206 
申し訳ないです、自分で議論広げたままにしてしまっていました🙏
改めてちょっとみてみたんですが

```suggestion
# 静的最適化インジケータ
```

- 自動最適化は文内(Automatic Static Optimizationのページ等)で使われているので単体だったら訳す
- インジケータはこのページ内でも使っているので訳す

とそれぞれを分解すればどちらもも訳す方が自然かなと個人的には思いましたが、いかがでしょうか？ 

レビュアーの方にも意見いただきたいです 👀

2020-08-12 04:42 UTC, hiro08gh commented on docs/api-reference/next.config.js/static-optimization-indicator.md
>  # Static Optimization Indicator
自分も`静的最適化インジケータ`であれば自然だと思いました。なので`Static Optimization Indicator`に関しては、`静的最適化インジケータ`でいいと思います。

2020-08-12 18:19 UTC, yokinist commented on docs/api-reference/next.config.js/static-optimization-indicator.md
>  # Static Optimization Indicator
@Hiro0206

静的最適化インジケータで特に問題なさそうであれば、お手数ですが以下2点ご対応お願いしたいです！

- Commit suggestion を取り込んでいただく
- `docs/manifest.json` も合わせて変更する

2020-08-15 04:55 UTC, Hiro0206 commented on docs/api-reference/next.config.js/static-optimization-indicator.md
>  # Static Optimization Indicator
こちら上記2点の対応をしましたので、ご確認お願いします！

2020-08-15 10:43 UTC, yokinist submitted a review, later dismissed
翻訳/ご確認ありがとうございました！！LGTMです👍

2020-08-15 10:43 UTC, yokinist commented
@all-contributors please add @Hiro0206 for translation

2020-08-22 09:24 UTC, yokinist commented
for reviewers:
こちらも2人目レビューされないとマージできないので、どなたかお時間あるときに最終確認お願いします！

2020-08-30 08:31 UTC, thesugar requested changes
翻訳ありがとうございました！
2 人目のレビューがかなり遅くなってしまって本当に申し訳ありません。
細かい部分にはなりますが、何点かコメントさせていただきましたのでご確認ください。

2020-08-30 08:31 UTC, thesugar commented on docs/api-reference/next.config.js/static-optimization-indicator.md
> +description: 最適化されたページには、静的に最適化されているかどうかを知らせるインジケーターが含まれています。オプトアウトの方法を見ていきましょう。
```suggestion
description: 最適化されたページには、静的に最適化されているかどうかを知らせるインジケーターが含まれています。また、こちらでオプトアウトすることができます。
```

「オプトアウトの方法を見ていきましょう」だと、オプトアウトについて（のみ）説明しているページのように見えてしまうかなと思い、（原文には and や also などがないので、原文には忠実ではなくなってしまいますが）「また」を加えてみました。

2020-08-30 08:31 UTC, thesugar commented on docs/api-reference/next.config.js/static-optimization-indicator.md
> +Automatic Static Optimization 自体とても有益なものですし、開発中にページが適格であるかどうかすぐに分かるので、これは役に立ちます。
```suggestion
Automatic Static Optimization 自体とても有益なものですし、ページが Automatic Static Optimization の対象であるか開発時にすぐ分かるので、これは役に立ちます。
```

「適格であるかどうか」だと、何を意味するのかわかりづらいかなと思いました。ここの qualifies は上の行の qualifies for Automatic Static Optimization と同じことを指していると思いますので、少し長くはなりますが「ページが Automatic Static Optimization の対象である（かどうか）」と訳してみました。

「あるかどうか」-> 「あるか」、「すぐに」-> 「すぐ」と変更したのは、手元で textlint を走らせたときに助詞エラーが出たので修正しているものです。

2020-08-30 08:31 UTC, thesugar commented on docs/api-reference/next.config.js/static-optimization-indicator.md
すみません、## Related 以下の部分の訳も↓のように加えていただけるとありがたいです！

```
## 関連事項

<div class="card">
  <a href="/docs/api-reference/next.config.js/introduction.md">
    <b>next.config.js の紹介</b>
    <small>Next.js で使用する設定ファイルについて詳しく学びましょう。</small>
  </a>
</div>
<div class="card">
  <a href="/docs/advanced-features/automatic-static-optimization.md">
    <b>Automatic Static Optimization:</b>
    <small>Next.jsは可能な限り静的HTMLにすることで自動でアプリケーションを最適化します。どのように動くか学んでみましょう。</small>
  </a>
</div>
```

2020-09-05 07:14 UTC, Hiro0206 commented on docs/api-reference/next.config.js/static-optimization-indicator.md
訳が漏れてました。。。すいません(_ _)
こちらの指摘内容を取り込みましたので、確認お願いします！
441ca63

2020-09-06 14:47 UTC, thesugar approved these changes

2020-09-06 14:51 UTC, thesugar commented
@Hiro0206 さん
さっそくにご対応ありがとうございました！LGTMです！

@yokinist さん
すみません、私が request changes したために yokinist さんの approve が外れてしまったみたいで。。お手数ですが今一度お願いします 🙇

2020-09-06 16:00 UTC, yokinist approved these changes
ありがとうございます！LGTMです！

2020-09-06 16:18 UTC, merged