docs: translate docs/routing/shallow-routing.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #152
Opened 2020-08-01 08:51 UTC by tanakaKSUK

遅くなってごめんなさい。やる気がどっかにいってしまってました。
docs/routing/shallow-routing.md を翻訳しました。
不備等あったらおしえてください！一瞬で直します。

2020-08-02 10:15 UTC, yokinist requested changes
翻訳いただきありがとうございます！
確認するの遅れてしまいましたが、

- textlint のエラー(自動修正できないもの)
- 細かい日本語の表現についての提案

についてコメントさせていただきました！

自動修正可能な textlint のエラーが複数あるので、作業環境で `yarn text-lint:fix docs/routing/shallow-routing.md` を走らせて修正してみてください！その上で、コメントさせていただいた点について確認し問題なければ修正お願いします！🙏

その際、PR 上で `Suggested change` から取り込んでしまうと lint の兼ね合いもあり二度手間になってしまうので、お手元の環境でまとめてコミットしていただくのがいいかと思います。スペースの取り扱いについて情報更新したのでわからないところがあれば、[こちら](https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/blob/master/styleguide.md#%E5%8D%8A%E8%A7%92%E3%81%A8%E5%85%A8%E8%A7%92%E3%81%AE%E3%82%B9%E3%83%9A%E3%83%BC%E3%82%B9)を参考にしていただければと思います！

よろしくおねがいします🙇‍♂️

2020-08-02 10:15 UTC, yokinist commented on docs/routing/shallow-routing.md
> +description: 浅いルーティングを利用することで、新しいページ変更をトリガーせずにURLを変更できます。このページで学びましょう。
```suggestion
description: 浅いルーティングを利用することで、新しいページの変更をトリガーせずにURLを変更できます。このページで学びましょう。
```
「の」が間にあったほうが自然かなと思いました！

2020-08-02 10:15 UTC, yokinist commented on docs/routing/shallow-routing.md
> +    <li><a href="https://github.com/zeit/next.js/tree/canary/examples/with-shallow-routing">浅いルーティング</a></li>
```suggestion
    <li><a href="https://github.com/vercel/next.js/tree/canary/examples/with-shallow-routing">浅いルーティング</a></li>
```
リンクの更新

2020-08-02 10:15 UTC, yokinist commented on docs/routing/shallow-routing.md
> +以下に示すように、 [`componentDidUpdate`](https://reactjs.org/docs/react-component.html#componentdidupdate) を介してURLの変更を監視することもできます:
```suggestion
以下に示すように、 [`componentDidUpdate`](https://reactjs.org/docs/react-component.html#componentdidupdate) を介してURLの変更を監視もできます:
```
https://github.com/textlint-ja/textlint-rule-ja-no-redundant-expression#dict2  ja-technical-writing/ja-no-redundant-expression

2020-08-02 10:15 UTC, yokinist commented on docs/routing/shallow-routing.md
> +これは新しいページなので、浅いルーティングを行うように設定していても、現在のページを読み込まず、新しいページを読み込み、データの取得を待ちます。
```suggestion
これは新しいページなので、浅いルーティングを設定していても現在のページを破棄し、新しいページを読み込みデータの取得を待ちます。
```
一つの文で"、"を3つ以上使用しています
ja-technical-writing/max-ten
に関連して文章をシンプルにしてみました。 `unload` については読み込んだものを捨てるようなニュアンスかなと思い「破棄」と訳しました。

2020-08-02 10:15 UTC, yokinist commented on docs/routing/shallow-routing.md
> +  [`router` object](/docs/api-reference/next/router.md#router-object)( [`useRouter`](/docs/api-reference/next/router.md#useRouter) や [`withRouter`](/docs/api-reference/next/router.md#withRouter)によって追
```suggestion
更新された` pathname`と `query` は、状態を失うことなく  [`router` オブジェクト](/docs/api-reference/next/router.md#router-object)( [`useRouter`](/docs/api-reference/next/router.md#useRouter) や [`withRouter`](/docs/api-reference/next/router.md#withRouter)によって追加されたもの)を介して受け取ることができます。
```
最初から単語が並ぶと分かりづらい印象を受けたので文章を並び替えて読みやすくしてみました

2020-08-02 10:15 UTC, yokinist commented on docs/routing/shallow-routing.md
> +浅いルーティングを有効にするには、 `shallow` オプションを `true`に設定します。 以下の例を考えてみましょう:
```suggestion
浅いルーティングを有効にするには、 `shallow` オプションを `true`に設定します。 以下を例に考えてみましょう:
```
細かい表現ですが例を考えるといよりも、例として考えてみるような方が伝わりやすいなと思いました

2020-08-02 10:15 UTC, yokinist commented on docs/routing/shallow-routing.md
> +ページが置き換えられないまま、URLは `/?counter=10` に更新されます。 ルートの状態のみが変更されます。
```suggestion
ページが置き換えられないまま、URLは `/?counter=10` に更新されます。 ルートの状態のみ変更されます。
```
細かいところですが、「のみ」または「だけが」の方が違和感ないように感じました。

2020-08-02 10:15 UTC, yokinist commented on docs/routing/shallow-routing.md
> +    // 新しいqueryに基づいてデータを取得する
```suggestion
    // 新しい query に基づいてデータを取得する
```
上と同様半角スペースを置きました

2020-08-02 13:29 UTC, tanakaKSUK commented
添削ありがとうございます。指摘された箇所を修正しました。

2020-08-02 15:48 UTC, yokinist requested changes
@tanakaKSUK 
早速のご対応ありがとうございます！
基本的は問題ないのですが、現状の lint 側で制御できない細かい箇所があり追加で数点コメントさせていただきました！再度となってしまい恐縮ですがご確認いただけると幸いです🙏

2020-08-02 15:48 UTC, yokinist commented on docs/routing/shallow-routing.md
> +浅いルーティングにより、 [`getServerSideProps`](/docs/basic-features/data-fetching.md#getserversideprops-server-side-rendering), [`getStaticProps`](/docs/basic-features/data-fetching.md#getstaticprops-static-gen
```suggestion
浅いルーティングにより、[`getServerSideProps`](/docs/basic-features/data-fetching.md#getserversideprops-server-side-rendering) や [`getStaticProps`](/docs/basic-features/data-fetching.md#getstaticprops-static-generation) そして [`getInitialProps`](/docs/api-reference/data-fetching/getInitialProps.md) を含むデータフェッチメソッドを再度実行せずに URL を変更できます。
```
ごめんなさい！見落としていましたが半角カンマのところは英語表記においてのものなので、日本語にしちゃうか句読点にしたほうがいいと思いました！

2020-08-02 15:48 UTC, yokinist commented on docs/routing/shallow-routing.md
> +更新された ` pathname` と `query` は、状態を失うことなく  [`router` オブジェクト](/docs/api-reference/next/router.md#router-object)( [`useRouter`](/docs/api-reference/next/router.md#useRouter) や [`withRouter`](/docs/api-re
```suggestion
更新された `pathname` と `query` は、状態を失うことなく  [`router` オブジェクト](/docs/api-reference/next/router.md#router-object)( [`useRouter`](/docs/api-reference/next/router.md#useRouter) や [`withRouter`](/docs/api-reference/next/router.md#withRouter) によって追加されたもの)を介して受け取ることができます。
```

2020-08-02 15:48 UTC, yokinist commented on docs/routing/shallow-routing.md
> +浅いルーティングを有効にするには、 `shallow` オプションを `true`に設定します。以下を例に考えてみましょう:
```suggestion
浅いルーティングを有効にするには、`shallow` オプションを `true` に設定します。以下を例に考えてみましょう:
```

2020-08-02 15:48 UTC, yokinist commented on docs/routing/shallow-routing.md
> +以下に示すように、 [`componentDidUpdate`](https://reactjs.org/docs/react-component.html#componentdidupdate) を介して URL の変更を監視もできます:
```suggestion
以下に示すように、[`componentDidUpdate`](https://reactjs.org/docs/react-component.html#componentdidupdate) を介して URL の変更を監視もできます:
```

2020-08-02 15:48 UTC, yokinist commented on docs/routing/shallow-routing.md
> +浅いルーティングは同じページの URL の変更に対して**のみ**機能します。例えば、 `pages / about.js`という別のページがあり、これを実行するとします:
```suggestion
浅いルーティングは同じページの URL の変更に対して**のみ**機能します。例えば、`pages/about.js`という別のページがあり、これを実行するとします:
```

2020-08-03 08:08 UTC, tanakaKSUK commented
お手数おかけしてすみません！
修正しました。ご確認おねがいします。

2020-08-03 08:38 UTC, yokinist approved these changes
ありがとうございました！僕からはLGTMです🙌

2020-08-04 10:04 UTC, yokinist commented
@all-contributors please add @tanakaKSUK for translation

2020-08-04 10:43 UTC, hiro08gh commented
翻訳していただきありがとうございます！LGTMです！

2020-08-04 10:43 UTC, hiro08gh approved these changes

2020-08-04 10:47 UTC, merged