docs: add suppor-ted-browsers-features.md and edit manifest.json, faq.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #172
Opened 2020-10-02 13:41 UTC by ia17011

2020-10-02 13:44 UTC, ia17011 commented on docs/faq.md
> -<details>
おそらく今回翻訳したページが追加されたタイミングで，公式のほうでこの faqが削除されていました．
それに倣い，内容がかぶるためこちらでも削除したほうが良いかなと思いました．

Next.js FAQ : [https://nextjs.org/docs/faq](https://nextjs.org/docs/faq)

2020-10-05 03:01 UTC, yokinist requested changes
翻訳のご協力ありがとうございます！
いずれも細かい点ですが数点コメントさせていただきました 🙏

2020-10-05 03:01 UTC, yokinist commented on docs/basic-features/supported-browsers-features.md
> +description: Next.js がサポートしているブラウザと JavaScript の言語機能
JavaScript 自体が言語なのと、原文にも特に書かれていないのでこちらは省略してもいいのかなと思いました！
```suggestion
description: Next.js がサポートしているブラウザと JavaScript の機能
```

2020-10-05 03:01 UTC, yokinist commented on docs/basic-features/supported-browsers-features.md
> +クライアント側での `fetch()` に加えて、 Next.js は Node.js 環境でも `fetch()` の polyfilsl を行います。 サーバー側のコード (例えば `getStaticProps`) では、 `isomorphic-unfetch` や `node-fetch` のような polyfills を使わずに `fetch()` を使用できます。
- typo
- [半角と全角のスペース](https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/blob/master/styleguide.md#半角と全角のスペース)
の修正
- `のような` -> `などの`
  - 「似ている」といった意味としても受け取れてしまうので、ここでは `such as` を具体的な例の1つといった意味で「などの」に留めておいた方が適切かと思いました
```suggestion
クライアント側での `fetch()` に加えて、Next.js は Node.js 環境でも `fetch()` の polyfills を行います。 サーバー側のコード (例えば `getStaticProps`) では、`isomorphic-unfetch` や `node-fetch` などの polyfills を使わずに `fetch()` を使用できます。
```

2020-10-05 03:01 UTC, yokinist commented on docs/basic-features/supported-browsers-features.md
> +- など
原文の表記に沿って `!` のニュアンスを追加してもよさそうです
```suggestion
- などなど！
```

2020-10-05 03:01 UTC, yokinist commented on docs/basic-features/supported-browsers-features.md
> +独自のコードや外部の npm 依存関係で、ターゲットブラウザにてサポートされていない機能が必要な場合は、 polyfills を追加する必要があります。
原文の表記に沿って `yourself` のニュアンスを追加してもよさそうです

```suggestion
独自のコードや外部の npm 依存関係で、ターゲットブラウザにてサポートされていない機能が必要な場合は、自分自身で polyfills を追加する必要があります。
```

2020-10-05 03:01 UTC, yokinist commented on docs/basic-features/supported-browsers-features.md
> +Next.js は **IE11 と全てのモダンブラウザ** (Edge, Firefox, Chrome, Safari や Opera など) を必要な設定なしでサポートしています。
こちらの方が自然な訳かなと思いましたがいかがでしょうか
```suggestion
Next.js は **IE11 と全てのモダンブラウザ** (Edge, Firefox, Chrome, Safari や Opera など) をサポートしており、設定は不要です。
```

2020-10-05 03:01 UTC, yokinist commented on docs/basic-features/supported-browsers-features.md
> +# サポートされているブラウザと機能
こちらの方が自然な訳かなと思いましたがいかがでしょうか
```suggestion
# サポートしているブラウザと機能
```

2020-10-05 03:01 UTC, yokinist commented on docs/manifest.json
> +              "title": "サポートされているブラウザと機能",
```suggestion
              "title": "サポートしているブラウザと機能",
```

2020-10-05 08:13 UTC, ia17011 commented on docs/basic-features/supported-browsers-features.md
> +クライアント側での `fetch()` に加えて、 Next.js は Node.js 環境でも `fetch()` の polyfilsl を行います。 サーバー側のコード (例えば `getStaticProps`) では、 `isomorphic-unfetch` や `node-fetch` のような polyfills を使わずに `fetch()` を使用できます。
ありがとうございます！！

2020-10-05 08:43 UTC, yokinist commented on docs/basic-features/supported-browsers-features.md
> +- などなど！
失礼しました。こちら連続していると textlint 
にひっかかってしまうようですね・・（自明なのでこのまま取り込んでしまいます）
```suggestion
- など！
```

2020-10-05 08:46 UTC, yokinist approved these changes
LGTMです 👍 
ありがとうございます！

2020-10-05 08:48 UTC, yokinist commented
@all-contributors please add @ia17011 for translation

2020-10-07 11:24 UTC, Shinyaigeek approved these changes
LGTMです！ありがとうございます！！

2020-10-07 11:29 UTC, merged