docs:translate docs/api-reference/next.config.js/trailing-slash.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #175
Opened 2020-10-18 06:19 UTC by f-teruhisa

`docs/api-reference/next.config.js/trailing-slash.md` を翻訳いたしました。
レビューをお願いします。

2020-10-21 13:42 UTC, yokinist requested changes
@f-teruhisa 
翻訳のご協力ありがとうございます！
何点かコメントいたしましたのでご確認ください 🙏 
- Trailing Slash の訳について
- 改行について
- スペースの例外について

2020-10-21 13:42 UTC, yokinist commented on docs/api-reference/next.config.js/trailing-slash.md
> +Next.js では、末尾にスラッシュが付いている URL から、末尾にスラッシュが付いていない URL にデフォルトでリダイレクトします。例えば、 `/about/` は `/about` にリダイレクトされます。この動作を逆に設定し、URL の末尾にスラッシュがない場合は、末尾にスラッシュがある URL にリダイレクトさせることもできます。
- 原文の改行はそのままで残す形でお願いします！
```suggestion

Next.js では、末尾にスラッシュが付いている URL から、末尾にスラッシュが付いていない URL にデフォルトでリダイレクトします。例えば、`/about/` は `/about` にリダイレクトされます。この動作を逆に設定し、URL の末尾にスラッシュがない場合は、末尾にスラッシュがある URL にリダイレクトさせることもできます。
```

2020-10-21 13:42 UTC, yokinist commented on docs/api-reference/next.config.js/trailing-slash.md
> +`next.config.js` を開き、 `trailingSlash` の設定を追加してください:
他の箇所もなのですが、句読点の場合は例外的に英単語と和文の間のスペースいれない方針でお願いしたいです！細かいところで恐縮です 🙇 
> 約物（特に句読点 。, 、）と直接隣接している場合は英単語と和文の間のスペースはいれないでください。
https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/blob/master/styleguide.md#%E5%8D%8A%E8%A7%92%E3%81%A8%E5%85%A8%E8%A7%92%E3%81%AE%E3%82%B9%E3%83%9A%E3%83%BC%E3%82%B9

```suggestion
`next.config.js` を開き、`trailingSlash` の設定を追加してください:
```

2020-10-21 13:42 UTC, yokinist commented on docs/api-reference/next.config.js/trailing-slash.md
> +このオプションの設定を追加すると、 `/about` のような URL は `/about/` へリダイレクトされるようなります。
```suggestion
このオプションの設定を追加すると、`/about` のような URL は `/about/` へリダイレクトされるようなります。
```

2020-10-21 13:42 UTC, yokinist commented on docs/api-reference/next.config.js/trailing-slash.md
> +# トレイリングスラッシュ
IMO: ページタイトルや見出しを `トレイリングスラッシュ` とするか `Trailing Slash` とするか `末尾のスラッシュ` にするかは悩ましいところですね、、個人的には「末尾のスラッシュ」が単純明快でいいかなと思いましたがいかがでしょうか？

```suggestion
# 末尾のスラッシュ
```

2020-10-21 13:42 UTC, yokinist commented on docs/manifest.json
> +              "title": "トレイリングスラッシュ",
IMO:
```suggestion
              "title": "末尾のスラッシュ",
```

2020-10-21 13:42 UTC, yokinist commented on docs/api-reference/next.config.js/trailing-slash.md
> +description: トレイリングスラッシュで Next.js のページを解決できるように設定します。
IMO:
```suggestion
description: 末尾のスラッシュで Next.js のページを解決できるように設定します。
```

2020-10-24 05:54 UTC, f-teruhisa commented on docs/api-reference/next.config.js/trailing-slash.md
> +# トレイリングスラッシュ
`末尾のスラッシュ` の方がどんなスラッシュかの意味がわかりやすいと思ったので、いただいた提案を取り込めればと思います 🙇

2020-10-24 06:01 UTC, f-teruhisa commented
@yokinist 
ありがとうございますｍ
Suggestionを取り込ませていただきましたので、再度レビューいただけますと幸いです。

2020-10-24 06:03 UTC, f-teruhisa commented on docs/api-reference/next.config.js/trailing-slash.md
> +`next.config.js` を開き、 `trailingSlash` の設定を追加してください:
承知いたしました！以後気をつけます :bow:

2020-10-24 06:04 UTC, f-teruhisa commented on docs/api-reference/next.config.js/trailing-slash.md
> +description: トレイリングスラッシュで Next.js のページを解決できるように設定します。
`有無` と表記している方がわかりやすいですね、ありがとうございますｍ

2020-10-25 07:11 UTC, yokinist approved these changes
ご確認ありがとうございます！LGTMです👍

2021-01-23 05:57 UTC, 5t111111 approved these changes
LGTM 👍

2021-01-23 06:08 UTC, yokinist commented
@f-teruhisa 
大変お待たせしてしまいましたが、こちら取り込ませていただきます 🙇 
ご協力ありがとうございました！！

2021-01-23 06:08 UTC, merged