docs:translate docs/api-reference/next.config.js/react-strict-mode.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #177
Opened 2020-10-19 13:29 UTC by f-teruhisa

`docs/api-reference/next.config.js/react-strict-mode.md` を翻訳いたしました。
レビューをお願いします。

2020-10-21 14:19 UTC, yokinist requested changes
@f-teruhisa 
こちらも翻訳のご協力ありがとうございます🙌
数点コメントいたしましたので、ご確認よろしくお願いします！

2020-10-21 14:19 UTC, yokinist commented on docs/api-reference/next.config.js/react-strict-mode.md
> +description: Next.js ランタイムが、完全に Strict モードに準拠しました。オプトインの方法を学びましょう。
ここでの `The complete` の訳については「すべて」とした方が適切だと思いました！
```suggestion
description: すべての Next.js ランタイムは、Strict モードに準拠しました。オプトインの方法を学びましょう。
```

2020-10-21 14:19 UTC, yokinist commented on docs/api-reference/next.config.js/react-strict-mode.md
> +> **推奨**: Next.js アプリケーションで Strict モードを有効にして、これからの React に備えておくことをおすすめします。
- `strongly` の訳を追加
- 自然な訳となるように入れ替え
- 表記ゆれ: 「おすすめ」 -> 「お勧め」
```suggestion
> **推奨**: これからの React に備えて、Next.js アプリケーションで Strict モードを有効にしておくことを強くお勧めします。
```

2020-10-21 14:19 UTC, yokinist commented on docs/api-reference/next.config.js/react-strict-mode.md
> +Next.js ランタイムは、現在 Strict モードに準拠しています。Strict モードを有効にするには、 `next.config.js` で以下のオプションを設定してください :
- 原文にあわせ改行
- 約物後のスペース削除
```suggestion

Next.js ランタイムは、現在 Strict モードに準拠しています。Strict モードを有効にするには、`next.config.js` で以下のオプションを設定してください :
```

2020-10-21 14:19 UTC, yokinist commented on docs/api-reference/next.config.js/react-strict-mode.md
> +あなたやチームが、アプリケーション全体で Strict モードを使用する準備ができていなくても問題ありません。 [`<React.StrictMode>` を使用](https://reactjs.org/docs/strict-mode.html)して、ページ単位で段階的に移行できます 。
- 原文にあわせて感嘆符を追加
```suggestion
あなたやチームが、アプリケーション全体で Strict モードを使用する準備ができていなくても問題ありません！[`<React.StrictMode>` を使用](https://reactjs.org/docs/strict-mode.html)して、ページ単位で段階的に移行できます 。
```

2020-10-24 06:06 UTC, f-teruhisa commented on docs/api-reference/next.config.js/react-strict-mode.md
> +description: Next.js ランタイムが、完全に Strict モードに準拠しました。オプトインの方法を学びましょう。
おっしゃる通りですねｍ
ありがとうございます！

2020-10-24 06:12 UTC, f-teruhisa commented
@yokinist
詳細までレビューいただき助かります 🙌 
こちらもSuggestionを取り込ませていただきましたので、再度レビューいただけますと幸いです。

2020-10-25 07:12 UTC, yokinist approved these changes
ご確認ありがとうございます！こちらもLGTMです👍

2020-10-26 08:56 UTC, hiro08gh commented
ありがとうございます！LGTMです！

2020-10-26 08:57 UTC, hiro08gh approved these changes

2020-10-26 08:57 UTC, merged