docs:translate docs/api-reference/next.config.js/headers.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #179
Opened 2020-10-20 13:33 UTC by f-teruhisa

`docs/api-reference/next.config.js/headers.md`を翻訳いたしました。
レビューをお願いします。

2020-10-25 08:41 UTC, yokinist requested changes
@f-teruhisa こちらも翻訳ありがとうございます！ 😭 
レビュータイミングずれてしまいましたが、何点かコメントしたのでご確認よろしくお願いします！

2020-10-25 08:41 UTC, yokinist commented on docs/api-reference/next.config.js/headers.md
> +# 独自のヘッダー
原文には custom がないので「ヘッダー」でいいかと思いました！
```suggestion
# ヘッダー
```

2020-10-25 08:41 UTC, yokinist commented on docs/api-reference/next.config.js/headers.md
> +ヘッダー内では、リクエストパスに独自の HTTP ヘッダーを設定できます。
- 改行
- `incoming` の訳語として「受け取る」を追加
```suggestion

ヘッダーでは、受け取るリクエストパスに対して独自の HTTP ヘッダーを設定できます。
```

2020-10-25 08:41 UTC, yokinist commented on docs/api-reference/next.config.js/headers.md
> +-  `headers` は `key` と `value` を持つヘッダーオブジェクトの配列です
- 文末に「。」を追加
- `incoming` の訳を追加
- `properties` の訳を追加
- 半角スペースが入り込んでいたので削除
```suggestion
- `source` は受け取るリクエストパスのパターンです。
- `headers` は `key` と `value` プロパティを持つヘッダーオブジェクトの配列です。
```

2020-10-25 08:41 UTC, yokinist commented on docs/api-reference/next.config.js/headers.md
> +## ヘッダーのオーバーライド時の振る舞い
オーバーライドは上書きの方が伝わりやすいかなと思いました！(あと語感が良さそうというのも...)
```suggestion
## ヘッダー上書き時の振る舞い
```

2020-10-25 08:41 UTC, yokinist commented on docs/api-reference/next.config.js/headers.md
> +2 つのヘッダーが同じパスにマッチし同じヘッダーキーが設定されていた場合、最後のヘッダキーが最初のヘッダーキーをオーバーライドします。以下のヘッダーを使うと、パス `/hello` は最後のヘッダーの値 `world` に設定されているため、ヘッダー `x-hello` の値は `world` となります。
- typo: 「ヘッダキー」 -> 「ヘッダーキー」
- 一文が長かったので句読点 を追加
- `being` の訳を「である」に変更

```suggestion
2 つのヘッダーが同じパスにマッチし、同じヘッダーキーが設定されていた場合、最後のヘッダーキーが最初のヘッダーキーを上書きします。以下のヘッダーを使うと、パス `/hello` は最後のヘッダーの値が `world` であるため、ヘッダー `x-hello` の値は `world` となります。
```

2020-10-25 08:41 UTC, yokinist commented on docs/api-reference/next.config.js/headers.md
> +以下の `/blog/:slug` は `/blog/hello-world` とマッチします (ネストされているパスはありません):
- `Path matches are allowed` の訳を追加
```suggestion
パスのマッチングができます。例えば、`/blog/:slug` は `/blog/hello-world` とマッチします (ネストされているパスはありません):
```

2020-10-25 08:41 UTC, yokinist commented on docs/api-reference/next.config.js/headers.md
> +### ワイルドカードを使ったパスのマッチング
正規表現の箇所と表記が違うので「使った or  用いた」はどちらかに統一しちゃったほうがいいと思いました！
```suggestion
### ワイルドカードを用いたパスのマッチング
```

2020-10-25 08:41 UTC, yokinist commented on docs/api-reference/next.config.js/headers.md
> +  async headers() {
どうやら原文が typo だったようです。ありがとうございます！
https://github.com/vercel/next.js/commit/58edd0998c4d3ec0967a6386dfcb877978aae4f8

2020-10-25 08:41 UTC, yokinist commented on docs/api-reference/next.config.js/headers.md
> +### basePathをサポートしたヘッダー
- 半角スペースを追加
```suggestion
### basePath をサポートしたヘッダー
```

2020-10-25 08:41 UTC, yokinist commented on docs/api-reference/next.config.js/headers.md
> +ヘッダーで [`basePath` サポート](/docs/api-reference/next.config.js/basepath.md) を利用する際はヘッダーに `basePath: false` を追加しない限り、各 `source` に自動的に `basePath` をプレフィックスとして付与します:
- 「サポート」と「を利用〜」の間は日本語同士なのでスペースが不要
- 意味合いとしては変わらないんですが、少し変えたら伝わりやすくなった気がするので提案です！
```suggestion
ヘッダーで [`basePath` サポート](/docs/api-reference/next.config.js/basepath.md)を利用する際は、ヘッダーに `basePath: false` を追加しない限り、各 `source` に対して自動的に `basePath` がプレフィックスとして付与されます:
```

2020-10-28 13:46 UTC, f-teruhisa commented
@yokinist 
レビューありがとうございます！
変更を取り込ませていただきましたので、再度レビューをお願いします 🙇

2020-10-29 02:21 UTC, yokinist approved these changes
ありがとうございます！こちらLGTMです👍

2021-01-23 05:57 UTC, 5t111111 approved these changes
LGTM 👍

2021-01-23 06:11 UTC, yokinist commented
こちらも取り込ませていただきます！！！ありがとうございました！！

2021-01-23 06:11 UTC, merged