docs: update(2021-01-22)
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #186
Opened 2021-01-22 01:02 UTC by yokinist

2021-01-22 01:05 UTC, hiro08gh submitted a review, later dismissed

2021-01-22 02:07 UTC, 5t111111 reviewed
翻訳ソース (本気repoの `canary`) では、

```
docs/api-reference/next.config.js/build-target.md
```

のファイルが削除されているようです。

把握できておらずすみませんが、ソース側でのページ削除時の追従のポリシーなどあれば教えてください！

2021-01-22 02:28 UTC, yokinist commented
> 翻訳ソース (本気repoの `canary`) では、
> 
> ```
> docs/api-reference/next.config.js/build-target.md
> ```
> 
> のファイルが削除されているようです。
> 
> 把握できておらずすみませんが、ソース側でのページ削除時の追従のポリシーなどあれば教えてください！



確認ありがとうございます！確認漏れでした！
削除の際の対応ポリシーは決められていませんでした。

以下の考えで追従させていました

```
- 本家で新規作成されたファイルは追加する
- 未翻訳のファイルが本家で更新されていたら更新する
```

ただ、本家にはないドキュメントが残り続けてしまうのは誤解を生みかねないため

- 翻訳の有無関わらず本家で削除されたファイルは削除する

を追従ポリシーとして追加したいと思いますが(該当ファイルを翻訳していただいた方には申し訳ない気持ちもありますが...)、いかがでしょうか？また、翻訳済の情報の更新については別途考えたいと思います！

2021-01-22 02:31 UTC, 5t111111 commented
確認ありがとうございます。

> 翻訳の有無関わらず本家で削除されたファイルは削除する

おっしゃる通り申し訳なさはありますね…が、ソースで削除されたものを残しておくことはできないと思うので、こちらの方針に同意します！

2021-01-22 02:47 UTC, yokinist commented
今後のために README に追従方針を記載 & 該当ファイルの削除しました！
お手数ですが再度ご確認お願いします 🙏

2021-01-22 02:52 UTC, 5t111111 requested changes
削除ファイルについて、反映ありがとうございます。
差分を見ていて、改めて気づいた点が一点あったので、こちらも確認お願いします！

2021-01-22 02:52 UTC, 5t111111 commented on docs/migrating/from-react-router.md
> +---
新規追加のファイルのようですが、 `<!-- textlint-disable -->` がないようです。これは意図したものですか？

2021-01-22 02:59 UTC, yokinist commented on docs/migrating/from-react-router.md
> +---
意図したものです！
ファイルによってはひっかからないものもありますが、以下に該当する場合は precommit 時にはじかれてしまってコミットできなかったため、textlint でひっかかったもののみ書いています！（消極的な理由）

```
error  Disallow to use "?"  ja-technical-writing/no-exclamation-question-mark
error  Disallow to use "!"  ja-technical-writing/no-exclamation-question-mark
error  This sentence exceeds the maximum count of comma. Maximum is 3  ja-technical-writing/max-comma
```

2021-01-22 03:01 UTC, 5t111111 commented on docs/migrating/from-react-router.md
> +---
なるほど、そういうことですね。理解しました。ありがとうございます！

2021-01-22 03:02 UTC, 5t111111 approved these changes
疑問点などすべて解消いただけました。LGTM 👍

2021-01-22 03:08 UTC, yokinist commented
@all-contributors please add @5t111111 for review

2021-01-23 04:53 UTC, hiro08gh approved these changes

2021-01-23 05:14 UTC, merged