docs: translate docs/basic-features/image-optimization.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #195
Opened 2021-01-26 02:59 UTC by kenzoukenzou

`docs/basic-features/image-optimization.md`を翻訳しました。
お手すきの際、ご確認よろしくお願い致します！🙇‍

2021-01-26 03:11 UTC, kenzoukenzou commented on docs/basic-features/image-optimization.md
> +`s-maxage` が `Cache-Control` に見つかった場合、それを使用します。 `s-maxage` が見つからない場合、 `max-age` を使用します。 `max-age` が見つからない場合、 60 秒を使用します。
原文に合わせると `が使用されます` とする方が適切かなと考えたのですが、textlint に弾かれるとため上記のような訳し方をしております。

2021-01-26 03:11 UTC, kenzoukenzou commented on docs/basic-features/image-optimization.md
>  ## Advanced
`発展的`のように無理に訳すと不自然かなと思い、そのまま残しました👀

2021-01-27 04:19 UTC, kenzoukenzou commented
1点 typo があったため修正を入れておきました🙇‍

2021-02-20 15:00 UTC, Shinyaigeek requested changes
@kenzoukenzou 翻訳ありがとうございます 🙏 
また, レビューが遅れてしまいすみません 🙇 
いくつかコメント, 指摘, suggestionを出したのでお手すきの時に確認お願いします 🙏

2021-02-20 15:00 UTC, Shinyaigeek commented on docs/basic-features/image-optimization.md
> +自動的な画像最適化により、ブラウザがサポートしている場合、 [WebP](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types) のようなモダンな形式で画像のサイズ変更、最適化及び提供が可能です。これはビューポートがより小さいデバイスに大きな画像を送信することを避けます。また、 Next.js が将来の画像形
webpは画像フォーマット云々で, 画像のリサイズには関係しない(はず)だったので, 少々違和感を覚えました.

文章的に, "resizing" と "optimizing" と "serving images in modern..." は等価であると思われるので, 訳的には「リサイズや最適化、ブラウザがサポートしている場合においてのwebpのようなモダンな形式での画像の配信が可能です。」といった感じの方が自然かなと感じましたが如何でしょうか？

また,  serve はこの場合サーバーからのserveであるので, 「配信する」などの訳の方が適切かと感じましたが如何でしょうか？

2021-02-20 15:00 UTC, Shinyaigeek commented on docs/basic-features/image-optimization.md
> +ビルド時に画像を最適化する代わりに、 Next.js はユーザーのリクエストに応じてオンデマンドで画像を最適化します。静的サイトジェネレーターや静的のみのソリューションと異なり、 10 枚の画像を公開する場合でも 1,000 万枚の画像を公開する場合でも、ビルド時間は増加しません。
「静的のみのソリューション」というのが何を指しているのが不明瞭に感じました。solutionをもうちょっと意訳してあげてもいいのかなと感じましたが如何でしょうか？

ただ僕も "static-only solutions" が何を指しているのかちょっとわかっていないんですよね...
画像処理とビルド時間の話をしているので実は "Unlike static site generators and static-only solutions" は Unlike A and B(AとBとは違い)ではなくてUnlike A and B(Aに伴ってのB), つまり「SSGとそれに伴う静的な画像の最適化処理」という意味なのかなとも感じましたがいまいち文法的にもしっくり来ないんですよね...

ここは @kenzoukenzou さんや他のレビュワーの方々の意見も聞いてみたいです 🙏

2021-02-20 15:00 UTC, Shinyaigeek commented on docs/basic-features/image-optimization.md
> +画像はデフォルトで遅延読み込みされます。つまりビューポート外の画像に対してページ速度が低下することはありません。画像はビューポートにスクロールされると読み込まれます。
```suggestion
画像はデフォルトで遅延読み込みされます。つまりビューポート外の画像によってページ速度が低下することはありません。画像はビューポートにスクロールされると読み込まれます。
```

「に対して」というよりかは「によって」, 「のせいで」というニュアンスの方が自然に感じられるような気がしましたが如何でしょうか？

2021-02-20 15:00 UTC, Shinyaigeek commented on docs/basic-features/image-optimization.md
> +もし Next.js のビルトイン画像最適化を使う代わりにクラウドプロバイダーを使用して画像を最適化したい場合、ローダーとプレフィックスを設定できます。これにより画像の `src` に相対 URL を使用し、プロバイダーの正しい絶対 URL を自動的に生成できます。
```suggestion
もし Next.js のビルトイン画像最適化を使う代わりにクラウドプロバイダーを使用して画像を最適化したい場合、ローダーとプレフィックスを設定できます。これにより画像の `src` に相対 URL を使用し、プロバイダー向けに正しい絶対 URL を自動的に生成できます。
```

2021-02-20 15:00 UTC, Shinyaigeek commented on docs/basic-features/image-optimization.md
> +有効期限（または最大経過時間）は、アップストリームサーバーの `Cache-Control` ヘッダーによって定義されます。
```suggestion
有効期限（というよりMax Age）は、アップストリームサーバーの `Cache-Control` ヘッダーによって定義されます。
```

`or rathar A`で「というより A」という訳になります.
また, わざわざ `Max Age` と `Cache-Control` ヘッダーの話をしているということからこれはCache-Controlに指定するmax-ageを固有名詞的に指していて, 訳するべきではないのではと感じましたが如何でしょうか？

2021-02-21 05:06 UTC, kenzoukenzou commented on docs/basic-features/image-optimization.md
> +画像はデフォルトで遅延読み込みされます。つまりビューポート外の画像に対してページ速度が低下することはありません。画像はビューポートにスクロールされると読み込まれます。
@Shinyaigeek ありがとうございます！
> 「に対して」というよりかは「によって」, 「のせいで」というニュアンスの方が自然に感じられる

そうですね！読み返すとそちらの方が自然に感じます！👀

2021-02-21 05:14 UTC, kenzoukenzou commented on docs/basic-features/image-optimization.md
> +有効期限（または最大経過時間）は、アップストリームサーバーの `Cache-Control` ヘッダーによって定義されます。
@Shinyaigeek こちらご指摘ありがとうございます！🙇‍ `or rather A` の訳知りませんでした👀  
> また, わざわざ Max Age と Cache-Control ヘッダーの話をしているということからこれはCache-Controlに指定するmax-ageを固有名詞的に指していて, 訳するべきではないのではと感じましたが如何でしょうか？

こちらの方針の方が良いと思いましたので、 https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/195/commits/f9287bd0e647b45e35de1e0d01e859aa505fee54 にて修正しています👀 (半角スペースを入れて対応しました)

2021-02-21 05:27 UTC, kenzoukenzou commented on docs/basic-features/image-optimization.md
> +自動的な画像最適化により、ブラウザがサポートしている場合、 [WebP](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types) のようなモダンな形式で画像のサイズ変更、最適化及び提供が可能です。これはビューポートがより小さいデバイスに大きな画像を送信することを避けます。また、 Next.js が将来の画像形
@Shinyaigeek 

> 文章的に, "resizing" と "optimizing" と "serving images in modern..." は等価である

ありがとうございます！🙇‍ なるほどです、ここが等価なのですね読み間違えていました.. 🙇‍ 「配信」の方が適切ですね！

主語の `The Automatic Image Optimization` のところどうするか迷っておりまして..
主語を入れて訳した場合はこんな感じで考えております👀

> 自動的な画像最適化により、リサイズや最適化、ブラウザがサポートしている場合においての [Webp](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types) のようなモダンな形式での画像配信を可能にします。

もしくは `自動的な画像最適化により` のところを省いてしまってた方が読みやすいですかね.. ？

> リサイズや最適化、ブラウザがサポートしている場合においての [Webp](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types) のようなモダンな形式での画像配信を可能にします。

2021-02-21 06:49 UTC, Shinyaigeek commented on docs/basic-features/image-optimization.md
> +自動的な画像最適化により、ブラウザがサポートしている場合、 [WebP](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types) のようなモダンな形式で画像のサイズ変更、最適化及び提供が可能です。これはビューポートがより小さいデバイスに大きな画像を送信することを避けます。また、 Next.js が将来の画像形
過去 "Automatic Static Optimization" を訳さずに固有名詞として扱ったという事があったので, それに倣って "Automatic Image Optimization" も固有名詞として扱って訳さずのままでいいのかなと感じました！

FYI: https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/66#pullrequestreview-451132533

2021-02-21 11:57 UTC, kenzoukenzou commented on docs/basic-features/image-optimization.md
> +自動的な画像最適化により、ブラウザがサポートしている場合、 [WebP](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types) のようなモダンな形式で画像のサイズ変更、最適化及び提供が可能です。これはビューポートがより小さいデバイスに大きな画像を送信することを避けます。また、 Next.js が将来の画像形
@Shinyaigeek ご意見ありがとうございます！🙇‍
訳さない方針で修正を加えました👀  https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/195/commits/fea070b3ee9a1cb1c1aefb84b85feecb7d49bac7

2021-02-21 12:25 UTC, kenzoukenzou commented on docs/basic-features/image-optimization.md
> +ビルド時に画像を最適化する代わりに、 Next.js はユーザーのリクエストに応じてオンデマンドで画像を最適化します。静的サイトジェネレーターや静的のみのソリューションと異なり、 10 枚の画像を公開する場合でも 1,000 万枚の画像を公開する場合でも、ビルド時間は増加しません。
@Shinyaigeek ここの段落は Gatsby などSSGライブラリとの比較や Next.js の利点を表現しているのかなと思っていました。なので "Unlike static site generators and static-only solutions" の訳は「...とは異なり」が適切かなと考えています👀 (Aに伴ってBは知りませんでした..)

"static-only solutions" のところは、「静的なHTMLを返すだけの諸々のやり方」くらいで捉えておりました.. 確かに「静的のみのソリューション」だと不明瞭ですね。

"Unlike static site generators and static-only solutions" のところを「静的サイトジェネレーターなどとは異なり」でまとめてしまうか、「静的サイトジェネレーターやその他の方法とは異なり」などが思いつきました。いかがでしょうか👀？

2021-02-22 01:08 UTC, 5t111111 commented on docs/basic-features/image-optimization.md
> +ビルド時に画像を最適化する代わりに、 Next.js はユーザーのリクエストに応じてオンデマンドで画像を最適化します。静的サイトジェネレーターや静的のみのソリューションと異なり、 10 枚の画像を公開する場合でも 1,000 万枚の画像を公開する場合でも、ビルド時間は増加しません。
僕も

> ここの段落は Gatsby などSSGライブラリとの比較や Next.js の利点を表現しているのかなと思っていました。

の認識です。
サーバーを利用して最適化する実装的にもこの文意であろう適切と考えています。

- 静的サイトジェネレーターやすべてが静的に構成される方式とは異なり

というのはいかがでしょうか？

「ソリューション」はそのままでも意味は通じますが、なんか訳文でそのまんま出てくると引っかかる感じなので (個人の感想ではある)、 @kenzoukenzou さんの「方法」という訳の方向性は文脈的に良いと思いました。その上で、より意味が確定しやすい「方式」としてみています。
そして、static-only 形容詞を意図から意訳して「すべてが静的に構成される」としてみました。

2021-02-23 03:55 UTC, kenzoukenzou commented on docs/basic-features/image-optimization.md
> +ビルド時に画像を最適化する代わりに、 Next.js はユーザーのリクエストに応じてオンデマンドで画像を最適化します。静的サイトジェネレーターや静的のみのソリューションと異なり、 10 枚の画像を公開する場合でも 1,000 万枚の画像を公開する場合でも、ビルド時間は増加しません。
@5t111111 ありがとうございます！！
> 静的サイトジェネレーターやすべてが静的に構成される方式とは異なり

具体的でとても良いと思いますので、

2021-02-23 04:17 UTC, kenzoukenzou commented
@Shinyaigeek レビューありがとうございました！
ご指摘頂いた箇所対応しましたのでお手すきの際ご確認お願い致します🙇‍

2021-02-28 09:38 UTC, Shinyaigeek commented on docs/basic-features/image-optimization.md
> +ビルド時に画像を最適化する代わりに、 Next.js はユーザーのリクエストに応じてオンデマンドで画像を最適化します。静的サイトジェネレーターや静的のみのソリューションと異なり、 10 枚の画像を公開する場合でも 1,000 万枚の画像を公開する場合でも、ビルド時間は増加しません。
良さそうです 👍

2021-02-28 09:38 UTC, Shinyaigeek approved these changes
対応ありがとうございます！LGTMです 👍

2022-02-10 12:17 UTC, Shinyaigeek commented
大変遅れました 🙏  マージします！

2022-02-10 12:17 UTC, merged