docs: translate docs/advanced-features/i18n-routing.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #196
Opened 2021-01-26 23:23 UTC by kei178

`docs/advanced-features/i18n-routing.md` を翻訳しました！
レビューよろしくお願いいたします。

冒頭の `description: Next.js has built-in support for internationalized routing and language detection. Learn more here.` は、
[原文](https://nextjs.org/docs/advanced-features/i18n-routing)になかったので割愛しましたが、必要であれば翻訳するので、その場合はその旨お伝えいただければと思います！

2021-01-28 06:22 UTC, yokinist commented
ページをシェアした際にog:descriptionとして表示されるので、`description` も翻訳いただけると嬉しいです 🙇‍♂️
(最初はなかったんですが追加した経緯があります https://github.com/vercel/next.js/pull/18438)

![image](https://user-images.githubusercontent.com/19779874/106098426-5ed83a00-617c-11eb-8cab-4187cce5d469.png)

2021-01-28 14:43 UTC, kei178 commented
承知致しました！のちほど、description の部分も翻訳させていただきます！

2021-01-28 15:19 UTC, kei178 commented
description の翻訳が完了しました！

"built-in support" の翻訳を迷っていましたが、「CSS のビルトインサポート」や「環境変数」の章でそのまま「ビルトインサポート」と訳されていたので、そちらを踏襲させていただきました。初見だと迷ってしまったので、[用語集](https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/blob/master/styleguide.md#%E7%94%A8%E8%AA%9E%E9%9B%86)に追加されるのもよいかもしれません。

2021-02-04 03:04 UTC, hiro08gh commented
翻訳していただきありがとうございます！レビュー開始まで少々お待ちください。

2021-02-20 15:26 UTC, Shinyaigeek requested changes
翻訳ありがとうございます！:pray:
いい訳が多くだいたい良かったですが、少しだけ指摘、コメントさせていただいているのでお手すきの時に確認お願いします 🙏

2021-02-20 15:26 UTC, Shinyaigeek commented on docs/advanced-features/i18n-routing.md
> +一般的にロケール識別子は、ダッシュ区切りの言語、地域、スクリプトで構成されます: `language-region-script`。地域とスクリプトは任意項目です。例としては、以下のようになります:
```suggestion
一般的にロケール識別子は、ダッシュ区切りの言語、地域、スクリプトで構成されます: `言語-地域-スクリプト`。地域とスクリプトは任意項目です。例としては、以下のようになります:
```

2021-02-20 15:26 UTC, Shinyaigeek commented on docs/advanced-features/i18n-routing.md
> +Next.js はページの複数バージョンについて把握していないので、`next/head` を使って `hreflang` メタタグを追加するかどうかは実装次第です。`hreflang` の詳細については [Google Webmasters ドキュメント](https://support.google.com/webmasters/answer/189077)を参照してください。
"it's up to you" の部分, 直訳で「あなた次第です」と訳してもいいかなと感じましたが, 「実装次第」と訳すに至った背景などあればお聞きしたいです 🙏

2021-02-22 16:03 UTC, kei178 commented on docs/advanced-features/i18n-routing.md
> +一般的にロケール識別子は、ダッシュ区切りの言語、地域、スクリプトで構成されます: `language-region-script`。地域とスクリプトは任意項目です。例としては、以下のようになります:
コードブロック内の翻訳漏れなので、ご提案いただいた内容で修正させていただきたいと思います 🙇‍♂️

2021-02-22 16:31 UTC, kei178 commented on docs/advanced-features/i18n-routing.md
> +Next.js はページの複数バージョンについて把握していないので、`next/head` を使って `hreflang` メタタグを追加するかどうかは実装次第です。`hreflang` の詳細については [Google Webmasters ドキュメント](https://support.google.com/webmasters/answer/189077)を参照してください。
この翻訳は迷ったところです。

全体を通して一人称「あなた (you)」を省略して翻訳しているので、この文章で「あなた次第」が出てくると、直訳感があると個人的に思いました。また、「あなた次第」という言い回し自体、英語の「It's up to you」と比べると利用シーンやニュアンスが異なるように思い、「メタタグを追加するかどうかはあなた次第です。」だと、文として少し突き放したような印象になってしまうような気がしました（こちらも個人的な感覚ですが）。そのため、代替的な表現として「実装次第」と訳しています。

直訳でも問題なければ、普通に「あなた次第」で良いと思います 👍

2021-03-15 07:04 UTC, Shinyaigeek commented on docs/advanced-features/i18n-routing.md
> +Next.js はページの複数バージョンについて把握していないので、`next/head` を使って `hreflang` メタタグを追加するかどうかは実装次第です。`hreflang` の詳細については [Google Webmasters ドキュメント](https://support.google.com/webmasters/answer/189077)を参照してください。
なるほど！納得しました！

文脈的にも「実装次第」という訳でも通るというのと, 「あなた次第」という直訳だと確かに直訳感が拭えない, 突き放した印象が出てしまうというのも理解できるのでこの「実装次第」という訳でもいいと感じました！

ありがとうございます 🙏

2021-03-15 07:05 UTC, Shinyaigeek approved these changes
LGTM!ありがとうございます 🙏

2022-02-10 12:19 UTC, Shinyaigeek commented
大変遅れました 🙏  マージします！

2022-02-10 12:19 UTC, merged