docs: translate docs/basic-features/pages.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #24
Opened 2020-07-16 00:17 UTC by hoosan

pages.mdを翻訳しました。ご確認お願いします。

2020-07-16 03:10 UTC, hiro08gh commented
ありがとうございます！レビュー致しますので少々お待ちください。

2020-07-17 04:24 UTC, Shinyaigeek commented
@all-contributors add @hoosan for translation

2020-07-17 05:09 UTC, Shinyaigeek requested changes
PRありがとうございます 🙏 

いくつか, コメント, Request Changesしましたので, 確認よろしくお願いします！(Request Changes等については, 考えがあればコメントしてください！)

2020-07-17 05:09 UTC, Shinyaigeek commented on docs/basic-features/pages.md
> +プリレンダリングすることで結果的にパフォーマンスとSEOが優れます。
```suggestion
プリレンダリングは優れたパフォーマンスとSEOをもたらします。
```

2020-07-17 05:09 UTC, Shinyaigeek commented on docs/basic-features/pages.md
> +プリレンダリング時にデータを取得するために、Next.jsでは`getStaticProps`と呼ばれる`async`関数をファイルから`export`します。
```suggestion
プリレンダリング時にデータを取得するために、Next.jsでは`getStaticProps`と呼ばれる`async`関数を同じファイルから`export`します。
```

コンポーネントを定義するファイルと同じファイルからexportしておくというニュアンスが抜けてた気がしたので

2020-07-17 05:09 UTC, Shinyaigeek commented on docs/basic-features/pages.md
> +この関数はビルド時に呼ばれ、取得されたデータをページの`props`に渡します。
```suggestion
この関数はビルド時に呼ばれ、取得されたデータをページのプリレンダリング時の`props`に渡します。
```

プリレンダリング時のpropsであることは明記しておいたほうがいいと思いました

2020-07-17 05:09 UTC, Shinyaigeek commented on docs/basic-features/pages.md
> +つまり、プリレンダリングするページの**パス**は外部のデータに依存します。このような処理を行うために、Next.jsでは`getStaticPaths`という`async`関数を`export`します。（今回の場合、`pages/posts/[id].js`に追加します。）
```suggestion
つまり、プリレンダリングするページの**パス**は外部のデータに依存します。外部データに依存するパスを扱うために、Next.jsでは`getStaticPaths`という`async`関数を`export`します。（今回の場合、`pages/posts/[id].js`に追加します。）
```

`getStaticPaths` は外部データに依存するパスを取得し扱うという感じの方が正しいかなと思いました.
「このようなパスを扱う」としてもよかったですが, 少し不明瞭かなとも思いthisの中身を展開してあげた方が親切と思いましたがどうでしょうか？

2020-07-17 05:09 UTC, Shinyaigeek commented on docs/basic-features/pages.md
> +（データ取得の有無に関わらず）可能な限り**静的生成**を行い、ビルドしてCDNによって配信することを推奨しています。
```suggestion
ページは一度だけビルドしてしまえばCDNによって配信できるので、（データ取得の有無に関わらず）可能な限り**静的生成**を行うことを推奨しています。
```

because感を出した方がいいように思えましたがどうでしょうか？

2020-07-17 05:09 UTC, Shinyaigeek commented on docs/basic-features/pages.md
> +例えば、ページの表示に用いるデータ（外部のAPIから取得する）が頻繁に更新される場合を考えましょう。この場合、`getServerSideProps`を追加することで、データを取得して`Page`に渡す処理を行うことができます。
```suggestion
例えば、ページの表示に用いるデータ（外部のAPIから取得する）が頻繁に更新される場合を考えましょう。この場合、以下のように`getServerSideProps`を追加することで、データを取得して`Page`に渡す処理を行うことができます。
```

2020-07-17 05:09 UTC, Shinyaigeek commented on docs/basic-features/pages.md
> +`getServerSideProps`は`getStaticProps`とよく似ています。両者の違いは、`getServerSideProps`がビルド時ではなくリクエストの度に呼ばれることです。
```suggestion
見ての通り、`getServerSideProps`は`getStaticProps`とよく似ています。両者の違いは、`getServerSideProps`がビルド時ではなくリクエストの度に呼ばれることです。
```

2020-07-17 05:09 UTC, Shinyaigeek commented on docs/basic-features/pages.md
> +静的生成では、ページの内容を`export`するか、`getStaticProps`（必要であれば`getStaticProps`も）を`export`してください。
```suggestion
静的生成では、ページの内容を`export`するか、`getStaticProps`（必要であれば`getStaticPaths`も）を`export`してください。
ユーザーからのリクエストの前に, ページをプリレンダリングできるということは素晴らしいことです。クライアントサイドレンダリングと併用することで、追加のデータもレンダリングすることができます。
```

2020-07-17 12:55 UTC, hoosan commented
レビューありがとうございます🙏
Request changes確認し、反映いたしました。

2020-07-17 16:25 UTC, Shinyaigeek submitted a review, later dismissed
ありがとうございます！
LGTMです 👍

2020-07-18 00:49 UTC, hiro08gh reviewed
一点だけ、Okumuraさんの翻訳と統一するため修正を入れました。確認お願いします。

2020-07-18 00:49 UTC, hiro08gh commented on docs/basic-features/pages.md
> +> このドキュメントはNext.jsバージョン9.3以上を想定しています。
```suggestion
> このドキュメントは、Next.jsバージョン9.3以上を対象としています
```

2020-07-18 00:49 UTC, hiro08gh commented on docs/basic-features/pages.md
> +もし古いバージョンのNext.jsを使用する場合、[過去のドキュメント](https://nextjs.org/docs/tag/v9.2.2/basic-features/pages)を参照してください。
```suggestion
古いバージョンのNext.jsを使用する場合は、[過去のドキュメント](https://nextjs.org/docs/tag/v9.2.2/basic-features/pages)を参照してください。
```

2020-07-18 02:53 UTC, hoosan commented
修正しましたのでご確認お願いします！
また、冗長表現になっていた「生成を行う」と「することができます」について表記を簡潔にしました。

2020-07-18 03:17 UTC, hiro08gh approved these changes

2020-07-18 03:17 UTC, merged