docs: translate docs/basic-features/typescript.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #30
Opened 2020-07-17 13:23 UTC by ria3100

docs/basic-features/typescript.md 翻訳しました。
レビューよろしくお願いします。

2020-07-17 13:37 UTC, hiro08gh commented
翻訳していただきありがとうございます！レビューしますので、お待ちください。

2020-07-17 15:00 UTC, hoosan requested changes

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +description: Next.jsはデフォルトでTypeScriptをサポートし、ページとAPIの型を備えています。ここではTypeScriptでNext.jsを使い始めることができます。
```suggestion
description: Next.jsは標準でTypeScriptをサポートし、ページとAPIに対してビルトインの型を備えています。ここではNext.jsでTypeScriptを使い始めることができます。
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +description: Next.jsはデフォルトでTypeScriptをサポートし、ページとAPIの型を備えています。ここではTypeScriptでNext.jsを使い始めることができます。
ビルトインを訳に含めました。また、"get started with TypeScript"とあるので、「TypeScriptを使い始める」に修正しました。

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +Next.jsは、IDEのように統合された[TypeScript](https://www.typescriptlang.org/)体験を提供します。
```suggestion
Next.jsは、IDEのように統合された革新的な[TypeScript](https://www.typescriptlang.org/)体験を提供します。
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +Next.jsは、IDEのように統合された[TypeScript](https://www.typescriptlang.org/)体験を提供します。
"out of the box"を訳に含めました。

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +はじめに、プロジェクトルートに空ファイル`tsconfig.json`を作成します。
```suggestion
はじめに、プロジェクトのルートに空の`tsconfig.json`ファイルを作成します。
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +> Next.jsはBabelを使用してTypeScriptを処理しますがいくつかの注意点があり、一部のコンパイラオプションは異なる方法で処理されます。
```suggestion
> Next.jsはTypeScriptを処理するためにBabelを用いますが、いくつかの[注意点](https://babeljs.io/docs/en/babel-plugin-transform-typescript#caveats)があり、一部の[コンパイラオプションの挙動が異なります](https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options)。
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +> Next.jsはBabelを使用してTypeScriptを処理しますがいくつかの注意点があり、一部のコンパイラオプションは異なる方法で処理されます。
リンクを含めました。

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +次に、`next`（通常は`npm run dev`）を実行すると、Next.jsが必要なパッケージのインストールを案内し、セットアップを完了します。
```suggestion
次に、`next`（通常は`npm run dev`）を実行すると、セットアップのためにNext.jsが必要なパッケージのインストールを案内します。
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +# 次のような手順が表示されます。
```suggestion
# 次のような指示が表示されます。
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +これで、ファイルを`.js`から`.tsx`に変換し、TypeScriptの利点を活用する準備が整いました。
```suggestion
これで、ファイルを`.js`から`.tsx`に変換し、TypeScriptの利点を活用する準備が整いました！
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +> このファイルにより、TypeScriptコンパイラによってNext.jsが確実に取得されます。**削除することはできません**が、編集することはできます（ただし、必須ではありません）。
```suggestion
> このファイルにより、TypeScriptコンパイラによってNext.jsの型が確実に取得されます。このファイルを**削除することはできません**が、編集することはできます（ただし、必須ではありません）。
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +> このファイルにより、TypeScriptコンパイラによってNext.jsが確実に取得されます。**削除することはできません**が、編集することはできます（ただし、必須ではありません）。
Next.js typesを訳に含めるのと、itを展開しました。

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
```suggestion
デフォルトでは、Next.jsはアクティブに開発に取り組んでいるページに対してTypeScriptのエラーを報告します。アクティブでないページに対するTypeScriptのエラーは開発工程を邪魔**しません**。
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +エラーを無視にする場合は、[TypeScriptのエラーを無視する](/docs/api-reference/next.config.js/ignoring-typescript-errors.md)に関するドキュメントを参照してください。
```suggestion
エラー報告を静かにさせたい場合は、[TypeScriptのエラーを無視する](/docs/api-reference/next.config.js/ignoring-typescript-errors.md)ためのドキュメントを参照してください。
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +`getStaticProps`、`getStaticPaths`、`getServerSideProps`のために、
```suggestion
`getStaticProps`、`getStaticPaths`、`getServerSideProps`に対して、
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +> `getInitialProps`を使用している場合は、[このページ](/docs/api-reference/data-fetching/getInitialProps.md#typescript)の指示に従ってください。
```suggestion
> `getInitialProps`を使用している場合は、[このページの指示に従って](/docs/api-reference/data-fetching/getInitialProps.md#typescript)ください。
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +## APIのルーティング
```suggestion
## APIルート
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +以下は、APIルーティングに型を使用する方法の例です。
```suggestion
以下は、APIルートにビルトインの型を使用する方法の例です。
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +レスポンスデータに型を指定できます。
```suggestion
レスポンスデータにも型を指定できます。
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +レスポンスデータに型を指定できます。
alsoのニュアンスを加えました。

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +[カスタム`App`](/docs/advanced-features/custom-app)がある場合は、`AppProps`型を使用して、ファイル名を`./pages/_app.tsx`に変更できます。
```suggestion
[カスタム`App`](/docs/advanced-features/custom-app)がある場合は、ビルトインの`AppProps`型を使用して、ファイル名を`./pages/_app.tsx`に変更できます。
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +## PathエイリアスとbaseUrl
```suggestion
## PathのエイリアスとbaseUrl
```

2020-07-17 15:00 UTC, hoosan commented on docs/basic-features/typescript.md
> +## PathエイリアスとbaseUrl
「Pathエイリアス」に若干違和感を感じたので、「の」を入れて柔らかい表現にしました。

2020-07-17 15:02 UTC, hoosan commented
PRありがとうございます ！🙏

いくつかRequest Changesしましたので、ご確認よろしくお願いします！
不明点ございましたらコメントいただければ幸いです！

2020-07-17 15:45 UTC, ria3100 commented
レビューありがとうございます！確認して取り込みましたっ！

2020-07-17 16:00 UTC, ria3100 commented
レビューありがとうございます、確認して取り込みました！

省略表示になってて見逃した分を取り込んで force-push したんですがログにそのまま出てしまうんですね。
ちょっと見づらいですがすいません。

2020-07-17 16:36 UTC, Shinyaigeek commented
@all-contributors add @ria3100 for translation

2020-07-17 16:52 UTC, hiro08gh commented
一点だけ、:で統一でお願いします！事前に書いておかなくてすみません！

2020-07-18 00:11 UTC, ria3100 commented
すみません、何度か読み返してみたのですがどの部分のことなのか分からなくて
お手数おかけしますがどの部分か教えていただければ・・・。

2020-07-18 00:35 UTC, hiro08gh commented on docs/basic-features/typescript.md
> +はじめに、プロジェクトのルートに空の`tsconfig.json`ファイルを作成します。
```suggestion
はじめに、プロジェクトのルートに空の`tsconfig.json`ファイルを作成します:
```

2020-07-18 00:35 UTC, hiro08gh commented on docs/basic-features/typescript.md
> +次に、`next`（通常は`npm run dev`）を実行すると、セットアップのためにNext.jsが必要なパッケージのインストールを案内します。
```suggestion
次に、`next`（通常は`npm run dev`）を実行すると、セットアップのためにNext.jsが必要なパッケージのインストールを案内します:
```

2020-07-18 00:35 UTC, hiro08gh commented on docs/basic-features/typescript.md
> +# 次のような指示が表示されます。
```suggestion
# 次のような指示が表示されます:
```

2020-07-18 00:35 UTC, hiro08gh commented on docs/basic-features/typescript.md
> +以下は、APIルートにビルトインの型を使用する方法の例です。
```suggestion
以下は、APIルートにビルトインの型を使用する方法の例です:
```

2020-07-18 00:35 UTC, hiro08gh commented on docs/basic-features/typescript.md
> +レスポンスデータにも型を指定できます。
```suggestion
レスポンスデータにも型を指定できます:
```

2020-07-18 00:35 UTC, hiro08gh commented on docs/basic-features/typescript.md
> +[カスタム`App`](/docs/advanced-features/custom-app)がある場合は、ビルトインの`AppProps`型を使用して、ファイル名を`./pages/_app.tsx`に変更できます。
```suggestion
[カスタム`App`](/docs/advanced-features/custom-app)がある場合は、ビルトインの`AppProps`型を使用して、ファイル名を`./pages/_app.tsx`に変更できます:
```

2020-07-18 00:36 UTC, hiro08gh commented
suggestions忘れてました。申し訳ないです。

2020-07-18 01:08 UTC, ria3100 commented
他のページよく見ておけばよかったですね、すいません。
指摘いただいた箇所修正しました。

2020-07-18 01:17 UTC, hiro08gh commented
ありがとうございます！LGTMです！

2020-07-18 01:17 UTC, hiro08gh approved these changes

2020-07-18 01:57 UTC, hiro08gh approved these changes

2020-07-18 02:59 UTC, hoosan commented
修正いただきありがとうございました🙏
LGTMです！

2020-07-18 02:59 UTC, hoosan approved these changes

2020-07-18 02:59 UTC, merged