docs: translate docs/api-routes/response-helpers.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #31
Opened 2020-07-17 13:39 UTC by 96-38

docs/api-routes/response-helpers.md を翻訳しました。
レビューよろしくお願いします。

2020-07-17 15:05 UTC, hoosan commented
LGTMです！

2020-07-17 16:18 UTC, Shinyaigeek requested changes
with nitsです ！
一箇所コメント, suggestしているので確認お願いします 🙏

2020-07-17 16:18 UTC, Shinyaigeek commented on docs/api-routes/response-helpers.md
> +レスポンス (`res`) には、Express.jsライクなメソッドのセットが用意されています。これらは、より良い開発者体験を提供し、より高速なAPIエンドポイントの作成に役立ちます。次の例を見てみましょう。
```suggestion
レスポンス (`res`) には、Express.jsライクなメソッドのセットが用意されています。これらは、より良い開発者体験を提供し、より手早くAPIエンドポイントを作成できます。次の例を見てみましょう。
```

こちら, `高速な` がAPIにかかっているのか作成にかかっているのか不明瞭な気がしたのでこうしてみましたが, どうでしょうか？

2020-07-17 16:18 UTC, Shinyaigeek commented
@all-contributors add @96-38 for translation

2020-07-17 16:19 UTC, Shinyaigeek commented
@all-contributors add @hoosan for review

2020-07-17 17:33 UTC, 96-38 commented on docs/api-routes/response-helpers.md
> +レスポンス (`res`) には、Express.jsライクなメソッドのセットが用意されています。これらは、より良い開発者体験を提供し、より高速なAPIエンドポイントの作成に役立ちます。次の例を見てみましょう。
レビューありがとうございます！
確かにそうですね。変更提案ありがとうございます。
変更を取り込んだのでご確認お願いします:pray:

2020-07-18 04:17 UTC, hiro08gh approved these changes

2020-07-18 08:58 UTC, Shinyaigeek approved these changes
LGTM です 👍

2020-07-18 09:10 UTC, merged