docs: translate docs/advanced-features/module-path-aliases.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #37
Opened 2020-07-17 14:20 UTC by noriaki

`docs/advanced-features/module-path-aliases.md`を翻訳しました。
少し意訳していますが開発者目線で書いています。

2020-07-17 14:29 UTC, hiro08gh commented
ありがとうございます！順次、レビューいたしますのでお待ちください。

2020-07-17 16:40 UTC, Shinyaigeek commented
@all-contributors add @noriaki for translation

2020-07-17 16:53 UTC, Shinyaigeek requested changes
PR ありがとうございます！

いくつかコメント残しましたので, 確認お願いします 🙏

2020-07-17 16:53 UTC, Shinyaigeek commented on docs/advanced-features/module-path-aliases.md
> +これらのオプションを設定すると、VSCodeなど特定のエディタは自動的に読み取り、補完を受けられるなど使い勝手が良くなります。
```suggestion
これらのオプションを設定すると、vscodeなど特定のエディタは自動的に読み取り、補完を受けられるなど使い勝手が良くなります。
```

`VSCode` は原文に合わせて `vscode` でお願いします 🙏

2020-07-17 16:53 UTC, Shinyaigeek commented on docs/advanced-features/module-path-aliases.md
> +import Button from 'components/button'; // <- not '../components/button';
```suggestion
import Button from 'components/button';
```

この追記があったほうがわかりやすいと僕も感じますが, 一応原文に合わせ抜いてもらってよろしいでしょうか？すみません...:pray:

2020-07-17 16:53 UTC, Shinyaigeek commented on docs/advanced-features/module-path-aliases.md
> +これらのオプションを設定するだけで、自動的にモジュール読み込みパスのエイリアス設定を利用できます。よくあるパターンとしては、特定のディレクトリパスへエイリアスを設定し、そこに存在するモジュールを相対パスではなく絶対パスでインポートするような使い方です。
```suggestion
これらのオプションによって、モジュール読み込みパスのエイリアスを設定できます。よくあるパターンとしては、特定のディレクトリパスへエイリアスを設定し、そこに存在するモジュールを相対パスではなく絶対パスでインポートするような使い方です。
```

細かいですが, オプションを設定するだけで〜〜というよりも, オプションで〜〜が設定できるとした方が直接的でわかりやすいかなと思いましたがどうでしょうか？

2020-07-18 02:25 UTC, noriaki commented
コメントありがとうございますー
夜に確認しますねー

2020-07-18 03:39 UTC, hoosan requested changes

2020-07-18 03:39 UTC, hoosan commented on docs/advanced-features/module-path-aliases.md
> +description: 特定のモジュール読み込みパスをコンパイル時にエイリアスとして解釈するよう設定できます
```suggestion
description: 特定のモジュール読み込みパスをコンパイル時にエイリアスとして解釈するよう設定できます。
```
細かくて恐縮ですが、原文にピリオドが含まれますので句点の追加をお願いします🙏

2020-07-18 03:39 UTC, hoosan commented on docs/advanced-features/module-path-aliases.md
>  // tsconfig.json or jsconfig.json
```suggestion
// tsconfig.json か jsconfig.json
```
コードブロック内はコメントを訳して頂けますと嬉しいです🙏（下にもう一箇所あります）

2020-07-18 14:25 UTC, noriaki commented on docs/advanced-features/module-path-aliases.md
>  // tsconfig.json or jsconfig.json
`or`に対して`または`を使用して翻訳追加しました

2020-07-18 14:33 UTC, noriaki commented
レビューコメントを反映しました。
GitHubのレビューに不慣れでして、コメントを`resolve`にしてしまったのですが適切な対応かどうか自信がないです。必要な手順あればアドバイスください

2020-07-18 23:48 UTC, hoosan requested changes
対応いただきありがとうございます！LGTMです！
細かい点ですが、統一の観点からコロンを使用することになりましたので、
そのご対応をいただければと思います！よろしくお願いします🙏

2020-07-18 23:48 UTC, hoosan commented on docs/advanced-features/module-path-aliases.md
>  この場合のサンプルコードは以下の通りです。
```suggestion
この場合のサンプルコードは以下の通りです:
```
追加で申し訳ございません！こちら、コロン":"に統一させて頂けますでしょうか🙏

2020-07-18 23:48 UTC, hoosan commented on docs/advanced-features/module-path-aliases.md
>  この場合のサンプルコードは以下の通りです。
```suggestion
この場合のサンプルコードは以下の通りです:
```
こちらも同様です🙏

2020-07-19 14:08 UTC, hiro08gh commented
確認しました。LGTMです！

2020-07-19 14:08 UTC, hiro08gh approved these changes

2020-07-19 14:08 UTC, hoosan approved these changes
ご対応ありがとうございました！！LGTMです！

2020-07-20 10:17 UTC, Shinyaigeek approved these changes
対応ありがとうございます！LGTMです :+1:

2020-07-20 10:18 UTC, merged