docs: translate docs/api-routes/introduction.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #46
Opened 2020-07-18 02:20 UTC by syakoo

docs/api-routes/introduction.mdを翻訳しました。
レビュー宜しくお願い致します。

2020-07-18 04:05 UTC, hoosan requested changes
翻訳いただきありがとうございます！！
いくつかRequest changesしましたのでご確認ください🙏

2020-07-18 04:05 UTC, hoosan commented on docs/api-routes/introduction.md
> +すべての`pages/api`フォルダ内にあるファイルは`/api/*`にマッピングされ、`page`の代わりにAPI エンドポイントとして扱われます。
```suggestion
`pages/api`フォルダ内にあるすべてのファイルは`/api/*`にマッピングされ、`page`の代わりにAPI エンドポイントとして扱われます。
```
細かいですが、「すべての」が係る言葉が曖昧に感じました。ご確認お願いします🙏

2020-07-18 04:05 UTC, hoosan commented on docs/api-routes/introduction.md
> +API エンドポイントを取得するには、このセクションの最初にある例を見てください。
```suggestion
API エンドポイントを取得するには、このセクションの最初にある例のどれかをご覧ください。
```
"any of"のニュアンスを加えました！

2020-07-18 04:05 UTC, hoosan commented on docs/api-routes/introduction.md
> +> API ルートは[CORSヘッダーを指定しません](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)。つまり、標準では**同一オリジンのみ**となります。[cors ミドルウェア](/docs/api-routes/api-middlewares.md#connectexpress-middleware-support)でリクエス
```suggestion
> API ルートは[CORSヘッダーを指定しません](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)。つまり、標準では**同一オリジンのみ**となります。[cors ミドルウェア](/docs/api-routes/api-middlewares.md#connectexpress-middleware-support)でリクエストハンドラをラップすることで挙動をカスタマイズすることができます。
```
"behavior"のニュアンスを加えました！

2020-07-18 05:00 UTC, syakoo commented
確認しました。添削ありがとうございます！

2020-07-18 05:22 UTC, hoosan approved these changes

2020-07-18 05:23 UTC, hoosan commented
ありがとうございます！LGTMです！👍

2020-07-18 09:11 UTC, Shinyaigeek approved these changes
ありがとうございます！ LGTMです 👍

2020-07-18 09:38 UTC, merged

2020-07-19 03:14 UTC, Shinyaigeek commented
@all-contributors add @syakoo for translation