docs: translate docs/advanced-features/automatic-static-optimization.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #47
Opened 2020-07-18 07:39 UTC by hoosan

`docs/advanced-features/automatic-static-optimization.md`を翻訳いたしました。

タイトルのAutomatic Static Optimizationを直訳すると「自動静的最適化」になるかと思いますが、
- textlintの連続漢字数の制限
- [docs/routing/dynamic-routes.mdの翻訳](https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/blob/master/docs/routing/dynamic-routes.md)では原文の"Automatic Static Optimization"のまま

以上の2点の理由から原文の"Automatic Static Optimization"としています。

2020-07-18 09:19 UTC, Shinyaigeek requested changes
ありがとうございます！一点気になるところがあったので確認お願いします 🙏

2020-07-18 09:19 UTC, Shinyaigeek commented on docs/advanced-features/automatic-static-optimization.md
> +ページがノンブロッキングなデータを必要としなければ、Next.jsはそのページが静的（プリレンダリングが可能）であると自動的に判断します。
```suggestion
ページが同期的にデータを要求しないのであれば、Next.jsはそのページが静的（プリレンダリングが可能）であると自動的に判断します。
```

noはrequirementsにかかってるのかと思います！ この場合, SSGされる条件についての分で, これはつまりSSRの必要がない, つまりデータセンターのものと同期的なデータを必要としないみたいな感じかと思いましたがどうでしょうか？

2020-07-18 09:57 UTC, hoosan commented on docs/advanced-features/automatic-static-optimization.md
> +ページがノンブロッキングなデータを必要としなければ、Next.jsはそのページが静的（プリレンダリングが可能）であると自動的に判断します。
ご指摘ありがとうございます🙏　間違い大変失礼いたしました💦
修正いたしましたのでご確認ください！（lintに引っかかったので後半の文章を少し修正しています）

2020-07-18 13:23 UTC, Shinyaigeek submitted a review, later dismissed
変更ありがとうございます 🙏  LGTMです :+1:

2020-07-19 00:58 UTC, hoosan commented
レビューありがとうございます！
訳語の統一の観点と、[スタイルガイド](https://github.com/gatsbyjs/gatsby-ja/blob/master/style-guide.md)の記載事項により、以下の2点の修正を行いました！

- Caveats の訳を「注意事項」に変更
- 半角と全角が切り替わる箇所にスペースをいれる

大変お手数ですが再度ご確認いただけますでしょうか🙏

2020-07-19 07:23 UTC, hiro08gh commented
確認しました！LGTMです！

2020-07-19 07:24 UTC, hiro08gh approved these changes

2020-07-19 07:25 UTC, Shinyaigeek approved these changes
確認しました！ありがとうございます！
LGTMです :+1:

2020-07-19 07:26 UTC, merged