docs: translate docs/basic-features/static-file-serving.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #51
Opened 2020-07-18 11:13 UTC by hiro08gh

docs/basic-features/static-file-serving.mdを翻訳しました。

ブランチ名間違えてすみません。レビューお願いします。

2020-07-18 13:29 UTC, thesugar requested changes
ありがとうございます！！
LGTM with nits です。よろしくお願いします :octocat:

2020-07-18 13:29 UTC, thesugar commented on docs/basic-features/static-file-serving.md
> +`public`内のファイルは、ベースURL(/)から始まるコードで参照できます。
```suggestion
Next.jsは、ルートディレクトリの`public`フォルダ下で、画像などの静的ファイルを配信できます。
`public`内のファイルは、ベースURL(`/`)から始まるコードで参照できます。
```

2020-07-18 13:29 UTC, thesugar commented on docs/basic-features/static-file-serving.md
> +例えば、`public/my-image.png`に画像を追加場合、次のコードで画像にアクセスします:
```suggestion
例えば、`public/my-image.png`に画像を追加した場合、次のコードで画像にアクセスします:
```

2020-07-18 13:29 UTC, thesugar commented on docs/basic-features/static-file-serving.md
> +このフォルダは、Googleのサイト検証、robots.txtや他の静的ファイル(.htmlを含む)にも役立ちます！
Google Site Verification は、固有名詞的に書かれていることからも [例えばこのページ](https://support.google.com/webmasters/answer/79812?hl=ja) などに説明のある google-site-verification タグ（にまつわる挙動）のことを言っているものと思われるため、「Googleのサイト検証」と日本語にせず「Google Site Verification」とそのまま英語で表記してしまってもいいのかな、と思ったりもします。が、あまり強いこだわりはないので、かみむらさん始め皆さんの好み/方針に従います！

2020-07-18 13:31 UTC, hiro08gh commented
thesugarさんありがとうございます！！！修正しますね！

2020-07-18 13:49 UTC, hiro08gh commented on docs/basic-features/static-file-serving.md
> +このフォルダは、Googleのサイト検証、robots.txtや他の静的ファイル(.htmlを含む)にも役立ちます！
迷ったんですが、自分も英語の固有名詞がいいと思いました。なので、Google  Site Verificationにします！

2020-07-19 01:14 UTC, hiro08gh commented on docs/basic-features/static-file-serving.md
> +`public`内のファイルは、ベースURL(/)から始まるコードで参照できます。
修正しました。

2020-07-19 01:14 UTC, hiro08gh commented on docs/basic-features/static-file-serving.md
> +例えば、`public/my-image.png`に画像を追加場合、次のコードで画像にアクセスします:
修正しました。

2020-07-19 01:14 UTC, hiro08gh commented on docs/basic-features/static-file-serving.md
> +このフォルダは、Googleのサイト検証、robots.txtや他の静的ファイル(.htmlを含む)にも役立ちます！
Google Site Verificationに修正しました。

2020-07-19 01:14 UTC, hiro08gh commented
遅くなってすみません。修正しましたので、確認お願いします。

2020-07-19 04:03 UTC, thesugar submitted a review, later dismissed

2020-07-19 04:03 UTC, thesugar commented
ご対応ありがとうございます！LGTMです 😄

2020-07-19 13:41 UTC, hoosan requested changes
LGTM with nitsです！アルファベットと日本語の切り替え位置に半角スペースを入れていただければと思います🙏

2020-07-19 13:41 UTC, hoosan commented on docs/basic-features/static-file-serving.md
> +Next.jsは、ルートディレクトリの`public`フォルダ下で、画像などの静的ファイルを配信できます。
```suggestion
Next.js は、ルートディレクトリの `public` フォルダ下で、画像などの静的ファイルを配信できます。
```

2020-07-19 13:54 UTC, hoosan requested changes
気づいたところだけRequestChanges送っておきます！

2020-07-19 13:54 UTC, hoosan commented on docs/basic-features/static-file-serving.md
> +`public` 内のファイルは、ベースURL(`/`)から始まるコードで参照できます。
```suggestion
`public` 内のファイルは、ベース URL （ `/` ）から始まるコードで参照できます。
```

2020-07-19 13:54 UTC, hoosan commented on docs/basic-features/static-file-serving.md
> +このフォルダは、 Google Site Verification、 robots.txt や他の静的ファイル(.htmlを含む)にも役立ちます！
```suggestion
このフォルダは、 Google Site Verification、 robots.txt や他の静的ファイル（ .html を含む）にも役立ちます！
```

2020-07-19 13:55 UTC, hoosan approved these changes

2020-07-19 13:59 UTC, hoosan approved these changes

2020-07-19 14:01 UTC, hiro08gh commented
修正しました。半角と全角のスペース切り替えはtextlintあたりで設定が必要そうです。一旦Approveお願いします。

2020-07-19 19:07 UTC, yokinist approved these changes
ありがとうございます！
スペース系は #74 マージ後にまとめて対応しようと思います

2020-07-20 00:19 UTC, merged