docs: translate docs/basic-features/built-in-css-support.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #52
Opened 2020-07-18 16:52 UTC by ogugu9

`docs/basic-features/built-in-css-support.md` を翻訳しました。
レビューお願い致します！

lintの設定に関わりそうなところ
- `()` は半角のままでよいか
- `""` は `「」` などに変えたほうがよいか

あえて英語表記のまま残したところ
- minify
- code-split
- scoped CSS

2020-07-19 05:25 UTC, hiro08gh commented
順次レビューしますので、お待ちください！

2020-07-19 08:46 UTC, hoosan requested changes
かなりの長文を翻訳していただき本当にありがとうございます！！
いくつかコメントしましたので、Request changesをご確認いただますでしょうか🙏

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +これは、 Next.js が JavaScript の範囲を越えて [`import`](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/import) の概念を拡張することで実現しています。
```suggestion
これは、 Next.js が JavaScript の [`import`](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/import) の概念を拡張することで実現しています。
```
「JavaScript の範囲を越えて`import`の概念を拡張する」という部分が少し抽象的に感じました！
原文を「JavaSciprt では不可能なCSSファイルの `import` をNext.js では可能にしている」という意味にとりますと、
「JavaScript の `import` の概念を拡張している」とする方が読みやすいかと思いましたが、いかがでしょうか？

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +スタイルシートを追加するために、 `pages/_app.js` 内で CSS をインポートしてみましょう。
```suggestion
スタイルシートをアプリケーションに追加するために、 `pages/_app.js` 内で CSS ファイルをインポートしてみましょう。
```
細かいですが、"to your application"のニュアンスを加えたのと、
原文が"CSS file"となっておりますので「CSS ファイル」としてみましたがいかがでしょうか？
その他の部分の `pages/_app.js` file という原文については、`.js`によってファイルであることが明らかであるのに対して、CSSは必ずしもファイルを明示的に表していないのではないかと思いました！

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +もし、まだ作成していない場合は、 [`pages/_app.js` ファイル](/docs/advanced-features/custom-app) を作成してください。
```suggestion
もし、まだ作成していない場合は、 [`pages/_app.js`](/docs/advanced-features/custom-app) を作成してください。  
```
その他の部分で"`pages/_app.js` file"のファイルを省略しておりますので、統一してここも省略するのはいかがでしょうか？

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +CSS Modules が、コンポーネントレベル CSS を導入する理想的な方法である理由は、こういった特徴のおかげなのです。
```suggestion
こういった特徴のおかげで、CSS Modules がコンポーネントレベルの CSS を導入するための理想的な方法となっています。
```
主語をCSS moludesにした方がシンプルかと思いましたがいかがでしょうか？

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +CSS Modules は、 **`.module.css` 拡張子ファイルに対してのみ有効**となるオプション機能です。
```suggestion
CSS Modules は、 **`.module.css` 拡張子ファイルに対してのみ有効**となる_オプション機能_です。  
```
原文に合わせて斜体にしました！

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +そして、 上記のCSSファイルをインポートして利用し、 `components/Button.js` を作成します:
```suggestion
そして、 上記の CSS ファイルをインポートして利用し、 `components/Button.js` を作成します:
```
他の部分でも半角スペースを入れてくださっていたので、統一のため追加しました！

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +なお、通常の `<link>` スタイルシートやグローバルCSSファイルもサポートされています。
```suggestion
なお、通常の `<link>` スタイルシートやグローバル CSS ファイルもサポートされています。
```
他の部分も半角スペースを入れてくださっているので、統一のため追加しました！

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +本番環境では、すべての CSS Module ファイルは、 code-split した上で minify された複数の `.css` ファイルへと統合されます。
```suggestion
本番環境では、すべての CSS Module ファイルは**コード分割した上で minify された複数の** `.css` ファイルへと自動的に統合されます。  
```
code-splitはコード分割とするのはいかがでしょうか？また、原文に合わせて太字にし、"automatically"のニュアンスを加えました！

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +Next.js では、 `.scss` あるいは `.sass` といったどちらの拡張子を用いた Sass ファイルでも、インポートできます。
```suggestion
Next.js では、 `.scss` または `.sass` のどちらの拡張子を用いた Sass ファイルでもインポートできます。  
```
「あるいは」を「または」に変更しました！
「といった」は冗長なので無くしても良いと思いましたがいかがでしょうか？

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +CSS Modules によるコンポーネントレベルな Sass は、 `.module.scss` あるいは `.module.sass` といった拡張子で利用できます。
```suggestion
CSS Modules によるコンポーネントレベルの Sass を、 `.module.scss` または `.module.sass` の拡張子で利用できます。
```
こちらも上と同様です！

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +Sass サポートには、前節で詳説した CSS ビルトインサポートと同様な恩恵および制限があります。
```suggestion
Sass サポートには、前節で詳説した CSS ビルトインサポートと同様の恩恵と制限があります。
```
およびが少し冗長に感じましたがいかがでしょう？

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +単純なインラインスタイルの一例としては、次のようになります:
```suggestion
最も単純なのは、インラインスタイルを用いる方法です:
```
"simplest one is .."とありますので、"CSS-in-JS" のうち最も単純なものはインラインスタイルであるという意味に捉えるのが良いかと思いましたがいかがでしょう？

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +分離された scoped CSS を提供するために、 Next.js では [styled-jsx](https://github.com/zeit/styled-jsx) を付属しています。
```suggestion
孤立状態にある scoped CSS へのサポートを提供するために、 Next.js では [styled-jsx](https://github.com/zeit/styled-jsx) を付属しています。  
```
Scoped CSSへのサポートがあるということがわかるような文章にしてみました！
また、「分離された scoped CSS」という部分ですが、原文を見ますと"isolated scoped CSS"となっており、
これは文脈的にscoped CSSが[ブラウザで非推奨となっている](https://developer.mozilla.org/ja/docs/Web/HTML/Element/style)ことを指しているのではないかと思います。
ですので「孤立状態にある」としてみましたがいかがでしょうか？

2020-07-19 08:46 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +その目的は、不幸なことに [JSのみでサーバーレンダリングはサポートしていなかった](https://github.com/w3c/webcomponents/issues/71) Web Components によく似た、 "shadow CSS" をサポートすることにあります。
```suggestion
その目的は、残念ながら [サーバーレンダリングをサポートしていない](https://github.com/w3c/webcomponents/issues/71) Web Components に似ている "shadow CSS" をサポートすることにあります。
```
本当はWeb Componentを使いたかったけど残念ながらサーバーレンダリングに対応していないので..という意味かと思いますので、「残念ながら」という訳にしてみました！
また、「よく似た、」と文を区切ってしまうと少し意味が取りにくいかと思い、変更してみましたがいかがでしょう？

2020-07-20 15:29 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +これは、 Next.js が JavaScript の範囲を越えて [`import`](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/import) の概念を拡張することで実現しています。
自分もモヤモヤしながら訳していた部分ですね…
文意も損なわないすっきりした訳ですし、採用させていただきます！

2020-07-20 15:33 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +CSS Modules は、 **`.module.css` 拡張子ファイルに対してのみ有効**となるオプション機能です。
確認漏れでした…取り込みます！

2020-07-20 15:49 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +CSS Modules が、コンポーネントレベル CSS を導入する理想的な方法である理由は、こういった特徴のおかげなのです。
```suggestion
こういった特徴のおかげで、CSS Modules はコンポーネントレベルの CSS を導入するための理想的な方法となっています。
```
やや細かいですが、一般に助詞「が」だと他の選択肢を潰すようなニュアンスが入ってくるように感じました。

原文は最上級や比較級を用いていないので、そういったニュアンスはなさそうでしたので、単に主題を表す助詞「は」に変更してみましたが、いかがでしょうか…？

（`the ideal way`の`the`がやや最上級っぽいニュアンスを感じますが…）

2020-07-20 15:50 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +そして、 上記のCSSファイルをインポートして利用し、 `components/Button.js` を作成します:
確認漏れでした…取り込みます！

2020-07-20 15:50 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +なお、通常の `<link>` スタイルシートやグローバルCSSファイルもサポートされています。
確認漏れでした…取り込みます！

2020-07-20 15:51 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +本番環境では、すべての CSS Module ファイルは、 code-split した上で minify された複数の `.css` ファイルへと統合されます。
エビデンスを探してみたところ、Reactの日本語ドキュメントが「コード分割」と訳していたため、採用させていただきます！
https://ja.reactjs.org/docs/code-splitting.html

2020-07-20 15:53 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +Next.js では、 `.scss` あるいは `.sass` といったどちらの拡張子を用いた Sass ファイルでも、インポートできます。
ご指摘通りだと思いますので、取り込みます！

2020-07-20 15:53 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +CSS Modules によるコンポーネントレベルな Sass は、 `.module.scss` あるいは `.module.sass` といった拡張子で利用できます。
ご指摘通りだと思いますので、取り込みます！

2020-07-20 15:54 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +Sass サポートには、前節で詳説した CSS ビルトインサポートと同様な恩恵および制限があります。
そちらのほうがシンプルですので採用します！

2020-07-20 15:56 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +単純なインラインスタイルの一例としては、次のようになります:
そちらのほうがシンプルですので採用します！

2020-07-20 16:15 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +分離された scoped CSS を提供するために、 Next.js では [styled-jsx](https://github.com/zeit/styled-jsx) を付属しています。
あーなるほど、自分は `isolated` のニュアンスは `scoped` にかかっていて、「影響が分離されたスコープ」を意味しているのかと解釈しておりました…。

ですが、その場合 `isolatedly` と副詞にするのが適切な気がしますし、前後の文脈から考えてもホーさんの訳が馴染む気がしました。

解釈次第で文意が大きく異なると思うので、一度Slackで他の方の意見も求めてみます！

2020-07-20 16:16 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +その目的は、不幸なことに [JSのみでサーバーレンダリングはサポートしていなかった](https://github.com/w3c/webcomponents/issues/71) Web Components によく似た、 "shadow CSS" をサポートすることにあります。
そちらのほうがナチュラルですので、採用します！

2020-07-20 16:16 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +もし、まだ作成していない場合は、 [`pages/_app.js` ファイル](/docs/advanced-features/custom-app) を作成してください。
ご指摘の通り統一すべきですので、取り込みます！

2020-07-20 16:18 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +スタイルシートを追加するために、 `pages/_app.js` 内で CSS をインポートしてみましょう。
ご指摘の通りですので、採用します！

2020-07-20 16:37 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +スタイルシートをアプリケーションに追加するために、 `pages/_app.js` 内で CSS ファイルをインポートしてみましょう。
```suggestion
スタイルシートをアプリケーションへ追加するために、 `pages/_app.js` 内で CSS ファイルをインポートしてみましょう。
```
ご指摘を取り込んだところ、助詞「に」の重複に引っかかってしまいましたので、このように修正しても良いでしょうか？

2020-07-21 00:01 UTC, Shinyaigeek commented on docs/basic-features/built-in-css-support.md
> +CSS Modules が、コンポーネントレベル CSS を導入する理想的な方法である理由は、こういった特徴のおかげなのです。
**個人的には** 「が」 -> 「は」賛成です！
`the ideal way` もやや最上級ぽいっという感じで, 〜〜は〜〜の理想的な方法くらいの強さが寧ろ適当かと感じました

2020-07-21 00:16 UTC, Shinyaigeek commented on docs/basic-features/built-in-css-support.md
> +分離された scoped CSS を提供するために、 Next.js では [styled-jsx](https://github.com/zeit/styled-jsx) を付属しています。
自分も @ogugu9 さんに近い考えを持ってました. `scoped css`で一つの単語と解釈していて, `isolated` も「他のStyleから分離された, 影響を受けない」くらいのニュアンスとしていました.

@hoosan の意見を見てなるほどなと思う一方, 標準仕様の scoped cssと, 最近よく言う(かつこの場で言及されている)、jsでunique keyを割り当てるscoped cssは似て非なるものだと思っていました(Web新参者なので解釈違いがあるかもですが...)

なので僕はどちらかと言うと「分離された」の方が適しているかもしれないくらいの考えでいます.

2020-07-21 03:18 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +CSS Modules が、コンポーネントレベル CSS を導入する理想的な方法である理由は、こういった特徴のおかげなのです。
なるほどです！個人的に"the ideal way"に唯一の方法という印象を受けてました（最上級では他の選択肢も認識しているけれど、the ideal wayは他を見てすらいないような感じです）。

「が」を「は」にすることで日本語のニュアンスが和らぎますし意味も損ねないので、変更に賛成です！ご提案いただきありがとうございます！

2020-07-21 03:23 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +分離された scoped CSS を提供するために、 Next.js では [styled-jsx](https://github.com/zeit/styled-jsx) を付属しています。
私が解釈間違いだったかもしれません🙏　私の訳だとかなり文意を限定してしまうので、「分離された」にしていただけますでしょうか！><

2020-07-21 08:38 UTC, hoosan commented on docs/basic-features/built-in-css-support.md
> +スタイルシートをアプリケーションに追加するために、 `pages/_app.js` 内で CSS ファイルをインポートしてみましょう。
失礼いたしました🙇‍♂️ 修正よろしくお願いします🙏

2020-07-21 12:34 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +スタイルシートをアプリケーションに追加するために、 `pages/_app.js` 内で CSS ファイルをインポートしてみましょう。
了解しました！

2020-07-21 12:37 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +CSS Modules が、コンポーネントレベル CSS を導入する理想的な方法である理由は、こういった特徴のおかげなのです。
ご意見ありがとうございます、おおむね賛成の意見を頂いてるので取り込みますね！

2020-07-21 12:40 UTC, ogugu9 commented on docs/basic-features/built-in-css-support.md
> +分離された scoped CSS を提供するために、 Next.js では [styled-jsx](https://github.com/zeit/styled-jsx) を付属しています。
かしこまりました！では「孤立状態にある」→「分離された」に戻して修正取り込みます。
```suggestion
分離された scoped CSS へのサポートを提供するために、 Next.js では [styled-jsx](https://github.com/zeit/styled-jsx) を付属しています。  
```

2020-07-21 12:47 UTC, ogugu9 commented
頂いた指摘を一通り取り込みましたので、再度確認お願いしますー！
（lintも通ってます）

2020-07-21 13:59 UTC, hoosan approved these changes
修正いただきありがとうございました！
LGTMです👍

2020-07-21 15:16 UTC, hiro08gh commented
翻訳していただきありがとうございます！LGTMです！

2020-07-21 15:17 UTC, hiro08gh approved these changes

2020-07-21 15:17 UTC, merged

2020-07-23 03:41 UTC, hiro08gh commented
@all-contributors add @ogugu9 for translation