docs: translate docs/deployment.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #62
Opened 2020-07-19 06:25 UTC by YopiNoji

2020-07-19 06:42 UTC, hiro08gh commented
翻訳していただきありがとうございます！順次確認いたしますのでお待ちください。

2020-07-19 11:32 UTC, hiro08gh commented
ja-technical-writing/sentence-lengthを無効化しました。masterブランチに反映してあります！

2020-07-19 12:21 UTC, YopiNoji commented
> ja-technical-writing/sentence-lengthを無効化しました。masterブランチに反映してあります！

対応ありがとうございます！
取り込んだものを再度プッシュいたしました。
レビューお願いいたします:bow:

2020-07-19 14:26 UTC, hoosan requested changes
長文を翻訳していただきありがとうございます！
コメントさせていただきましたのでご確認ください🙏
細かい指摘が多く大変恐縮です🙇‍♂️

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +description: Next.jsアプリをVercelやその他のホスティングオプションを使って本番環境にデプロイします。
```suggestion
description: Next.js アプリを Vercel やその他のホスティング方法を使って本番環境にデプロイします。
```
「ホスティングオプション」についてですが、ここで指しているのは「Vercel以外のホスティング方法（サービス）の選択肢」だと思いますので、単にオプションとしてしまうと「他の方法がある」というニュアンスが弱いと思いました。いかがでしょうか？

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +## Vercel (推奨する方法)
```suggestion
## Vercel (推奨)
```
単に推奨で良いかと思います！

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +はじめに、Next.js アプリを任意の Git プロバイダーにプッシュしてください。[GitHub](http://github.com/)、[GitLab](https://gitlab.com/)、[BitBucket](https://bitbucket.org/)などです。リポジトリはプライベートまたはパブリックでも構いません。
```suggestion
はじめに、Next.js アプリを任意の Git プロバイダーにプッシュしてください。[GitHub](http://github.com/)、[GitLab](https://gitlab.com/)、[BitBucket](https://bitbucket.org/)などです。リポジトリはプライベートとパブリックのどちらでも構いません。
```
「プライベートまたはパブリックでも構いません」という言い回しが気になり修正してみましたがいかがでしょうか？

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +次に、以下の手順に従ってください。
```suggestion
次に、以下の手順に従ってください:
```
記載がなく申し訳ございません🙏　原文にコロンがある場合は訳文もコロンとさせて下さい！

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +1. [Vercelにサインアップする](https://vercel.com/signup) （クレジットカードの登録は不要）
```suggestion
1. [Vercelにサインアップする](https://vercel.com/signup) （クレジットカードの登録は不要）。
```
細かいですが、原文にピリオドがあるので訳文にも句点にも記載することとさせてください！

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +おめでとうございます！Next.jsアプリのデプロイが完了しました。質問がある場合は、[Vercel documentation](https://vercel.com/docs) を参照してください。
```suggestion
おめでとうございます！Next.jsアプリのデプロイが完了しました。疑問点がある場合は、[Vercel documentation](https://vercel.com/docs) を参照してください。
```
質問というと問い合わせを連想させるので、疑問点とするのはどうでしょう？

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +> [Next.js においてカスタマイズされたサーバー設定](/docs/advanced-features/custom-server.md)を使用したい場合は、他への移行を強くお勧めします(例えば、[ダイナミックルーティング](/docs/routing/dynamic-routes.md)を使用するなど)。移行できない場合は、[他のホスティングオプション](#other-hosting-
```suggestion
> [カスタムサーバー](/docs/advanced-features/custom-server.md)を使用している場合は、代替手法への移行を強くお勧めします(例えば、[動的ルーティング](/docs/routing/dynamic-routes.md)を使用するなど)。移行できない場合は、[他のホスティング方法](#other-hosting-options)を検討してください。
```
"custom server"はシンプルにカスタムサーバーとするのはどうでしょうか？また、「他への移行」は「カスタムサーバから他の方法（動的ルーティングなど）への移行」を指していますので、わかりやすいように少し表現を変えてみました。また、ここの「オプション」も「方法」に言い換えるのはどうでしょう？

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +### DPS: 開発（Develop）、プレビュー（Preview）、出荷（Ship）
```suggestion
### DPS: 開発（Develop）、プレビュー（Preview）、公開（Ship）
```
Shipを公開と訳すのはどうでしょうか？

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +ここでは、[Vercel](https://vercel.com)が推奨するワークフローについて説明します。[Vercel](https://vercel.com)では、**DPS**ワークフローと呼ばれるものをサポートしています。**DPS**とは、開発（**D**evelop）・プレビュー（**P**review）・出荷（**S**hip）のことです。
```suggestion
ここでは、[Vercel](https://vercel.com)が推奨するワークフローについて説明します。[Vercel](https://vercel.com)では、私たちが**DPS**と呼ぶワークフローを支持しています。**DPS**とは、開発（**D**evelop）・プレビュー（**P**review）・公開（**S**hip）の頭字語です。
```
"what we call"とありますので、ニュアンスを含むように修正しました！また、ここでいう"supports"は「支持する」と訳すのが良いかと思いますがどうでしょうか？

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +- **出荷（Ship）:** 本番環境に出荷する準備ができたら、プルリクエストをデフォルトのブランチ (例: `master`) にマージします。Vercel は自動的に本番環境のデプロイを実施し、本番環境を更新します。
```suggestion
- **公開（Ship）:** 本番環境で公開する準備ができたら、プルリクエストをデフォルトのブランチ (例: `master`) にマージします。Vercel  は自動的に本番環境へのデプロイを行います。
```
少し言い回しを変えましたのでご確認ください！

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +プルリクエストを開いたときに GitHub で見ることができますし、Vercel のプロジェクトページの「デプロイメントのプレビュー」で見ることもできます。[詳細はこちらをご覧ください](https://vercel.com/features/deployment-previews)。
```suggestion
プルリクエストを開くと GitHub で見ることができますし、Vercel のプロジェクトページの「デプロイメントのプレビュー」で見ることもできます。[詳細はこちらをご覧ください](https://vercel.com/features/deployment-previews)。
```
少し冗長かと思い修正しましたがいかがでしょうか？

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +例えば、[ハイブリッドページ](/docs/basic-features/pages.md)を活用する手法は完全にサポートされています。
```suggestion
例えば、[ハイブリッドページ](/docs/basic-features/pages.md)については完全にサポートされています。
```
少し冗長に感じましたので修正しましたがいかがでしょうか？

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +- [静的サイト生成]（/docs/basic-features/pages.md#static-generation）または[サーバサイドレンダリング]（/docs/basic-features/pages.md#server-side-rendering）を使用できます。
```suggestion
- 各ページについて[静的サイト生成]（/docs/basic-features/pages.md#static-generation）または[サーバサイドレンダリング]（/docs/basic-features/pages.md#server-side-rendering）を使用できます。
```
"Every page"のニュアンスを加えました！

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +- [サーバサイドレンダリング](/docs/basic-features/pages.md#server-side-rendering) と [APIルート](/docs/api-routes/introduction.md) を使用しているページは、自動的にページと分離されたサーバレスなファンクションとしてデプロイされます。これにより、レンダリングとAPIリクエストを無限にスケールさせること
```suggestion
- [サーバサイドレンダリング](/docs/basic-features/pages.md#server-side-rendering) と [APIルート](/docs/api-routes/introduction.md) を使用しているページは、独立したサーバレス関数へと自動的に変換してデプロイします。これにより、レンダリングとAPIリクエストを無限にスケールさせることができます。
```
「自動的にページと分離されたサーバレスなファンクションとしてデプロイ」が冗長に感じましたので少し言い回しを変えましたがどうでしょうか？

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +- **環境変数:** Vercelでは環境変数を設定できます。詳細は、[ここにあるドキュメント](https://vercel.com/docs/v2/build-step#using-environment-variables-and-secrets) を参照してください。そして、Next.jsアプリ内で[これらの環境変数](/docs/api-reference/next.config.j
```suggestion
- **環境変数:** Vercel では環境変数を設定できます。詳細は、[ここにあるドキュメント](https://vercel.com/docs/v2/build-step#using-environment-variables-and-secrets) を参照してください。Next.js アプリ内で[これらの環境変数](/docs/api-reference/next.config.js/environment-variables.md)を使用できます。
```
「そして」はなくても良いかと思いましたがいかがでしょうか？

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +- **上記以外:** Vervelというプラットフォームを知るために[ドキュメント](https://vercel.com/docs)を読んでいただければ幸いです。
```suggestion
- **その他:** Vervel というプラットフォームをさらに知るために[ドキュメント](https://vercel.com/docs)をご覧ください。
```
"Read.." ですので、それほど丁寧な言い回しである必要はないと感じましたがいかがでしょうか？また、"learn more"のニュアンスを加えました！

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +## その他のホスティングオプション
```suggestion
## その他のホスティング方法
```
上と同様です！

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +ビルド後、`next start`スクリプトにより [Pagesにおける動的なルーティング](/docs/basic-features/pages.md) をサポートする Node.js サーバを起動します。
```suggestion
ビルド後に実行する `next start` により、静的に生成されたページとサーバサイドでレンダリングされたページ の[ハイブリッドページ](/docs/basic-features/pages.md) をサポートする Node.js サーバを起動します。
```
下の文章と統合してみましたがいかがでしょうか？

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +静的に生成されたページとサーバサイドでレンダリングされたページの両方をサポートします。
```suggestion
```
統合したのでここは削除します！

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +### 静的サイト生成
```suggestion
### 静的 HTML の出力
```
Exportですので作成ではなく出力（あるいは単にエクスポート）が良いかと思いますがいかがでしょう？

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +Next.jsアプリの静的サイト生成を用いたい場合は、[ドキュメント](/docs/advanced-features/static-html-export.md)の指示に従ってください。デフォルトでは、`next export`によりは`out`ディレクトリに、CDN や静的サイトホスティングサービスで用いることができる静的サイトを生成します。
```suggestion
Next.js アプリを静的 HTML へと出力したい場合は、[ドキュメント](/docs/advanced-features/static-html-export.md)の指示に従ってください。デフォルトでは、`next export`によって`out`ディレクトリが生成され、 CDN や静的サイトホスティングサービスで配信することができます。
```
言い回し修正しましたのでご確認ください！

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +> ご利用のNext.jsアプリが完全に静的サイトの場合でも、[Vercel](https://vercel.com/)を使用することを強くお勧めします。[Vercel](https://vercel.com/) は、静的な Next.js アプリが非常に高速に動作するように最適化されています。`next export`で生成された静的サイトは、Vercel では設定を一切行わずにデプロイするこ
```suggestion
> ご利用の Next.js アプリが完全に静的サイトの場合でも、[Vercel](https://vercel.com/) を使用することを強くお勧めします。[Vercel](https://vercel.com/) は、静的な Next.js アプリが非常に高速に動作するように最適化されています。`next export` は、Vercel では設定を一切行わずにデプロイしても動作します。
```
「することでも」が少し冗長に感じましたが、いかがでしょうか？

2020-07-19 14:26 UTC, hoosan commented on docs/deployment.md
> +あなたの`package.json`に`"build"`と`"start"`スクリプトが含まれていることを確認してください。
```suggestion
あなたの `package.json` に `"build"` と `"start"` のスクリプトが含まれていることを確認してください。
```
助詞を足しました！

2020-07-21 15:40 UTC, YopiNoji commented on docs/deployment.md
> +description: Next.jsアプリをVercelやその他のホスティングオプションを使って本番環境にデプロイします。
ご指摘ありがとうございます！
おっしゃる通りだと思います。修正を取り込ませていただきます。

2020-07-21 15:44 UTC, YopiNoji commented on docs/deployment.md
> +おめでとうございます！Next.jsアプリのデプロイが完了しました。質問がある場合は、[Vercel documentation](https://vercel.com/docs) を参照してください。
確かに、「疑問点」の方が訳語として最適ですね。

2020-07-21 15:46 UTC, YopiNoji commented on docs/deployment.md
> +> [Next.js においてカスタマイズされたサーバー設定](/docs/advanced-features/custom-server.md)を使用したい場合は、他への移行を強くお勧めします(例えば、[ダイナミックルーティング](/docs/routing/dynamic-routes.md)を使用するなど)。移行できない場合は、[他のホスティングオプション](#other-hosting-
`他のホスティングオプション` → `他のホスティング方法`
おっしゃる通り、そちらの方がわかりやすいですね。

2020-07-21 15:47 UTC, YopiNoji commented on docs/deployment.md
> +### DPS: 開発（Develop）、プレビュー（Preview）、出荷（Ship）
Ship の訳語悩んだのですが、「公開」の方がしっくりする気がしますね。

2020-07-21 15:50 UTC, YopiNoji commented on docs/deployment.md
> +プルリクエストを開いたときに GitHub で見ることができますし、Vercel のプロジェクトページの「デプロイメントのプレビュー」で見ることもできます。[詳細はこちらをご覧ください](https://vercel.com/features/deployment-previews)。
確かに、「ときに」を多用しすぎていました:bow:

2020-07-21 15:52 UTC, YopiNoji commented on docs/deployment.md
> +- [サーバサイドレンダリング](/docs/basic-features/pages.md#server-side-rendering) と [APIルート](/docs/api-routes/introduction.md) を使用しているページは、自動的にページと分離されたサーバレスなファンクションとしてデプロイされます。これにより、レンダリングとAPIリクエストを無限にスケールさせること
「ページと分離」　→　「独立」
おっしゃる通り、冗長でした:bow:

2020-07-21 15:54 UTC, YopiNoji commented on docs/deployment.md
> +- **出荷（Ship）:** 本番環境に出荷する準備ができたら、プルリクエストをデフォルトのブランチ (例: `master`) にマージします。Vercel は自動的に本番環境のデプロイを実施し、本番環境を更新します。
冗長な表現でした:bow:

2020-07-21 16:14 UTC, YopiNoji commented
@hoosan 
ご指摘いただきありがとうございます！！（細かい指摘が多くて、こちらこそ恐縮です:bow:）
修正しましたのでご確認いただければ幸いです。

2020-07-21 16:15 UTC, YopiNoji commented
また、lint のルールが少し更新されたようだったので、そちらの指摘にも対応しました！

2020-07-22 14:29 UTC, hoosan requested changes
修正いただきありがとうございます！
改めて読んでみて数点気になる場所がありましたので、お手数ですがご確認お願いします🙏
また、可能であればコミットは一つにまとめていただけると大変助かります！

2020-07-22 14:29 UTC, hoosan commented on docs/deployment.md
> +Next.js を本番環境にデプロイする最も簡単な方法は、Next.js の開発者が提供する **[Vercel platform](https://vercel.com)** を利用することです。[Vercel](https://vercel.com) は、静的サイト・JAMstack なアーキテクチャでのデプロイ、サーバーレスファンクション機能をサポートするグローバル CDN を備えたオール
```suggestion
Next.js を本番環境にデプロイする最も簡単な方法は、Next.js の開発者が提供する **[Vercel platform](https://vercel.com)** を利用することです。[Vercel](https://vercel.com) は、静的サイト・JAMstack なアーキテクチャでのデプロイや、サーバーレスファンクション機能をサポートするグローバル CDN を備えたオールインワンプラットフォームです。
```
細かくて恐縮ですが少し読みにくかったので修正しました🙏

2020-07-22 14:29 UTC, hoosan commented on docs/deployment.md
>  はじめに、Next.js アプリを任意の Git プロバイダーにプッシュしてください。[GitHub](http://github.com/)、[GitLab](https://gitlab.com/)、[BitBucket](https://bitbucket.org/)などです。リポジトリはプライベートとパブリックのどちらでも構いません。
```suggestion
はじめに、Next.js アプリを[GitHub](http://github.com/)、[GitLab](https://gitlab.com/)、[BitBucket](https://bitbucket.org/)など任意の Git プロバイダーにプッシュしてください。リポジトリはプライベートとパブリックのどちらでも構いません。
```
文章を統一できると思いますがどうでしょうか？

2020-07-22 14:29 UTC, hoosan commented on docs/deployment.md
> +1. [Vercelにサインアップする](https://vercel.com/signup)（クレジットカードの登録は不要）。
```suggestion
1. [Vercelにサインアップしてください](https://vercel.com/signup)（クレジットカードの登録は不要です）。
```
他と文体を合わせました！

2020-07-22 14:29 UTC, hoosan commented on docs/deployment.md
>  2. サインアップ後に、[「Import Project」](https://vercel.com/import)ページに遷移します。「From Git Repository」でデプロイに使用する Git プロバイダーを選択し、設定をします。(設定は各プロバイダーで次の手順で行います: [GitHub](https://vercel.com/docs/v2/git-integrations/ve
```suggestion
2. サインアップすると、[Import Project](https://vercel.com/import)ページに遷移します。「From Git Repository」からデプロイに使用する[GitHub](https://vercel.com/docs/v2/git-integrations/vercel-for-github)、[GitLab](https://vercel.com/docs/v2/git-integrations/vercel-for-gitlab) 、[BitBucket](https://vercel.com/docs/v2/git-integrations/vercel-for-bitbucket))などの Git プロバイダーを選択して設定を行います。(設定は各プロバイダーで次の手順で行います。
```
こちらも気になったので直しました！

2020-07-22 14:29 UTC, hoosan commented on docs/deployment.md
> +ここでは、[Vercel](https://vercel.com)が推奨するワークフローについて説明します。[Vercel](https://vercel.com)では、私たちが**DPS**と呼ぶワークフローを支持しています。**DPS**とは、開発（**D**evelop）・プレビュー（**P**review）・公開（**S**hip）の頭字語です。
```suggestion
ここでは、[Vercel](https://vercel.com)が推奨するワークフローについて説明します。[Vercel](https://vercel.com)では、いわゆる**DPS**ワークフローを支持しています。**DPS**とは、開発（**D**evelop）・プレビュー（**P**review）・公開（**S**hip）の頭字語です。
```
申し訳ありません！"what we call"は「いわゆる」と訳す方が自然だと思い至りました🙏（DPSはVercel以外では聞かないような気がするので、修正前の訳でも良い気はしますが・・）

2020-07-22 14:29 UTC, hoosan commented on docs/deployment.md
>  あなたの `package.json` に `"build"` と `"start"` のスクリプトが含まれていることを確認してください。
```suggestion
`package.json` に `"build"` と `"start"` のスクリプトが含まれていることを確認してください。
```
「あなたの」はあえてつけなくて良いかと思いました

2020-07-22 15:11 UTC, YopiNoji commented on docs/deployment.md
>  あなたの `package.json` に `"build"` と `"start"` のスクリプトが含まれていることを確認してください。
🙇

2020-07-22 15:31 UTC, YopiNoji commented on docs/deployment.md
> +Next.js を本番環境にデプロイする最も簡単な方法は、Next.js の開発者が提供する **[Vercel platform](https://vercel.com)** を利用することです。[Vercel](https://vercel.com) は、静的サイト・JAMstack なアーキテクチャでのデプロイ、サーバーレスファンクション機能をサポートするグローバル CDN を備えたオール
🙇

2020-07-22 15:33 UTC, YopiNoji commented on docs/deployment.md
>  はじめに、Next.js アプリを任意の Git プロバイダーにプッシュしてください。[GitHub](http://github.com/)、[GitLab](https://gitlab.com/)、[BitBucket](https://bitbucket.org/)などです。リポジトリはプライベートとパブリックのどちらでも構いません。
おっしゃる通りです:bow:
気付けず申し訳ありません。

2020-07-22 16:09 UTC, YopiNoji commented on docs/deployment.md
>  2. サインアップ後に、[「Import Project」](https://vercel.com/import)ページに遷移します。「From Git Repository」でデプロイに使用する Git プロバイダーを選択し、設定をします。(設定は各プロバイダーで次の手順で行います: [GitHub](https://vercel.com/docs/v2/git-integrations/ve
修正ありがとうございます:bow:

`設定を行います。(設定は各プロバイダーで次の手順で行います。`
上記の箇所、そのままだと linter にも指摘されていましたので、以下のように修正しました。
`設定をします（設定は各プロバイダーで次の手順で行います）。`

2020-07-23 08:15 UTC, YopiNoji commented
@hoosan 
いくつか修正しましたので、今一度確認いただければ幸いです:bow:

2020-07-23 10:03 UTC, hoosan commented
すみません！最後に一つ、
`[静的サイト生成]（/docs/basic-features/pages.md#static-generation）`
のカッコが大文字になっていてリンクにできていないところが2箇所ありますのでご対応いただけますでしょうか><
### Next.js のための最適化
の部分です。あとはLGTMです！

2020-07-23 11:27 UTC, YopiNoji commented
@hoosan 
何度も申し訳ありません:bow: :bow: :bow:
修正いたしました。

2020-07-23 12:03 UTC, hoosan approved these changes
ご対応ありがとうございます！私からはLGTMです👍

もう一人のレビュアーの方、お手数ですがご確認お願いします🙏

2020-07-23 13:34 UTC, yokinist requested changes
翻訳ありがとうございます！1点だけ気になったところあったのでコメントさせていただきました！

2020-07-23 13:34 UTC, yokinist commented on docs/deployment.md
> +ここでは、[Vercel](https://vercel.com)が推奨するワークフローについて説明します。[Vercel](https://vercel.com)では、いわゆる **DPS** ワークフローを支持しています。**DPS** とは、開発（**D**evelop）・プレビュー（**P**review）・公開（**S**hip）の頭字語です。
1点細かいところですが、ここは「支持」よりも「サポート」の方が自然な訳かと思いました！

2020-07-23 14:27 UTC, hoosan commented on docs/deployment.md
> +ここでは、[Vercel](https://vercel.com)が推奨するワークフローについて説明します。[Vercel](https://vercel.com)では、いわゆる **DPS** ワークフローを支持しています。**DPS** とは、開発（**D**evelop）・プレビュー（**P**review）・公開（**S**hip）の頭字語です。
すみませんこちら私が直したとこでした🙏
ここのsupportは推しているとか支援しているという意味かと思うので、機能が対応しているというような意味が強い「サポートする」より「支持する」が良いかと思ったのですが、どうでしょう？

2020-07-23 15:17 UTC, yokinist commented on docs/deployment.md
> +ここでは、[Vercel](https://vercel.com)が推奨するワークフローについて説明します。[Vercel](https://vercel.com)では、いわゆる **DPS** ワークフローを支持しています。**DPS** とは、開発（**D**evelop）・プレビュー（**P**review）・公開（**S**hip）の頭字語です。
申し訳ありません、経緯確認不足でした！確かによく読んだら、おっしゃる通り推すというニュアンスの支持の方が良さそうですね！

2020-07-23 15:18 UTC, yokinist approved these changes
お騒がせしましたが、LGTMです！
ご協力ありがとうございました🙏

2020-07-23 15:23 UTC, yokinist commented
@all-contributors please add @YopiNoji for translation

2020-07-23 15:24 UTC, merged