docs: translate docs/api-reference/cli.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #63
Opened 2020-07-19 08:37 UTC by f-teruhisa

`docs/api-reference/cli.md` を翻訳させていただきましたので、レビューをお願いします。
`docs/manifest.json` のメニューについては、 `CLI` のままで良いと判断しこちらは翻訳しておりません。

2020-07-19 09:04 UTC, hiro08gh commented
翻訳していただきありがとうございます！順次レビューしますので、お待ちください。

2020-07-19 12:22 UTC, Shinyaigeek requested changes
ありがとうございます！
少しコメント, suggest残したので確認お願いします 🙏

2020-07-19 12:22 UTC, Shinyaigeek commented on docs/api-reference/cli.md
> +_([npx](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b) はnpm 5.2+ 以上が組み込まれています。)_
```suggestion
_([npx](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b) はnpm 5.2+ 以上に組み込まれています。)_
```

2020-07-19 12:22 UTC, Shinyaigeek commented on docs/api-reference/cli.md
> +- **First Load JS** – サーバーからページへアクセスしたときにダウンロードされたアセットの数。すべてのアプリケーションで共有されるJSの量は、別の指標として表示されます。
```suggestion
- **First Load JS** – ページへアクセスしたときにサーバーからダウンロードされたアセットの数。すべてのアプリケーションで共有されるJSの量は、別の指標として表示されます。
```

「サーバーから」が最初にあると, それがアクセスにかかっているのかダウンロードにかかっているのか不明瞭かと思いましたがどうでしょうか？

2020-07-19 14:15 UTC, hiro08gh reviewed
翻訳していただきありがとうございます。概要の部分はdescriptionで統一していただけたら嬉しいです。

2020-07-19 14:15 UTC, hiro08gh commented on docs/api-reference/cli.md
> +概要: Next.js CLIを使用すると、アプリケーションの起動やビルド、エクスポートを行うことができます。詳細はこちらをご覧ください。
```suggestion
description: Next.js CLIを使用すると、アプリケーションの起動やビルド、エクスポートを行うことができます。詳細はこちらをご覧ください。
```

2020-07-19 15:01 UTC, f-teruhisa commented on docs/api-reference/cli.md
> +- **First Load JS** – サーバーからページへアクセスしたときにダウンロードされたアセットの数。すべてのアプリケーションで共有されるJSの量は、別の指標として表示されます。
ありがとうございます。おっしゃるとおりだと思いますので、Suggestionを取り込ませていただきますｍｍ

2020-07-20 01:56 UTC, hiro08gh commented
ありがとうございます！僕からはLGTMです！

2020-07-20 10:28 UTC, Shinyaigeek approved these changes
対応ありがとうございます！LGTMです :+1:

2020-07-20 10:29 UTC, hiro08gh approved these changes

2020-07-20 10:29 UTC, merged

2020-07-20 15:36 UTC, yokinist commented
@all-contributors please add @f-teruhisa for translation