docs: translate /docs/api-routes/dynamic-api-routes.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #71
Opened 2020-07-19 13:00 UTC by okmr-d

`/docs/api-routes/dynamic-api-routes.md`を翻訳しました。
レビューよろしくお願いします。

`route`の訳を`ルーティング`にまとめてしまうと一部変な訳になるので`ルート`も併用してます。

2020-07-19 15:12 UTC, yokinist reviewed
翻訳のご協力ありがとうございます！ 
細かい箇所が多く恐縮ですがコメントさせていただきました！ご確認お願いします🙏
PENDINGの箇所についてはもう1人のレビュアーの方と確認して方針を決めたいと思うので、そのままで大丈夫です

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +}
[MUST]
`;` がなくなっていたり `,` が追加されていたり原文から変わってしまっている箇所があるので元のままでお願いしたいです！

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +このとき、`/api/post/abc`へのリクエストは次のテキストを返します: `Post: abc`
[PENDING]
原文に合わせようとすると最後に句読点を置いたほうがいいと思いますが、`:` の後なので不要にしちゃっていいかなということを検討したいです

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +非常に一般的なRESTfulパターンは、次のようなルートを設定します:
[IMO]
```suggestion
ごく一般的なRESTfulパターンは、次のようなルートを設定します:
```
`非常に` より `ごく` のほうが自然かなと思いましたが、いかがでしょうか？

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +}
[MUST]
（こちらも同じく）`;` がなくなっていたり `,` が追加されていたり原文から変わってしまっている箇所があるので元のままでお願いしたいです！

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +このとき、`/api/post/a/b/c`へのリクエストは次のテキストを返します: `Post: a, b, c`
[PENDING]
（こちらも同じく）原文に合わせようとすると最後に句読点を置いたほうがいいと思いますが、: の後なので不要にしちゃっていいかなということを検討したいです

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +  - `pages/api/post/create.js` - `/api/post/create`にマッチします
[nits]
```suggestion
  - `pages/api/post/create.js` - `/api/post/create`に一致します
```
ここまでの箇所では `match` を `一致` と訳しているので統一したいです

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +  - `pages/api/post/[pid].js` - `/api/post/1`、`/api/post/abc`などにマッチします。しかし、`/api/post/create`にはマッチしません。
[nits]
```suggestion
  - `pages/api/post/[pid].js` - `/api/post/1`、`/api/post/abc`などに一致します。しかし、`/api/post/create`には一致しません。
```

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +  - `pages/api/post/[...slug].js` - `/api/post/1/2`、`/api/post/a/b/c`などにマッチします。しかし、`/api/post/create`、`/api/post/abc`などにはマッチしません。
[nits]
```suggestion
  - `pages/api/post/[...slug].js` - `/api/post/1/2`、`/api/post/a/b/c`などにマッチします。しかし、`/api/post/create`、`/api/post/abc`などには一致しません。
```

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +    <small>ビルトインの動的ルーティングについて学びましょう。</small>
[IMO]
```suggestion
    <small>ビルトインされた動的ルーティングについて学びましょう。</small>
```
ビルドインが動的ルーティングにうまくかかっていなかったように見えたので `ビルドインされた` はいかがでしょうか？

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +括弧`[]`内に3つのドット（`...`）を追加することで、APIルートを拡張してすべてのパスをキャッチできます。例えば:
[nits]
```suggestion
角括弧`[]`内に3つのドット（`...`）を追加することで、APIルートを拡張してすべてのパスをキャッチできます。例えば:
```
日本語だと `[]` は角括弧になるそうです！

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +すべてのルートをキャッチすることは、`[[...slug]]`のようにパラメータを二重括弧内に含めることでオプショナルにできます。
[nits]
```suggestion
すべてのルートをキャッチすることは、`[[...slug]]`のようにパラメータを二重角括弧内に含めることでオプショナルにできます。
```

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +- `pages/api/post/[...slug].js`は`/api/post/a`と一致しますが、`/api/post/a/b`、`/api/post/a/b/c`なども一致します。
[IMO]
```suggestion
- `pages/api/post/[...slug].js`は`/api/post/a`に一致しますが、`/api/post/a/b`、`/api/post/a/b/c`などにも一致します。
```
細かい日本語表現ですがこちらのほうが自然かなと思いましたが、いかがでしょうか？

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +一致したパラメータはクエリパラメータ（例では`slug`）としてページに送信され、常に配列になり、パス`/api/post/a`には次の`query`オブジェクトが含まれます:
[IMO]
```suggestion
一致したパラメータはクエリパラメータ（例では`slug`）としてページに送信され、常に配列になり、パス`/api/post/a`は次の`query`オブジェクトを持ちます:
```
`have` に対しては「含む」というより「持つ」が近いかなと思いましたが、いかがでしょうか？

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +description: ページに使用される動的ルーティングはAPIのルーティングにおいても使用できます。ここではそれがどのように機能するかを学びます。
[IMO]
```suggestion
description: ページに使用される動的ルーティングはAPIのルーティングにおいても使用できます。ここでは、それがどのように機能するかを学びます。
```
原文にはないですが「このとき」の箇所同様に「ここでは」のあとには句読点 ( `、` ) があったほうが自然なのではと思いましたがいかがでしょうか？

2020-07-19 15:12 UTC, yokinist commented on docs/api-routes/dynamic-api-routes.md
> +- 事前定義されたAPIのルーティングは動的APIルーティングよりも優先され、動的APIルーティングはすべてのAPIルートのキャッチよりも優先されます。次の例を見てください:
[IMO]
```suggestion
- 予め定義されたAPIのルーティングは動的APIルーティングよりも優先され、動的APIルーティングはすべてのAPIルートのキャッチよりも優先されます。次の例を見てください:
```
細かい表現ですがこちらのほうが自然かなと思いました。いかがでしょうか？

2020-07-21 13:02 UTC, hoosan commented on docs/api-routes/dynamic-api-routes.md
> +このとき、`/api/post/abc`へのリクエストは次のテキストを返します: `Post: abc`
IMOですが、日本語文の最後にコロンが来るのは、後ろにコードブロックが続く場合を除くと不自然に感じます。

```suggestion
このとき、`/api/post/abc`へのリクエストは`Post: abc`というテキストを返します。 
```
のように文章にするのはどうでしょうか？

2020-07-23 04:36 UTC, yokinist requested changes
コメントとして書き込んでしまっていましたが、Request changes として送らせていただきます

2020-07-24 21:37 UTC, okmr-d commented
指摘箇所を修正しました。
基本的にレビューいただいた内容をそのまま反映させてもらってます。

あと、手元ではmasterマージした状態でtextlintが通ったのですが、githubのcheckでfailedになってしまい、、
お手数ですがご確認いただけますでしょうか？

再レビューよろしくお願いします。

2020-07-26 23:39 UTC, okmr-d commented
再度マスターをマージしたらtextlintのエラー解消されました。
再レビューよろしくお願いします。

2020-07-27 00:16 UTC, hiro08gh commented
修正していただきありがとうございます！順次対応致しますので、もう少々お待ちください！

2020-07-27 01:27 UTC, yokinist submitted a review, later dismissed
確認遅くなってしまい申し訳ありません🙇‍♂️
僕からはLGTMです！ありがとうございます！

2020-07-27 13:57 UTC, yokinist approved these changes

2020-07-27 14:00 UTC, hoosan approved these changes

2020-07-27 14:15 UTC, merged