translate docs/api-reference/next.config.js/build-target.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #73
Opened 2020-07-19 15:37 UTC by dmamira

build targetsの部分を翻訳しました。

2020-07-19 18:36 UTC, yokinist reviewed
翻訳ありがとうございます！  
細かい箇所が多く恐縮ですがコメントさせていただきました。ご確認お願いします 🙇 
PENDINGの箇所についてはもう1人のレビュアーの方にも意見も参考にしながら方針等を決めたいと思うので、一旦はそのままで大丈夫です

2020-07-19 18:36 UTC, yokinist commented on docs/api-reference/next.config.js/build-target.md
> +description: Next.jsで使用され、アプリケーションの構築と実行の方法を決定するbuild targetについて学びましょう。
[IMO]
```suggestion
description: Next.jsで使用され、アプリケーションのビルドと実行方法を決めるbuild targetについて学びましょう。
```
buildに関しては構築よりもビルドの方が直接的で日本語としても通用するので、そのままで良いのではと思いました。また、実行の方法は実行方法でいいかなと思いましたがいかがでしょうか？

2020-07-19 18:36 UTC, yokinist commented on docs/api-reference/next.config.js/build-target.md
> +Next.jsは様々なビルドターゲットをサポートしています。これらはそれぞれ、あなたのアプリケーションのビルドと実行の方法を変えます。下記で各ターゲットについて説明します。
[IMO]
```suggestion
Next.jsは様々なビルドターゲットをサポートしています。これらはそれぞれ、あなたのアプリケーションのビルドと実行方法を変えます。下記でそれぞれのターゲットについて説明します。
```
「各ターゲット」を少し柔らかく「それぞれのターゲット」としてみましたが、いかがでしょうか？

2020-07-19 18:36 UTC, yokinist commented on docs/api-reference/next.config.js/build-target.md
> +> これはデフォルトのターゲットですが、我々は[`serverless` target](#serverless-target)を強くお勧めします。`serverless`ターゲットは、[追加の制約](https://rauchg.com/2020/2019-in-review#serverless-upgrades-itself)を強制することで、あなたを[成功の落とし穴](https://b
[PENDING/IMO]
```suggestion
> これはデフォルトのターゲットですが、我々は[`serverless` target](#serverless-target)を強くお勧めします。`serverless`ターゲットは、[追加の制約(原文: additional constraints)](https://rauchg.com/2020/2019-in-review#serverless-upgrades-itself)を強制することで、あなたを[成功の落とし穴(原文: Pit of Success)](https://blog.codinghorror.com/falling-into-the-pit-of-success/)にはめてくれます(訳注:成功に導いてくれるということ)。
```
訳注ありがとうございます！ここは訳し方難しいところですね・・

1. 訳注や原文といった追加を許容するのはルールとしてもう1人のレビュアーの方と確認したいです。

2. (その上で許容されるのであれば) 記事からの引用された言葉なので原文も載せたほうがいいかなと思いましたが、どうでしょうか？

2020-07-19 18:36 UTC, yokinist commented on docs/api-reference/next.config.js/build-target.md
> +使用する場合はこのターゲットが必須)
[nits]
```suggestion
このターゲットは、`next start`と[カスタムサーバー](/docs/advanced-features/custom-server.md)の両方の設定と互換性があります。(カスタムサーバーを使用する場合はこのターゲットが必須)
```
不要な改行がはいってしまっていたので

2020-07-19 18:36 UTC, yokinist commented on docs/api-reference/next.config.js/build-target.md
> +## 関連ページ:
[MUST]
```suggestion
## 関連事項
```
こちらは表記の統一性の観点から関連事項でお願いします🙏

2020-07-19 18:36 UTC, yokinist commented on docs/api-reference/next.config.js/build-target.md
> +あなたのアプリケーションは全てのページが1つの大きなアプリケーションとしてビルドされ、デプロイされます。これはデフォルトターゲットで、特に設定は必要ありません。
[IMO]
```suggestion
あなたのアプリケーションは全てのページが1つの大きなアプリケーションとしてビルドされ、デプロイされます。これはデフォルトのターゲットで、特に設定の必要はありません。
```
他の箇所では `デフォルトの` となっていたのでそのまま繋げずに `の` があったほうが日本語として伝わりやすいと思いました！ `設定の必要はありません` も同様により伝わりやすいのではという理由で提案させていただきました

2020-07-19 18:36 UTC, yokinist commented on docs/api-reference/next.config.js/build-target.md
> +このターゲットは、`next start`、もしくは[Vercel](https://vercel.com)のようなサーバーレスプラットフォームとしか互換性がありません。- カスタムサーバーを利用できません。
[PENDING]
原文では `custom server API` となっていますが、文脈としてはAPIを含めると日本語としては不自然になってしまうので自分も `カスタムサーバー` でいいんじゃないかなと思いましたが、もう1人のレビュアーの方にも意見を伺いたいです

2020-07-19 18:36 UTC, yokinist commented on docs/api-reference/next.config.js/build-target.md
> +このターゲットを選択するには、`next.config.js`を以下のように設定してください。
[nits]
```suggestion
このターゲットを選択するには、`next.config.js`を以下のように設定してください:
```

2020-07-20 01:44 UTC, dmamira commented on docs/api-reference/next.config.js/build-target.md
> +description: Next.jsで使用され、アプリケーションの構築と実行の方法を決定するbuild targetについて学びましょう。
確かに、”ビルド”は日本語でもよく使いますね。修正します。

2020-07-20 01:46 UTC, dmamira commented on docs/api-reference/next.config.js/build-target.md
> +> これはデフォルトのターゲットですが、我々は[`serverless` target](#serverless-target)を強くお勧めします。`serverless`ターゲットは、[追加の制約](https://rauchg.com/2020/2019-in-review#serverless-upgrades-itself)を強制することで、あなたを[成功の落とし穴](https://b
直訳の”成功の落とし穴”という言葉も、日本語圏ではあまり聞かないので原文を載せるのは良いと思います。
確認よろしくお願いします。

2020-07-20 01:46 UTC, dmamira commented on docs/api-reference/next.config.js/build-target.md
> +使用する場合はこのターゲットが必須)
ありがとうございます。修正します

2020-07-20 01:46 UTC, dmamira commented on docs/api-reference/next.config.js/build-target.md
> +## 関連ページ:
承知しました。修正します。

2020-07-20 01:47 UTC, dmamira commented on docs/api-reference/next.config.js/build-target.md
> +あなたのアプリケーションは全てのページが1つの大きなアプリケーションとしてビルドされ、デプロイされます。これはデフォルトターゲットで、特に設定は必要ありません。
こちらの方がより自然だと思います。修正します。

2020-07-20 03:03 UTC, yokinist commented on docs/api-reference/next.config.js/build-target.md
> +## 関連事項:
[nits]
```suggestion
## 関連事項
```
後からすいません！textlintで気付きましたが、ここは `:` が不要ですね 👀

2020-07-20 03:04 UTC, yokinist commented on docs/api-reference/next.config.js/build-target.md
> +あなたのアプリケーションは全てのページが1つの大きなアプリケーションとしてビルドされ、デプロイされます。これはデフォルトターゲットで、特に設定は必要ありません。
ありがとうございます！

2020-07-21 13:46 UTC, hoosan commented on docs/api-reference/next.config.js/build-target.md
> +> これはデフォルトのターゲットですが、我々は[`serverless` target](#serverless-target)を強くお勧めします。`serverless`ターゲットは、[追加の制約](https://rauchg.com/2020/2019-in-review#serverless-upgrades-itself)を強制することで、あなたを[成功の落とし穴](https://b
"Pit of Success"の原文併記は賛成です！
ただ、「成功の落とし穴」だけで十分良い訳語だと思うので、あえて訳注はつけなくて良いと思います。

additional constraintsについては原文併記なくて良いかと思いますがどうでしょう？
原文があるということはそこに特別な理由があるはず（「成功の落とし穴」のように日本語に何らかの違和感があるとか）と読み手は考えると思うのですが、additional constraintsを追加の制約と訳すのは特に問題ないように思いました！

2020-07-21 15:26 UTC, yokinist commented on docs/api-reference/next.config.js/build-target.md
> +> これはデフォルトのターゲットですが、我々は[`serverless` target](#serverless-target)を強くお勧めします。`serverless`ターゲットは、[追加の制約](https://rauchg.com/2020/2019-in-review#serverless-upgrades-itself)を強制することで、あなたを[成功の落とし穴](https://b
@hoosan ありがとうございます！おっしゃる通り訳注はなくても意味が通っているので、なくてもいいかなと思いました。また、追加の制約についても十分に伝わるので原文の表記はなくていいですね。Suggested change の方を更新させていただきました！

2020-07-22 06:18 UTC, dmamira commented on docs/api-reference/next.config.js/build-target.md
> +> これはデフォルトのターゲットですが、我々は[`serverless` target](#serverless-target)を強くお勧めします。`serverless`ターゲットは、[追加の制約](https://rauchg.com/2020/2019-in-review#serverless-upgrades-itself)を強制することで、あなたを[成功の落とし穴](https://b
ありがとうございます！
修正します！

2020-07-22 14:31 UTC, hoosan commented on docs/api-reference/next.config.js/build-target.md
> +このターゲットは、`next start`、もしくは[Vercel](https://vercel.com)のようなサーバーレスプラットフォームとしか互換性がありません。- カスタムサーバーを利用できません。
私もAPIとあえてつける必然性は感じませんでしたので、「カスタムサーバー」の訳に賛成します！

2020-07-23 04:54 UTC, yokinist requested changes
@dmamira 
確認送れて申し訳ありません！うまく Suggested change できていなかったので再度送りました、それぞれ問題なければ取り込んでいただき別途検討することがあればコメントいただけると嬉しいです。

また、変更時点での表記ゆれの設定の関係で textlint が通っていない状態になっています。お手数ですが、最新の master を取り込んでいただけると通るようになるので更新お願いいたします🙏

2020-07-23 04:54 UTC, yokinist commented on docs/api-reference/next.config.js/build-target.md
> +> これはデフォルトのターゲットですが、我々は[`serverless` target](#serverless-target)を強くお勧めします。`serverless`ターゲットは、[追加の制約(原文: additional constraints)](https://rauchg.com/2020/2019-in-review#serverless-upgrades-itself)を強制す
```suggestion
> これはデフォルトのターゲットですが、我々は[`serverless` target](#serverless-target)を強くお勧めします。`serverless`ターゲットは、[追加の制約](https://rauchg.com/2020/2019-in-review#serverless-upgrades-itself)を強制することで、あなたを[成功の落とし穴(原文: Pit of Success)](https://blog.codinghorror.com/falling-into-the-pit-of-success/)にはめてくれます。
```
https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/73#discussion_r456937213

2020-07-25 06:09 UTC, dmamira commented
修正したのですが、TextLintのエラーが出てしまいました。
このエラーの詳細が分からないのですが、どなたかわかる方はいらっしゃいますか？

2020-07-25 06:12 UTC, Shinyaigeek commented
あれ, 古いバージョンのtextlintが動いてますね 🤔 
対応考えてみますので, もうしばしお待ちください 🙇

2020-07-25 06:13 UTC, Shinyaigeek commented
@dmamira 一度今の `master` をマージしてみてもらってよろしいですか？ それで動くかもです...

2020-07-25 06:15 UTC, dmamira commented
コミットする前に、
```$ git fetch upstream/master```
をしてから、
``` $git merge upstream/master```
をしましたが、もう一度実行したほうがいいですかね？

2020-07-25 06:29 UTC, dmamira commented
空コミットしたら通りました！ありがとうございます。

2020-07-26 06:28 UTC, dmamira commented
何か改善する点はまだありますか？

2020-07-26 07:05 UTC, yokinist commented
@dmamira 
ご確認遅れて申し訳ありません 🙇‍♂️
こちら文末の表記に関して原文に揃えるのを 1点 お願いしたいです！
https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/pull/73#discussion_r456939597

2020-07-26 07:07 UTC, dmamira commented
承知しました！修正します！

2020-07-26 11:18 UTC, dmamira commented
完了しました！

2020-07-26 12:31 UTC, yokinist submitted a review, later dismissed
ありがとうございました！
僕からはLGTMです👍

2020-07-26 13:18 UTC, hoosan commented
確認しました！関連事項の翻訳もお願いできますでしょうか🙏
以下はSuggestionです

```
<div class="card">
  <a href="/docs/api-reference/next.config.js/introduction.md">
    <b>next.config.js の紹介</b>
    <small>Next.js で使われる設定ファイルについて詳しく学びましょう。</small>
  </a>
</div>

<div class="card">
  <a href="/docs/deployment.md">
    <b>デプロイ</b>
    <small>Next.js のアプリをコンパイルし開発環境へデプロイしましょう。</small>
  </a>
</div>

```

2020-07-26 13:21 UTC, hiro08gh commented
翻訳していただきありがとうございました！LGTMです！

2020-07-26 13:21 UTC, hiro08gh submitted a review, later dismissed

2020-07-26 13:27 UTC, hiro08gh commented
@all-contributors please add @dmamira  for translation

2020-07-26 13:27 UTC, hiro08gh approved these changes

2020-07-26 13:28 UTC, hoosan approved these changes

2020-07-26 13:31 UTC, merged