docs: translate docs/advanced-features/custom-error-page.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #77
Opened 2020-07-20 00:56 UTC by syakoo

`docs/advanced-features/custom-error-page.md`を翻訳しました。
レビューよろしくお願いします。

2020-07-20 05:18 UTC, Shinyaigeek requested changes
ありがとうございます！
いくつか指摘, コメントさせていただいたので, 確認よろしくお願いします 🙏

2020-07-20 05:18 UTC, Shinyaigeek commented on docs/advanced-features/custom-error-page.md
> +description: カスタムエラーを処理するために組み込みのエラーページを上書きして拡張しましょう。
```suggestion
description: エラー処理をカスタマイズするために組み込みのエラーページを上書きして拡張しましょう。
```

カスタムエラーを処理 :thinking: と一瞬なったので, カスタムされたエラーを処理 -> エラー処理をカスタマイズまで意訳してもいいかと思われましたがどうでしょうか？

2020-07-20 05:18 UTC, Shinyaigeek commented on docs/advanced-features/custom-error-page.md
> +`pages/404.js`ファイルを作成することで、カスタムの404ページを作ることができます。このファイルはビルド時に静的に生成されます。
```suggestion
`pages/404.js`ファイルを作成することで、カスタマイズされた404ページを作ることができます。このファイルはビルド時に静的に生成されます。
```

めちゃくちゃ細かいですが, 「カスタムの」 -> 「カスタマイズされた」の方が違和感がないように思われましたがどうでしょうか？

2020-07-20 05:18 UTC, Shinyaigeek commented on docs/advanced-features/custom-error-page.md
> +> `pages/_error.js`は運用時でのみ使われます。開発時ではエラーがどこから発生したのかを知るためのコールスタックでエラーを取得します。
```suggestion
> `pages/_error.js`は本番環境でのみ使われます。開発時ではエラーがどこから発生したのかを知るためのコールスタックでエラーを取得します。
```

運用時より, 「プロダクション環境」や「本番環境」の方が一般的かなと思いましたがどうでしょうか？
( `開発時` に合わせるのであれば, 運用時のまま, あるいは本番環境の運用時まで訳する, あるいは 「開発時」-> 「開発環境」にするとかもあるかもですね)

2020-07-20 05:30 UTC, syakoo commented on docs/advanced-features/custom-error-page.md
> +description: カスタムエラーを処理するために組み込みのエラーページを上書きして拡張しましょう。
ご指摘ありがとうございます。確かにカスタムエラーはわかりにくいですね。
見出しの"Custom Error Page"は"カスタムエラーページ"と訳しましたが、"エラーページのカスタマイズ"に変更した方がよろしいですか？

2020-07-20 05:33 UTC, syakoo commented on docs/advanced-features/custom-error-page.md
> +> `pages/_error.js`は運用時でのみ使われます。開発時ではエラーがどこから発生したのかを知るためのコールスタックでエラーを取得します。
ご指摘ありがとうございます。確かに本番環境が一番しっくりきますね！

2020-07-20 05:35 UTC, syakoo commented
確認しました。添削ありがとうございます。

2020-07-20 13:12 UTC, hoosan submitted a review, later dismissed
LGTMです👍

2020-07-21 00:20 UTC, Shinyaigeek commented on docs/advanced-features/custom-error-page.md
> +description: カスタムエラーを処理するために組み込みのエラーページを上書きして拡張しましょう。
そうですね, お願いします 🙏

2020-07-21 01:00 UTC, syakoo commented
`manifest.json`の`Custom Error Page`を"エラーページのカスタマイズ"に修正しました。確認よろしくお願いします。

2020-07-21 01:19 UTC, syakoo commented
全角文字と半角文字、インラインコードの前後にスペースを入れました。
ごちゃごちゃしてしまい申し訳ないですが、ご確認よろしくお願いします。

2020-07-22 14:35 UTC, hoosan approved these changes

2020-07-23 02:59 UTC, Shinyaigeek approved these changes
対応ありがとうございます！ LGTMです :+1:

2020-07-23 03:00 UTC, Shinyaigeek commented
@all-contributors add @syakoo for translation

2020-07-23 03:00 UTC, merged