docs: translate docs/api-reference/next/head.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #85
Opened 2020-07-21 09:58 UTC by kentaro84207

`docs/api-reference/next/head.md` を翻訳いたしました。
レビューお願いいたします。

※ このPRの `docs/manifest.json` は変更の必要かと判断しました

2020-07-21 14:19 UTC, hoosan requested changes
LGTM with nitsです！２点コメントしましたのでご確認ください🙏

2020-07-21 14:19 UTC, hoosan commented on docs/api-reference/next/head.md
> +description: ビルトインのヘッドコンポーネントを用いてページの `head` にカスタム要素を追加します。
```suggestion
description: ビルトインの Head コンポーネントを用いてページの `head` にカスタム要素を追加します。
```
原文が文中にも関わらず大文字始まりの "Head" となっていることから、"Head" というコンポーネントであることを強調できるように、そのまま記載するのはいかがでしょうか？

2020-07-21 14:19 UTC, hoosan commented on docs/api-reference/next/head.md
> +この場合、2番目の `<meta property="og:title" />` のみがレンダリングされます。name属性が重複する `meta` タグは自動的に処理されます。
```suggestion
この場合、2番目の `<meta property="og:title" />` のみがレンダリングされます。`name` 属性が重複する `meta` タグは自動的に処理されます。
```
原文と合わせました！

2020-07-21 14:45 UTC, hoosan requested changes
すみません、追加で1つコメントしました！

2020-07-21 14:45 UTC, hoosan commented on docs/api-reference/next/head.md
> +Next.js はページの `head` に要素を追加するためのビルトインコンポーネントを公開しています。
```suggestion
Next.js はページの `head` に要素を追加するためのビルトインコンポーネントを公開しています:
```
コードブロック前の文末コロンはそのままでお願いします🙏

2020-07-21 23:38 UTC, kentaro84207 commented on docs/api-reference/next/head.md
> +description: ビルトインのヘッドコンポーネントを用いてページの `head` にカスタム要素を追加します。
私の方でも少し悩んだ箇所でした。"Head" で適切かと思います！

2020-07-21 23:38 UTC, kentaro84207 commented on docs/api-reference/next/head.md
> +この場合、2番目の `<meta property="og:title" />` のみがレンダリングされます。name属性が重複する `meta` タグは自動的に処理されます。
ありがとうございます 🙇

2020-07-21 23:40 UTC, kentaro84207 commented on docs/api-reference/next/head.md
> +Next.js はページの `head` に要素を追加するためのビルトインコンポーネントを公開しています。
ありがとうございます 🙇 
35行目にもコードブロック前の文末コロンが存在していたので、そちらもそのまま残しておこうと思います。

2020-07-21 23:54 UTC, kentaro84207 commented
レビューありがとうございます！
ご指摘頂いた箇所修正いたしました。

2020-07-22 14:41 UTC, hoosan approved these changes
修正ありがとうございます！LGTMです👍

2020-07-22 15:22 UTC, hiro08gh approved these changes

2020-07-22 15:23 UTC, hiro08gh commented
翻訳していただきありがとうございます！LGTMです。

2020-07-22 15:23 UTC, merged

2020-07-23 03:33 UTC, hiro08gh commented
@all-contributors add @kentaro84207 for translation