docs: translate ocs/advanced-features/customizing-postcss-config.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #88
Opened 2020-07-21 13:25 UTC by yamanoku

https://nextjs.org/docs/advanced-features/customizing-postcss-config
翻訳しました。よろしくお願いいたします。

2020-07-21 14:39 UTC, hoosan requested changes
翻訳ありがとうございます！LGTM with nitsです！
2点コメントしましたのでご確認ください🙏

2020-07-21 14:39 UTC, hoosan commented on docs/advanced-features/customizing-postcss-config.md
> +何も設定していない場合、Next.js は以下のような変換をして CSS をコンパイルします:
```suggestion
何も設定していなくても、Next.js は以下のような変換によって CSS をコンパイルします:
```
"out of the box, with no configuration"は「初期設定で、何の設定もなしに」と少々強調しており「何も設定していないのにできる」という得意げなニュアンスを感じます。なので「何も設定していなくても」とするのはどうでしょうか？

2020-07-21 14:39 UTC, hoosan commented on docs/advanced-features/customizing-postcss-config.md
> +1. Autoprefixer は、CSS ルールセットにベンダープレフィックスを自動的に追加します（IE11 に戻す）。
```suggestion
1. [Autoprefixer](https://github.com/postcss/autoprefixer) は、CSS ルールセットにベンダープレフィックスを自動的に追加します（IE11 に戻す）。
```
原文のリンクを追加しました！

2020-07-22 09:49 UTC, yamanoku commented on docs/advanced-features/customizing-postcss-config.md
> +何も設定していない場合、Next.js は以下のような変換をして CSS をコンパイルします:
> 「初期設定で、何の設定もなしに」と少々強調しており「何も設定していないのにできる」という得意げなニュアンス
なるほど。。。勉強になりました

2020-07-22 09:50 UTC, yamanoku commented on docs/advanced-features/customizing-postcss-config.md
> +1. Autoprefixer は、CSS ルールセットにベンダープレフィックスを自動的に追加します（IE11 に戻す）。
ありがとうございます！こちら対応しました

2020-07-22 09:51 UTC, yamanoku commented
@hoosan レビューありがとうございます。2点対応しましたのでよろしくお願いします

2020-07-22 14:43 UTC, hoosan approved these changes
修正いただきありがとうございます！LGTMです👍

2020-07-22 14:44 UTC, hiro08gh approved these changes

2020-07-22 14:44 UTC, merged

2020-07-22 14:44 UTC, hiro08gh commented
翻訳していただきありがとうございます！LGTMです！