docs: translate docs/basic-features/data-fetching.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #89
Opened 2020-07-21 15:00 UTC by ossan-engineer

docs/basic-features/data-fetching.mdを翻訳しました。

2020-07-21 15:28 UTC, ossan-engineer commented
text-lintの設定に差分が出ていたようなので修正中です。

2020-07-21 15:32 UTC, ossan-engineer commented
lintエラー修正しました。お手すきでレビューお願いいたします:pray:

2020-07-21 15:34 UTC, hiro08gh commented
翻訳していただきありがとうございます！順次レビューしますのでお待ちください！

2020-07-22 15:57 UTC, hoosan requested changes
大変な長文をご担当いただきましてありがとうございます！！
訳文についてはLGTM with nitsで、気になった数点についてコメント致しました！
また、表示が崩れているところもコメントしましたのでご確認いただけますと幸いです！

2020-07-22 15:57 UTC, hoosan commented on docs/basic-features/data-fetching.md
> +- [`getStaticProps`](#getstaticprops-static-generation)（静的生成）: **ビルド時**のデータ取得する
```suggestion
- [`getStaticProps`](#getstaticprops-static-generation)（静的生成）: **ビルド時**にデータ取得する
```
"at build time"ですので、ビルド時に、が適切かと思います！

2020-07-22 15:57 UTC, hoosan commented on docs/basic-features/data-fetching.md
> +`context`パラメータは次のキーを含むオブジェクトです。
ここは他のレビュアーへのコメントですが、コードブロック前ではないのでコロンではなく句点として良いと思うのですがどうでしょうか？

2020-07-22 15:57 UTC, hoosan commented on docs/basic-features/data-fetching.md
> +// この関数はサーバー側でのビルド時に呼び出されます。
ここも他のレビュアーへのコメントです。
コードブロック内の句点の扱いについて、このブロックのように原文にピリオドがついている場合は日本語も句点をつけて良いと思うのですがいかがでしょうか？

2020-07-22 15:57 UTC, hoosan commented on docs/basic-features/data-fetching.md
> +この JSON ファイルは、`next/link`([ドキュメント](/docs/api-reference/next/link.md))もしくは `next/router` ([ドキュメント](/docs/api-reference/next/router.md))経由のクライアント側のルーティングで使われます。`getStaticProps`　でプリレンダリングされたページに遷移すると、Ne
```suggestion
この JSON ファイルは、`next/link`([ドキュメント](/docs/api-reference/next/link.md))もしくは `next/router` ([ドキュメント](/docs/api-reference/next/router.md))経由のクライアント側のルーティングで使われます。`getStaticProps`　でプリレンダリングされたページに遷移すると、Next.js はこの JSON ファイル（ビルド時に事前処理）を取得してページコンポーネントの props として使います。つまり、クライアント側のページ遷移は `getStaticProps` を呼び出さず、エクスポートされた JSON だけが使われます。
```
確かに原文は"pre-computed"なのですが、日本語としては「事前処理」の方が自然と思いましたがいかがでしょうか？

2020-07-22 15:57 UTC, hoosan commented on docs/basic-features/data-fetching.md
> +####`paths`キー（必須）
```suggestion
#### `paths`キー（必須）
```
ここはスペースがないと表示が崩れるようです！

2020-07-22 15:57 UTC, hoosan commented on docs/basic-features/data-fetching.md
> +`paths`キーはどのパスがプリレンダリングされるかを決定します。たとえば、動的ルートを使った `pages/posts/[id].js` というページがあります。このページから `getStaticPaths` をエクスポートして `paths` に次のような値を返すとしましょう。
```suggestion
`paths`キーはどのパスがプリレンダリングされるかを決定します。たとえば、動的ルートを使った `pages/posts/[id].js` というページがあるとします。このページから `getStaticPaths` をエクスポートして `paths` に次のような値を返すとしましょう:
```
"suppose"のニュアンスを加えました。また、コードブロック前の文末コロンはそのままでお願いします！

2020-07-22 15:57 UTC, hoosan commented on docs/basic-features/data-fetching.md
> +Next.js はビルド時に `pages/posts/[id].js` でページコンポーネントを使って `静的に` posts/1`と`posts/2`を生成します。
```suggestion
Next.js はビルド時に `pages/posts/[id].js` でページコンポーネントを使って静的に ` posts/1` と `posts/2` を生成します。
```
表示を修正しました！

2020-07-22 15:57 UTC, hoosan commented on docs/basic-features/data-fetching.md
> +各 `params` の値はページ名で使われたパラメータと一致しなければならないことに注意してください。
```suggestion
それぞれの `params` の値はページ名で使われたパラメータと一致しなければならないことに注意してください。
```
「各 `params`」が少し唐突だったのでそれぞれのとしてみましたがいかがでしょうか？

2020-07-22 15:57 UTC, hoosan commented on docs/basic-features/data-fetching.md
> +データをプリレンダリングする必要がなければ、クライアント側でのデータ取得を検討すべきです。[詳細はこちら]](#fetching-data-on-the-client-side)。
```suggestion
データをプリレンダリングする必要がなければ、クライアント側でのデータ取得を検討すべきです。[詳細はこちら](#fetching-data-on-the-client-side)。
```
表示を修正しました！

2020-07-22 15:57 UTC, hoosan commented on docs/basic-features/data-fetching.md
> +`getServerSideProps`はサーバー側でのみ実行され、ブラウザでは決して実行されません。ページが `getServerSideProps` を使うとこのような挙動になります。
```suggestion
`getServerSideProps`はサーバー側でのみ実行され、ブラウザでは決して実行されません。ページが `getServerSideProps` を使うと次のような挙動になります。
```
細かいですが、「このような」が係る部分が少しわかりにくいと感じましたので修正してみましたがいかがでしょうか？

2020-07-22 15:57 UTC, hoosan commented on docs/basic-features/data-fetching.md
> +ページが頻繁に更新されるデータを持ち、データをプリレンダリングする必要がないようであれば、クライアント側でデータ取得もできます。ユーザー固有のデータなどが該当します。このように機能します。
```suggestion
ページが頻繁に更新されるデータを持ち、データをプリレンダリングする必要がないようであれば、クライアント側でデータ取得もできます。ユーザー固有のデータなどが該当します。次のように機能します。
```
この部分も「このように」を「次のように」に変えてみましたがいかがでしょうか？

2020-07-22 15:57 UTC, hoosan commented on docs/basic-features/data-fetching.md
> +このアプローチは、ユーザーダッシュボードのようなページで活用できます。ダッシュボードはプライベートかつユーザー固有のページであり、SEO も不要なのでページをプリレンダリングする必要もないためです。データは頻繁に更新され、リクエスト時のデータ取得を必要とします。
```suggestion
このアプローチは、ユーザーダッシュボードのようなページに有効です。ダッシュボードはプライベートかつユーザー固有のページであり、SEO も不要なのでページをプリレンダリングする必要もないためです。データは頻繁に更新され、リクエスト時のデータ取得を必要とします。
```
"works well"とありますので、「有効です」と訳すのはいかがでしょう？

2020-07-22 15:57 UTC, hoosan commented on docs/basic-features/data-fetching.md
> +Next.js の開発チームはデータ取得用の [**SWR**](https://swr.now.sh/) という React フックを作成しました。クライアント側でデータ取得する際にはその利用を強くお勧めします。キャシュ、再バリデーション、フォーカスの追跡、一定間隔での再取得などを処理できます。このように使用します。
```suggestion
Next.js の開発チームはデータ取得用の [**SWR**](https://swr.now.sh/) という React フックを作成しました。クライアント側でデータ取得する際にはその利用を強くお勧めします。キャシュ、再バリデーション、フォーカスの追跡、一定間隔での再取得などを処理できます。次のように使用します。
```
こちらも上と同様です！

2020-07-22 16:07 UTC, hiro08gh commented on docs/basic-features/data-fetching.md
> +Next.js の開発チームはデータ取得用の [**SWR**](https://swr.now.sh/) という React フックを作成しました。クライアント側でデータ取得する際にはその利用を強くお勧めします。キャシュ、再バリデーション、フォーカスの追跡、一定間隔での再取得などを処理できます。このように使用します。
こちらキャシュというタイポを見つけたので、お手数ですが修正お願いいたします。

2020-07-22 16:26 UTC, hiro08gh reviewed
翻訳していただきありがとうございます！レビューコメントに答える形ですが、いくつかコメントしました！！

2020-07-22 16:26 UTC, hiro08gh commented on docs/basic-features/data-fetching.md
> +`context`パラメータは次のキーを含むオブジェクトです。
```suggestion
`context`パラメータは次のキーを含むオブジェクトです:
```
できるだけ末尾:で統一して欲しいです。

2020-07-22 16:26 UTC, hiro08gh commented on docs/basic-features/data-fetching.md
> +// この関数はサーバー側でのビルド時に呼び出されます。
ありがとうございます。確かに、コードブロックに句点がある場合は、翻訳も句点をつけた方がいい気がしますね。

2020-07-23 00:21 UTC, ossan-engineer commented
@hoosan @hiro08gh suggestion頂いた箇所は異論ないのでそのまま適用させて頂きました:pray:

2020-07-23 03:50 UTC, hiro08gh commented
ありがとうございます！僕からはLGTMです！

2020-07-23 03:50 UTC, hiro08gh submitted a review, later dismissed

2020-07-23 10:08 UTC, hoosan submitted a review, later dismissed
ありがとうございます！LGTMです👍

2020-07-23 10:33 UTC, hiro08gh approved these changes

2020-07-23 10:36 UTC, hoosan approved these changes

2020-07-23 10:37 UTC, merged

2020-07-23 10:48 UTC, hiro08gh commented
@all-contributors please add @ossan-engineer   for translation