docs: translate docs/advanced-features/custom-document.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #90
Opened 2020-07-21 17:00 UTC by takefumi-yoshii

https://nextjs.org/docs/advanced-features/custom-document
翻訳しました。よろしくお願いいたします。

2020-07-22 16:13 UTC, hoosan requested changes
翻訳いただきありがとうございます！いくつかコメントしましたのでご確認ください🙏

2020-07-22 16:13 UTC, hoosan commented on docs/advanced-features/custom-document.md
> +description: Next.jsによって追加された、デフォルトのドキュメントマークアップを拡張する
```suggestion
description: Next.jsによって追加された、デフォルトのドキュメントマークアップを拡張する。
```
細かくて恐縮ですが、原文にピリオドがありますので訳文にも句点を追加させてください🙇‍♂️

2020-07-22 16:13 UTC, hoosan commented on docs/advanced-features/custom-document.md
> +デフォルトの `Document` をオーバーライドするには `./pages/_document.js` ファイルを作成し、次のように `Document` クラスを拡張します。
```suggestion
デフォルトの `Document` をオーバーライドするには `./pages/_document.js` ファイルを作成し、次のように `Document` クラスを拡張します:
```
表記の統一のため、コードブロック直前の文末コロンはそのままでお願いいたします🙇‍♂️

2020-07-22 16:13 UTC, hoosan commented on docs/advanced-features/custom-document.md
> +カスタム属性は `lang` のように props として許可されます。
```suggestion
カスタム属性は `lang` のように props として許可されます:
```
こちらも同様です！

2020-07-22 16:13 UTC, hoosan commented on docs/advanced-features/custom-document.md
> +> `renderPage` をカスタマイズする必要があるのは、**css-in-js** ライブラリなどで、サーバーサイドレンダリングを適切に処理するために、アプリケーションをラップする時です。
```suggestion
> `renderPage` をカスタマイズする必要があるのは、**css-in-js** ライブラリなどで、サーバーサイドレンダリングを適切に処理するために、アプリケーションをラップする時だけです。
```
"the only reason"とありますので、「だけ」を加えましたがいかがでしょうか？

2020-07-22 16:13 UTC, hoosan commented on docs/advanced-features/custom-document.md
> +カスタマイズするために、オプションオブジェクトを引数として受け取ります。
```suggestion
カスタマイズするために、オプションオブジェクトを引数として受け取ります:
```

2020-07-22 16:16 UTC, hoosan requested changes

2020-07-22 16:16 UTC, hoosan commented on docs/advanced-features/custom-document.md
> +カスタム `Document` は通常、アプリケーションの `<html>` タグと `<body>` タグを拡張するために使用されます。これはドキュメント関連事項のマークアップ定義を Next.js pages が省略するために必要です。
```suggestion
カスタム `Document` は通常、アプリケーションの `<html>` タグと `<body>` タグを拡張するために使用されます。これはドキュメントのマークアップ定義を Next.js pages が省略するために必要です。
```
ドキュメントのマークアップ定義とした方がシンプルかと思いましたがいかがでしょう？

2020-07-23 00:51 UTC, takefumi-yoshii commented on docs/advanced-features/custom-document.md
> +カスタム `Document` は通常、アプリケーションの `<html>` タグと `<body>` タグを拡張するために使用されます。これはドキュメント関連事項のマークアップ定義を Next.js pages が省略するために必要です。
そうですね！この方が意味としても伝わりますし、シンプルだと思います！

2020-07-23 00:52 UTC, takefumi-yoshii commented
@hoosan レビューありがとうございます。概ね異論ありませんので、suggestion 取り込みました！

2020-07-23 03:13 UTC, Shinyaigeek approved these changes
翻訳ありがとうございます！ LGTMです :+1:

2020-07-23 03:13 UTC, Shinyaigeek commented
@all-contributors add @takefumi-yoshii for translation

2020-07-23 10:09 UTC, hoosan approved these changes
ありがとうございます！LGTMです👍

2020-07-23 10:23 UTC, merged