docs: translate docs/api-reference/next.config.js/introduction.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #92
Opened 2020-07-22 08:39 UTC by resqnet

docs/api-reference/next.config.js/introduction.mdを翻訳しました。
レビューよろしくお願いします。

2020-07-22 16:25 UTC, hoosan requested changes
翻訳ありがとうございます！LGTM with nitsです！数点ご確認ください🙏

2020-07-22 16:25 UTC, hoosan commented on docs/api-reference/next.config.js/introduction.md
> +Next.js の高度な動作をカスタマイズするには、プロジェクトディレクトリのルートに `next.config.js` を作成します。(`package.json` と同じディレクトリ)
```suggestion
Next.js の高度な動作をカスタマイズするには、プロジェクトディレクトリのルートに `next.config.js` を作成します(`package.json` と同じディレクトリ)。
```

2020-07-22 16:25 UTC, hoosan commented on docs/api-reference/next.config.js/introduction.md
>  > 利用する Node.js のバージョンでは利用出来ない JavaScript の機能を使用しないようにしましょう。 `next.config.js` は Webpack、Babel、TypeScriptで解析されません。
```suggestion
> 利用する Node.js のバージョンで利用出来ない JavaScript の新機能を使用しないようにしましょう。 `next.config.js` は Webpack、Babel、TypeScriptで解析されません。
```
"new JavaScript features"とあるので新機能としてみましたがいかがでしょうか？

2020-07-23 03:04 UTC, resqnet commented on docs/api-reference/next.config.js/introduction.md
>  > 利用する Node.js のバージョンでは利用出来ない JavaScript の機能を使用しないようにしましょう。 `next.config.js` は Webpack、Babel、TypeScriptで解析されません。
利用するNodeのバージョンに依存するということが伝えたいのでこうしたのですが、
原文では新機能を指しているので提案の修正にします。

2020-07-23 03:06 UTC, resqnet commented
@hoosan 
レビューありがとうございました。
修正Doneです。

2020-07-23 03:21 UTC, hiro08gh commented
ありがとうございます！僕からはLGTMです！

2020-07-23 03:21 UTC, hiro08gh approved these changes

2020-07-23 10:11 UTC, hoosan approved these changes
ありがとうございます！LGTMです👍

2020-07-23 10:23 UTC, merged

2020-07-23 10:47 UTC, hiro08gh commented
@all-contributors please add @resqnet  for translation