Docs/api reference/next.config.js/runtime configuration
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #95
Opened 2020-07-22 15:31 UTC by KushibikiMashu

`docs/api-reference/next.config.js/runtime-configuration.md`を翻訳しました。

- 原文を忠実に翻訳するよりは、原語に添いながらも意図を汲んで日本語として読みやすい訳を心がけました。
- 文中の `Runtime Configuration`  `Runtime Config`  を「ランタイムの設定」と訳すか迷いましたが、「ランタイムの設定」では意味がわかりにくいことと、`Runtime Configuration` という機能名であると考えて、原語のままにしました。

レビューのほどよろしくお願いします。

2020-07-22 18:52 UTC, yokinist reviewed
翻訳いただきありがとうございます！
細かいところも多く恐縮ですが変更の提案を送らせていただきました 🙇 
問題なければ取り込んでいただき、別途検討が必要な箇所については追加でコメントいただけると嬉しいです。
ご確認お願いします！

---

> 文中の Runtime Configuration Runtime Config を「ランタイムの設定」と訳すか迷いましたが、「ランタイムの設定」では意味がわかりにくいことと、Runtime Configuration という機能名であると考えて、原語のままにしました。

まだルールとしては明文化されていないものの個人としては原文表記のままがいいとされるケースは
- 原文の方がニュアンスが伝わりやすい場合
- 日本語に訳すものが見当たらない場合

になるのかなと思っています(もう1人のレビュアーの方にも意見いただきたい箇所で要検討)。今回の場合だと、`Runtime Configuration` は `ランタイム設定` として訳してニュアンスが十分に伝わるのではないかと思いましたが、いかがでしょうか？以下、その前提で Suggested change させていただいております。

※ また、基本的に `runtime config(s)` は「ランタイムの設定」とし `runtime configuration` は機能名「ランタイム設定」として区別していますが、いいアイデアがあればコメントいただけると嬉しいです

2020-07-22 18:52 UTC, yokinist commented on docs/api-reference/next.config.js/runtime-configuration.md
> +description: クライアント側とサーバー側のランタイムの設定をあなたの Next.js アプリケーションに追加します。
```suggestion
description: クライアント側とサーバー側のランタイム設定を Next.js アプリケーションに追加します。
```
「の」が続いてしまうので、`ランタイムの設定`  -> `ランタイム設定` の方がスッキリしていいかと思いました。
また、`your` はここでは訳さない方が自然かなと思いました！

2020-07-22 18:52 UTC, yokinist commented on docs/api-reference/next.config.js/runtime-configuration.md
> +> 一般的に、あなたの Next.js アプリケーションに設定値を渡すためには [build-time environment variables](/docs/api-reference/next.config.js/environment-variables.md) を使いたいです。なぜなら、 Runtime configuration は レンダリング / 初期化 のオーバーヘッドにつなが
```suggestion
> 一般的には、 [環境変数](/docs/api-reference/next.config.js/environment-variables.md) を使用して設定を行うのがいいでしょう。なぜなら、ランタイム設定はレンダリング / 初期化時の余計な処理につながり、また [Automatic Static Optimization](/docs/advanced-features/automatic-static-optimization.md) と互換性がないからです。
```
それぞれ細かいですが提案内容とその理由について書かせていただきます
1. `Next.js アプリケーションに` というのは description には記述されていますが、Next.js のドキュメントということもあり文脈として前提になっており、原文にもないのでここでは記述しなくてもいいのではと思いました。
2. `you'll want to` のニュアンスとしては控えめな提案としてここでは用いられているかなと思ったので文体を少し変えました。
3. `build-time environment variables` については所謂、日本語の `環境変数` のことをさしているので原文表記から訳しました。
4. `オーバーヘッド` とそのまま表記するよりも `余計な処理` としたほうが自然な訳かなと思いました。

2020-07-22 18:52 UTC, yokinist commented on docs/api-reference/next.config.js/runtime-configuration.md
> +# Runtime configuration
```suggestion
# ランタイム設定
```

2020-07-22 18:52 UTC, yokinist commented on docs/api-reference/next.config.js/runtime-configuration.md
> +> Runtime configuration は [`serverless` target](/docs/api-reference/next.config.js/build-target.md#serverless-target) のときは利用できません。
```suggestion
> ランタイム設定は [`serverless` target](/docs/api-reference/next.config.js/build-target.md#serverless-target) のときは利用できません。
```

2020-07-22 18:52 UTC, yokinist commented on docs/api-reference/next.config.js/runtime-configuration.md
> +Runtime configuration をあなたのアプリケーションに追加するためには、 `next.config.js` に `publicRuntimeConfig` と `serverRuntimeConfig` を記述してください:
```suggestion
ランタイム設定を追加するためには、`next.config.js` に `publicRuntimeConfig` と `serverRuntimeConfig` を記述してください:
```
`your app` は日本語に訳さないほうが自然かなと思いました！

2020-07-22 18:52 UTC, yokinist commented on docs/api-reference/next.config.js/runtime-configuration.md
> +サーバー側だけで利用する値であれば、 Runtime config は `serverRuntimeConfig` に記述します。
```suggestion
サーバー側だけで利用する値であれば、ランタイム設定は `serverRuntimeConfig` に記述してください。
```
表記の統一の観点から

2020-07-22 18:52 UTC, yokinist commented on docs/api-reference/next.config.js/runtime-configuration.md
> +クライアント側とサーバー側のどちらのコードからも使う値であれば、 `publicRuntimeConfig` に記述しましょう。
```suggestion
クライアント側とサーバー側のどちらのコードからも使う値であれば、 `publicRuntimeConfig` に記述してください。
```

2020-07-22 18:52 UTC, yokinist commented on docs/api-reference/next.config.js/runtime-configuration.md
> +> `publicRuntimeConfig` を使用しているページは [Automatic Static Optimization](/docs/advanced-features/automatic-static-optimization.md) の対象から除外するために、 **必ず** `getInitialProps` を使ってください。 Runtime configuration は
```suggestion
> `publicRuntimeConfig` に依存しているページは [Automatic Static Optimization](/docs/advanced-features/automatic-static-optimization.md) の対象から除外するために、 **必ず** `getInitialProps` を使ってください。 ランタイム設定は `getInitialProps` を使っていないページ（またはページ内のコンポーネント）では利用できません。
```
- わかりやすく配慮いただき恐縮ですが、 `relies on` に関しては「〜を使用する」よりも 「〜に依存する」としたほうが直接的でニュアンスが伝わりやすい気がしました。

2020-07-22 18:52 UTC, yokinist commented on docs/api-reference/next.config.js/runtime-configuration.md
> +あなたのアプリケーションで Runtime config を利用するためには `next/config` を以下のように記述してください:
```suggestion
アプリケーション内でランタイム設定を利用するためには `next/config` を以下のように記述してください:
```
`your` はここでは訳さない方が自然かなと思いました。
また、`in` の訳としては「ページ内のコンポーネント」と同じように `~内で` のほうが適切かと思いました。

2020-07-22 18:52 UTC, yokinist commented on docs/api-reference/next.config.js/runtime-configuration.md
> +    <b>next.config.js の概要:</b>
```suggestion
    <b>next.config.js の紹介:</b>
```
ルール化できてなくてすいません🙏
表記の統一ため、こちらは `紹介` でお願いします！
https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/blob/master/docs/api-reference/next.config.js/environment-variables.md#%E9%96%A2%E9%80%A3%E4%BA%8B%E9%A0%85

2020-07-22 18:52 UTC, yokinist commented on docs/api-reference/next.config.js/runtime-configuration.md
> +    <small>あなたの Next.js アプリケーションのビルド時に環境変数を利用する。</small>
```suggestion
    <small>Next.js アプリケーションのビルド時に環境変数を利用する。</small>
```
`your` はここでは訳さない方が自然かなと思いました

2020-07-22 18:52 UTC, yokinist commented on docs/api-reference/next.config.js/runtime-configuration.md
> +    <small>Next.js の設定ファイルについてもっと学ぶ。</small>
```suggestion
    <small>Next.js の設定ファイルについて学ぶ。</small>
```
上に同じく統一性の観点からこちらでお願いします。

2020-07-22 19:14 UTC, yokinist commented on docs/manifest.json
> +              "title": "ランタイムの設定",
```suggestion
              "title": "ランタイム設定",
```
`runtime config(s)` は「ランタイム設定」とし `runtime configuration` は「ランタイムの設定」として表記を合わせました

2020-07-23 04:29 UTC, yokinist requested changes
(普通にコメントとして書き込んでしまいましたが、Request changes として送らせていただきます)

2020-07-23 05:26 UTC, KushibikiMashu commented
>  runtime config(s) は「ランタイムの設定」とし runtime configuration は機能名「ランタイム設定」として区別しています

こちらでいいと思います 🙋‍♂️
Suggestion適用しました！

2020-07-23 05:35 UTC, yokinist approved these changes
早速のご確認ありがとうございます！僕からはLGTMです👍👍

2020-07-23 10:49 UTC, hoosan approved these changes
LGTMです！👍

2020-07-23 10:50 UTC, merged

2020-07-23 11:07 UTC, hiro08gh commented
@all-contributors add @rikusen0335 for translation

2020-07-23 11:08 UTC, hiro08gh commented
@all-contributors add @KushibikiMashu  for translation