docs: translate docs/api-reference/next/amp.md
Nextjs-ja-translation/Nextjs-ja-translation-docs pull request #99
Opened 2020-07-23 03:30 UTC by kentaro84207

`docs/api-reference/next/amp.md` を翻訳いたしました。
レビューお願いいたします。

原文： https://nextjs.org/docs/api-reference/next/amp

※ このPRの docs/manifest.json は変更不要かと判断しました

2020-07-23 04:03 UTC, thesugar requested changes
翻訳ありがとうございます！
ほぼ完璧と思うのですが、一点だけ（かなり些細で取るに足らないような部分ですが）コメント入れましたので、お手数ですがご確認お願いします 🙇‍♂️

2020-07-23 04:03 UTC, thesugar commented on docs/api-reference/next/amp.md
> +- `'hybrid'` - ページには AMP を使用したものと HTML を使用したものの 2 つのバージョンがあります
```suggestion
- `'hybrid'` - ページは AMP を使用したものと HTML を使用したものの 2 つのバージョンを持ちます
```
非人物である page に対して have を「持つ」と訳出すると直訳感も出てしまうものの、
「この設定（`'hybrid'`）をしたことで→こうなる（2つのバージョンを持つようになる）」というような変化感を出すために、「2 つのバージョンを持ちます」のほうがわかりやすいかなと思いました（「2 つのバージョンがあります」だと元々そうであるような静的なイメージ）。

2020-07-23 08:42 UTC, kentaro84207 commented on docs/api-reference/next/amp.md
> +- `'hybrid'` - ページには AMP を使用したものと HTML を使用したものの 2 つのバージョンがあります
レビューありがとうございます！
 ご提案いただいた文章の方が自然でわかりやすいと思いました！😄

2020-07-23 15:28 UTC, thesugar submitted a review, later dismissed

2020-07-23 15:29 UTC, thesugar commented
ご対応ありがとうございます。私からは LGTM です 😸

2020-07-23 15:57 UTC, yokinist requested changes

2020-07-23 15:57 UTC, yokinist commented on docs/api-reference/next/amp.md
> +- ページは [AMP Optimizer](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer) によって自動的に最適化されます。AMP Optimizer は AMP キャッシュと同様の変換をするオプティマイザであり、パフォーマンスを最大 42 % 向上させます
```suggestion
- ページは [AMP Optimizer](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer) によって自動的に最適化されます。AMP Optimizer は AMP キャッシュと同様の変換をするオプティマイザであり、パフォーマンスを最大 42% 向上させます
```
再度とても細かいところで恐縮ですが 42 と % の間の半角スペースは不要かなと思いました！半角同士であり原文も繋がっているためです。何か別に意図があるのであれば、教えていただきたいです🙏

2020-07-23 23:29 UTC, kentaro84207 commented on docs/api-reference/next/amp.md
> +- ページは [AMP Optimizer](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer) によって自動的に最適化されます。AMP Optimizer は AMP キャッシュと同様の変換をするオプティマイザであり、パフォーマンスを最大 42 % 向上させます
レビューありがとうございます！ 
半角スペースを入れてしまっていたのは特に意図はなく、ミスになります🙇
細かい箇所まで見ていただき、ありがとうございます！

2020-07-23 23:43 UTC, yokinist approved these changes
ご確認ありがとうございます！LGTMです！

2020-07-24 02:28 UTC, thesugar approved these changes

2020-07-24 02:28 UTC, merged